export class Constant2017 {
    id = 17;
    header = 'Texas State Water Plan';
    region_footer =
        " The 2021 Regional Water Plans can be found on the TWDB website at: <a href='http://www.twdb.texas.gov/waterplanning/rwp/plans/2021/index.asp'>http://www.twdb.texas.gov/waterplanning/rwp/plans/2021/index.asp</a> .";
    allow_dl = true;
    MIN_RADIUS = 4;
    MAX_RADIUS = 9;

    tappend = 'vw2017Map';
    sourcemap = 'iswp_sourcefeatures2017.map';
    sourcetables = 'iswp_sourcefeatures2017';

    nav_categories = [
        { value: '', label: 'All of Texas' },
        {
            value: 'region',
            label: 'Planning Region',
            placeholder_override: 'Region'
        },
        { value: 'county', label: 'County' },
        { value: 'entity', label: 'Water User Group' },
        { value: 'usagetype', label: 'Usage Type' },
        { value: 'source', label: 'Water Source' },
        { value: 'project', label: 'WMS Project' },
        { value: 'wms', label: 'Water Management Strategy' },
        { value: 'wmstype', label: 'WMS Type' }
    ];
    
    regionalDescription = {
        A: 'The Panhandle (Region A) Regional Water Planning Area includes 21 counties split between the Canadian and Red River basins. The major cities in the region include Amarillo, Pampa, Borger, and Dumas. Groundwater from the Ogallala Aquifer is the region’s primary source of water and is used at a rate that exceeds recharge. The economy of this region is grounded in agribusiness. The full 2016 Panhandle (A) Regional Water Plan can be found on the TWDB Web site at',
        B: 'The Region B Regional Water Planning Area encompasses all or parts of 11 counties in north central Texas bordering the Red River. Parts of three river basins (Red, Brazos, and Trinity) lie within the region. The major cities in the region include Wichita Falls, Burkburnett, and Vernon. The main components of the region’s economy are farming, mineral production, and ranching. The full 2016 Region B Regional Water Plan can be found on the TWDB Web site at',
        C: 'The Region C Regional Water Planning Area includes all or parts of 16 counties. Overlapping much of the upper portion of the Trinity River Basin, Region C also includes smaller parts of the Red, Brazos, Sulphur, and Sabine river basins. The Dallas-Fort Worth metropolitan area is centrally located in the region, and its surrounding counties are among the fastest growing in the state. Major economic sectors in the region include service, trade, manufacturing, and government. The full 2016 Region C Regional Water Plan can be found on the TWDB Web site at',
        D: 'The North East Texas (Region D) Regional Water Planning Area encompasses all or parts of 19 counties. While largely rural, the region includes the cities of Longview, Texarkana, and Greenville. The planning area overlaps large portions of the Red, Sulphur, Cypress, and Sabine river basins and smaller parts of the Trinity and Neches river basins. The North East Texas Region’s main economic base is agribusiness, including a variety of crops, as well as cattle and poultry production. Timber, oil and gas, and mining are significant industries in the eastern portion of the region. In the western portion of the region, many residents are employed in the Dallas-Fort Worth metropolitan area. The full 2016 North East Texas (D) Regional Water Plan can be found on the TWDB Web site at',
        E: 'The Far West Texas (Region E) Regional Water Planning Area includes seven counties and lies within the Rio Grande Basin. The largest economic sectors in the region are agriculture, agribusiness, manufacturing, tourism, wholesale and retail trade, government, and military. The vast majority of the population in this planning area reside in El Paso County. The full 2016 Far West Texas (E) Regional Water Plan can be found on the TWDB Web site at',
        F: 'The Region F Regional Water Planning Area is located in the Edwards Plateau encompassing 32 counties. Intersected by the Pecos River to the south and the Colorado River to the north, most of the region is located in the upper portion of the Colorado River Basin and Pecos portion of the Rio Grande Basin; a small portion is in the Brazos Basin. The major cities in the region include Midland, Odessa, and San Angelo. The region’s economy relies heavily on healthcare, mining, manufacturing, agriculture, and oil and gas employment sectors. The full 2016 Region F Regional Water Plan can be found on the TWDB Web site at',
        G: 'The Brazos G Regional Water Planning Area includes all or parts of 37 counties. Over 90 percent of the region lies within the Brazos River Basin, with the Brazos River being the region’s primary source of water. The largest economic sectors in the region are service, manufacturing, and retail trade. Major cities in the region include Abilene, Bryan, College Station, Killeen, Round Rock, Temple, and Waco. The full 2016 Brazos (G) Regional Water Plan can be found on the TWDB Web site at',
        H: 'The Region H Regional Water Planning Area is composed of all or parts of 15 counties and includes portions of the Trinity, San Jacinto, Brazos, Neches, and Colorado river basins. The Houston metropolitan area is located within this region. The largest economic sector in Region H is the petrochemical industry, which accounts for two-thirds of the petrochemical production in the United States. Other major economic sectors in the region include medical services, tourism, government, agriculture, fisheries, and transportation, with the Port of Houston being the nation’s second largest port. The full 2016 Region H Regional Water Plan can be found on the TWDB Web site at',
        I: 'The East Texas (Region I) Regional Water Planning Area is composed of all or parts of 20 counties. The largest cities include Beaumont, Tyler, Port Arthur, Nacogdoches, and Lufkin. The major economic sectors are petrochemical, timber, and agriculture. The principal surface water sources are the Sabine and Neches Rivers and their tributaries. The full 2016 East Texas (I) Regional Water Plan can be found on the TWDB Web site at',
        J: 'Located on the southern edge of the Edwards Plateau, the Plateau (Region J) Regional Water Planning Area covers six counties. The region includes portions of the Colorado, Guadalupe, Nueces, Rio Grande, and San Antonio river basins. Land use in the western portion of the planning area is primarily range land, while the eastern portion is a mix of forest land, range land, and agricultural areas. The economy of this region is based primarily on tourism, hunting, ranching, and government. Major cities in the region include Del Rio and Kerrville. The full 2016 Plateau (J) Regional Water Plan can be found on the TWDB Web site at',
        K: 'The Lower Colorado (Region K) Regional Water Planning Area is composed of all or parts of 14 counties, portions of 6 river and coastal basins, and Matagorda Bay. Most of the region is located in the Colorado River Basin. Major cities in the region include Austin, Bay City, Pflugerville, and Fredericksburg. The largest economic sectors in the region include agriculture, government, service, manufacturing, and retail trade. The manufacturing sector is primarily concentrated in the technology and semiconductor industry in the Austin area. Oil, gas, petrochemical processing and mineral production are found primarily in Wharton and Matagorda counties near the coast. The full 2016 Lower Colorado (K) Regional Water Plan can be found on the TWDB Web site at',
        L: 'The South Central Texas (Region L) Regional Water Planning Area includes all or parts of 21 counties, portions of nine river and coastal basins, the Guadalupe Estuary, and San Antonio Bay. The largest cities in the region are San Antonio, Victoria, San Marcos, and New Braunfels. The region’s largest economic sectors are tourism, military, medical, service, manufacturing, and retail trade. The region contains the two largest springs in Texas: Comal and San Marcos. Water planning in the region is particularly complex because of the intricate relationships between the region’s surface and groundwater resources. The full 2016 South Central Texas (L) Regional Water Plan can be found on the TWDB Web site at',
        M: 'The Rio Grande (Region M) Regional Water Planning Area includes eight counties, with over 60 percent of the region lying within the Rio Grande Basin. Its major cities include Brownsville, McAllen, and Laredo. The international reservoirs of the Rio Grande are the region’s primary source of water. The largest economic sectors in the region are agriculture, trade, services, manufacturing, and hydrocarbon production. The full 2016 Rio Grande (M) Regional Water Plan can be found on the TWDB Web site at',
        N: 'The Coastal Bend (Region N) Regional Water Planning Area includes 11 counties, portions of the Nueces River Basin, and its adjoining coastal basins, including the Nueces Estuary. The region’s largest economic sectors are service industries, retail trade, government, construction, manufacturing, and the petrochemical industry. Corpus Christi is the region’s largest metropolitan area. The full 2016 Coastal Bend (N) Regional Water Plan can be found on the TWDB Web site at',
        O: 'The Llano Estacado (Region O) Regional Water Planning Area encompasses 21 counties in the southern High Plains of Texas. The region lies within the upstream parts of four major river basins (Canadian, Red, Brazos, and Colorado). Groundwater from the Ogallala Aquifer is the region’s primary source of water and is used at a rate that exceeds recharge. The largest economic sectors in the region are livestock and crop operations, producing about 60 percent of the state’s total cotton crop. Major cities in the region include Lubbock, Plainview, Levelland, Lamesa, Hereford, and Brownfield. The full 2016 Region O Regional Water Plan can be found on the TWDB Web site at',
        P: 'The Lavaca (Region P) Regional Water Planning Area is composed of Jackson and Lavaca counties and Precinct Three of Wharton County, including the entire City of El Campo. Other cities in the region include Edna, Yoakum, and Hallettsville. Most of the region lies in the Lavaca River Basin, with the Lavaca and Navidad Rivers being its primary source of surface water. Groundwater from the Gulf Coast Aquifer supplies most of the water for the planning area. The largest economic sector in the region is agribusiness, while manufacturing, oil and gas production, and mineral production also contribute to the region’s economy. The full 2016 Lavaca (P) Regional Water Plan can be found on the TWDB Web site at'
    };

    regionalLink = {
        A: 'A summary of the 2016 [Panhandle A] Regional Water Plan can be found at',
        B: 'A summary of the 2016 [Region B] Regional Water Plan can be found at',
        C: 'A summary of the 2016 [Region C] Regional Water Plan can be found at',
        D: 'A summary of the 2016 [North East Texas D] Regional Water Plan can be found at',
        E: 'A summary of the 2016 [Far West Texas E] Regional Water Plan can be found at',
        F: 'A summary of the 2016 [Region F] Regional Water Plan can be found at',
        G: 'A summary of the 2016 [Brazos G] Regional Water Plan can be found at',
        H: 'A summary of the 2016 [Region H] Regional Water Plan can be found at',
        I: 'A summary of the 2016 [East Texas I] Regional Water Plan can be found at',
        J: 'A summary of the 2016 [Plateau J] Regional Water Plan can be found at',
        K: 'A summary of the 2016 [Lower Colorado K] Regional Water Plan can be found at',
        L: 'A summary of the 2016 [South Central Texas L] Regional Water Plan can be found at',
        M: 'A summary of the 2016 [Rio Grande M] Regional Water Plan can be found at',
        N: 'A summary of the 2016 [Coastal Bend N] Regional Water Plan can be found at',
        O: 'A summary of the 2016 [Region O] Regional Water Plan can be found at',
        P: 'A summary of the 2016 [Lavaca P] Regional Water Plan can be found at'
    };

    /**
     * Create a Statewide.
     */
    DATA_TABLES = {
        demands: 'vw2017MapWugDemand',
        needs: 'vw2017MapWugNeeds',
        supplies: 'vw2017MapExistingWugSupply',
        population: 'vw2017MapWugPopulation',
        strategies: 'vw2017MapWMSWugSupply'
    };

    PROJECT_TABLES = {
        region: 'vw2017MapWMSProjects',
        county: 'vw2017MapWMSProjectByCounty',
        entity: 'vw2017MapWMSProjectByEntity',
        source: 'vw2017MapWMSProjectBySource',
        wmstype: 'vw2017MapWMSProjectsByWmsType',
        project: 'vw2017MapWMSProjectByWMS', //Not included as project information in project view is pulled from the vwWMSProjectByEntityWUGSplit table
        strategies: 'vw2017MapWMSProjectByEntityWUGSplit',
        wms: 'vw2017MapWMSProjectByWMS'
        //usagetype: vwWMSProjectByWUGType //Not included because results are too large
    };

    #decades = ['2020', '2030', '2040', '2050', '2060', '2070'];
    #usage_types = ['IRRIGATION', 'MUNICIPAL', 'MANUFACTURING', 'STEAM ELECTRIC POWER', 'LIVESTOCK', 'MINING'];
    USAGE_TYPE_DESCRIPTIONS = {
        IRRIGATION:
            'Irrigation water demand includes water used in irrigated field crops, vineyards, orchards, and self-supplied golf courses.',
        MUNICIPAL:
            'Municipal water demand consists of water to be used for residential (single family and multi-family), commercial (including some manufacturing firms that do not use water in their production process), and institutional purposes (establishments dedicated to public service).',
        MANUFACTURING:
            'Manufacturing water demand consists of the future water necessary for large facilities including those that process chemicals, oil and gas, food, paper, and other materials.',
        'STEAM ELECTRIC POWER': 'Steam-electric water demand consists of water used for the purpose of generating power.',
        LIVESTOCK:
            'Livestock water demand includes water used in the production of various types of livestock including cattle (beef and dairy), hogs, poultry, horses, sheep, and goats.',
        MINING: 'Mining water demand consists of water used in the exploration, development, and extraction of oil, gas, coal, aggregates, and other materials.'
    };
    WMS_TYPES = [
        'AQUIFER STORAGE & RECOVERY',
        'CONJUNCTIVE USE',
        'DIRECT POTABLE REUSE',
        'DROUGHT MANAGEMENT',
        'GROUNDWATER DESALINATION',
        'GROUNDWATER WELLS & OTHER',
        'INDIRECT REUSE',
        'IRRIGATION CONSERVATION',
        'MUNICIPAL CONSERVATION',
        'NEW MAJOR RESERVOIR',
        'OTHER CONSERVATION',
        'OTHER DIRECT REUSE',
        'OTHER STRATEGIES',
        'OTHER SURFACE WATER',
        'SEAWATER DESALINATION'
    ];

    #themes = ['demands', 'supplies', 'needs', 'strategies'];

    #theme_titles = {
        demands: 'Demands',
        supplies: 'Existing Supplies',
        needs: 'Needs (Potential Shortages)',
        strategies: 'Strategy Supplies',
        population: 'Population'
    };

    chosenTitles = {
        region: 'Region',
        entity: 'Water User Group',
        usagetype: 'Usage Type',
        source: 'Water Source',
        project: 'Project',
        wms: 'WMS',
        wmstype: 'WMS Type',
        county: 'County'
    };

    wms_info = {
        WMS_TYPES: [
            'AQUIFER STORAGE & RECOVERY',
            'CONJUNCTIVE USE',
            'DIRECT POTABLE REUSE',
            'DROUGHT MANAGEMENT',
            'GROUNDWATER DESALINATION',
            'GROUNDWATER WELLS & OTHER',
            'INDIRECT REUSE',
            'IRRIGATION CONSERVATION',
            'MUNICIPAL CONSERVATION',
            'NEW MAJOR RESERVOIR',
            'OTHER CONSERVATION',
            'OTHER DIRECT REUSE',
            'OTHER STRATEGIES',
            'OTHER SURFACE WATER',
            'SEAWATER DESALINATION'
        ],
        WMS_TYPE_DESCRIPTIONS: {
            'AQUIFER STORAGE & RECOVERY':
                'Aquifer storage and recovery water management strategies inject water, when available, into an aquifer where it is stored for later use.',
            'CONJUNCTIVE USE':
                'Conjunctive use water management strategies combine multiple water sources, usually surface water and groundwater, to optimize the beneficial characteristics of each source, yielding additional firm water supplies.',
            'DIRECT POTABLE REUSE':
                'Direct potable reuse strategies involve taking treated wastewater effluent, further treating it at an advanced water treatment plant, and then either introducing it upfront of the water treatment plant or directly into the potable water distribution system.',
            'DROUGHT MANAGEMENT':
                'Drought management water management strategies reduce water use during times of drought by temporarily restricting certain economic and domestic activities such as car washing and lawn watering.',
            'GROUNDWATER DESALINATION':
                'Groundwater desalination water management strategies involve the process of removing dissolved solids from brackish groundwater, often by forcing the source water through membranes under high pressure.',
            'GROUNDWATER WELLS & OTHER':
                'Groundwater wells & other water management strategies include the development of additional groundwater including single wells or multiple wells, which may be part of the development of new well fields or existing well fields.',
            'INDIRECT REUSE':
                'Indirect reuse water management strategies generally involve discharging wastewater into a natural water body and diverting that water for subsequent use.',
            'IRRIGATION CONSERVATION':
                'Irrigation conservation water management strategies include a variety of activities that either reduce everyday water consumption or increase water use efficiency, allowing more to be done with the same amount of water. Irrigation conservation activities include water savings associated with changes to irrigation methods and equipment, for example, conversion to Low Energy Precision Application systems and other irrigation best management practices.',
            'MUNICIPAL CONSERVATION':
                'Municipal conservation water management strategies include a variety of activities that either reduce everyday water consumption or increase water use efficiency, allowing more to be done with the same amount of water. Examples of municipal conservation includes activities such as low flow plumbing fixtures, water conservation pricing structure, water system audits, or landscape irrigation restrictions.',
            'NEW MAJOR RESERVOIR':
                'New major reservoir water management strategies involve the construction of a new major reservoir. Major reservoirs are defined as reservoirs having at least 5,000 acre-feet of storage capacity at the normal operating level.',
            'OTHER CONSERVATION':
                'Other conservation water management strategies include a variety of activities that either reduce everyday water consumption or increase water use efficiency of water use categories other than municipal and irrigation, allowing more to be done with the same amount of water. Steam-electric, manufacturing, and mining conservation activities are based on best management practices, which may include evaluating cooling and process water practices, water audits, or submetering.',
            'OTHER DIRECT REUSE':
                'Other direct reuse water management strategies generally convey treated wastewater directly from a treatment plant to non-potable uses such as landscaping or industrial processes.',
            'OTHER STRATEGIES':
                'Other water management strategies individually, provide less than 0.5 percent of the total recommended strategy supplies in 2070. They include surface water desalination, weather modification, brush control, and rainwater harvesting.',
            'OTHER SURFACE WATER':
                'Other surface water management strategies includes minor reservoirs (less than 5,000 acre-feet of storage) and subordination as well as a wide variety of other strategies that convey, treat, reassign, or otherwise make accessible additional surface water supplies to users with or without additional infrastructure.',
            'SEAWATER DESALINATION':
                'Seawater desalination water management strategies involve the process of removing dissolved solids from seawater, often by forcing the source water through membranes under high pressure.'
        }
    };

    #year = 2017;
    #regions = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P'];
    #countyNames = [
        'Anderson',
        'Andrews',
        'Angelina',
        'Aransas',
        'Archer',
        'Armstrong',
        'Atascosa',
        'Austin',
        'Bailey',
        'Bandera',
        'Bastrop',
        'Baylor',
        'Bee',
        'Bell',
        'Bexar',
        'Blanco',
        'Borden',
        'Bosque',
        'Bowie',
        'Brazoria',
        'Brazos',
        'Brewster',
        'Briscoe',
        'Brooks',
        'Brown',
        'Burleson',
        'Burnet',
        'Caldwell',
        'Calhoun',
        'Callahan',
        'Cameron',
        'Camp',
        'Carson',
        'Cass',
        'Castro',
        'Chambers',
        'Cherokee',
        'Childress',
        'Clay',
        'Cochran',
        'Coke',
        'Coleman',
        'Collin',
        'Collingsworth',
        'Colorado',
        'Comal',
        'Comanche',
        'Concho',
        'Cooke',
        'Coryell',
        'Cottle',
        'Crane',
        'Crockett',
        'Crosby',
        'Culberson',
        'Dallam',
        'Dallas',
        'Dawson',
        'Deaf Smith',
        'Delta',
        'Denton',
        'DeWitt',
        'Dickens',
        'Dimmit',
        'Donley',
        'Duval',
        'Eastland',
        'Ector',
        'Edwards',
        'Ellis',
        'El Paso',
        'Erath',
        'Falls',
        'Fannin',
        'Fayette',
        'Fisher',
        'Floyd',
        'Foard',
        'Fort Bend',
        'Franklin',
        'Freestone',
        'Frio',
        'Gaines',
        'Galveston',
        'Garza',
        'Gillespie',
        'Glasscock',
        'Goliad',
        'Gonzales',
        'Gray',
        'Grayson',
        'Gregg',
        'Grimes',
        'Guadalupe',
        'Hale',
        'Hall',
        'Hamilton',
        'Hansford',
        'Hardeman',
        'Hardin',
        'Harris',
        'Harrison',
        'Hartley',
        'Haskell',
        'Hays',
        'Hemphill',
        'Henderson',
        'Hidalgo',
        'Hill',
        'Hockley',
        'Hood',
        'Hopkins',
        'Houston',
        'Howard',
        'Hudspeth',
        'Hunt',
        'Hutchinson',
        'Irion',
        'Jack',
        'Jackson',
        'Jasper',
        'Jeff Davis',
        'Jefferson',
        'Jim Hogg',
        'Jim Wells',
        'Johnson',
        'Jones',
        'Karnes',
        'Kaufman',
        'Kendall',
        'Kenedy',
        'Kent',
        'Kerr',
        'Kimble',
        'King',
        'Kinney',
        'Kleberg',
        'Knox',
        'Lamar',
        'Lamb',
        'Lampasas',
        'La Salle',
        'Lavaca',
        'Lee',
        'Leon',
        'Liberty',
        'Limestone',
        'Lipscomb',
        'Live Oak',
        'Llano',
        'Loving',
        'Lubbock',
        'Lynn',
        'Madison',
        'Marion',
        'Martin',
        'Mason',
        'Matagorda',
        'Maverick',
        'McCulloch',
        'McLennan',
        'McMullen',
        'Medina',
        'Menard',
        'Midland',
        'Milam',
        'Mills',
        'Mitchell',
        'Montague',
        'Montgomery',
        'Moore',
        'Morris',
        'Motley',
        'Nacogdoches',
        'Navarro',
        'Newton',
        'Nolan',
        'Nueces',
        'Ochiltree',
        'Oldham',
        'Orange',
        'Palo Pinto',
        'Panola',
        'Parker',
        'Parmer',
        'Pecos',
        'Polk',
        'Potter',
        'Presidio',
        'Rains',
        'Randall',
        'Reagan',
        'Real',
        'Red River',
        'Reeves',
        'Refugio',
        'Roberts',
        'Robertson',
        'Rockwall',
        'Runnels',
        'Rusk',
        'Sabine',
        'San Augustine',
        'San Jacinto',
        'San Patricio',
        'San Saba',
        'Schleicher',
        'Scurry',
        'Shackelford',
        'Shelby',
        'Sherman',
        'Smith',
        'Somervell',
        'Starr',
        'Stephens',
        'Sterling',
        'Stonewall',
        'Sutton',
        'Swisher',
        'Tarrant',
        'Taylor',
        'Terrell',
        'Terry',
        'Throckmorton',
        'Titus',
        'Tom Green',
        'Travis',
        'Trinity',
        'Tyler',
        'Upshur',
        'Upton',
        'Uvalde',
        'Val Verde',
        'Van Zandt',
        'Victoria',
        'Walker',
        'Waller',
        'Ward',
        'Washington',
        'Webb',
        'Wharton',
        'Wheeler',
        'Wichita',
        'Wilbarger',
        'Willacy',
        'Williamson',
        'Wilson',
        'Winkler',
        'Wise',
        'Wood',
        'Yoakum',
        'Young',
        'Zapata',
        'Zavala'
    ];

    page_types = {
        region: 'region',
        county: 'county',
        entity: 'entity',
        usagetype: 'usagetype',
        source: 'source',
        project: 'project',
        wms: 'wms',
        wmstype: 'wmstype'
    };

    sourceNames = [
        {value: 1, label: "ABILENE LAKE/RESERVOIR"},
        {value: 2, label: "ALAN HENRY LAKE/RESERVOIR"},
        {value: 3, label: "ALCOA LAKE/RESERVOIR"},
        {value: 4, label: "ALLENS CREEK LAKE/RESERVOIR"},
        {value: 6, label: "AMISTAD-FALCON LAKE/RESERVOIR SYSTEM"},
        {value: 7, label: "AMON G. CARTER LAKE/RESERVOIR"},
        {value: 884, label: "ANSON NORTH LAKE/RESERVOIR"},
        {value: 9, label: "ATHENS LAKE/RESERVOIR"},
        {value: 820, label: "ATMOSPHERE"},
        {value: 885, label: "AUSTIN CHALK AQUIFER | KINNEY"},
        {value: 886, label: "AUSTIN CHALK AQUIFER | UVALDE"},
        {value: 887, label: "BAIRD LAKE/RESERVOIR"},
        {value: 10, label: "BALLINGER/MOONEN LAKE/RESERVOIR"},
        {value: 11, label: "BALMORHEA LAKE/RESERVOIR"},
        {value: 12, label: "BARDWELL LAKE/RESERVOIR"},
        {value: 888, label: "BAYLOR CREEK RESERVOIR"},
        {value: 14, label: "BELLWOOD LAKE/RESERVOIR"},
        {value: 15, label: "BIG CREEK LAKE/RESERVOIR"},
        {value: 16, label: "BIG SANDY CREEK LAKE/RESERVOIR"},
        {value: 17, label: "BLAINE AQUIFER | CHILDRESS"},
        {value: 18, label: "BLAINE AQUIFER | COLLINGSWORTH"},
        {value: 19, label: "BLAINE AQUIFER | COTTLE"},
        {value: 20, label: "BLAINE AQUIFER | FISHER"},
        {value: 21, label: "BLAINE AQUIFER | FOARD"},
        {value: 22, label: "BLAINE AQUIFER | HALL"},
        {value: 23, label: "BLAINE AQUIFER | HARDEMAN"},
        {value: 24, label: "BLAINE AQUIFER | KING"},
        {value: 25, label: "BLAINE AQUIFER | KNOX"},
        {value: 26, label: "BLAINE AQUIFER | NOLAN"},
        {value: 27, label: "BLAINE AQUIFER | STONEWALL"},
        {value: 28, label: "BLAINE AQUIFER | WHEELER"},
        {value: 29, label: "BLANCO LAKE/RESERVOIR"},
        {value: 30, label: "BLOSSOM AQUIFER | BOWIE"},
        {value: 31, label: "BLOSSOM AQUIFER | LAMAR"},
        {value: 32, label: "BLOSSOM AQUIFER | RED RIVER"},
        {value: 33, label: "BOB SANDLIN LAKE/RESERVOIR"},
        {value: 34, label: "BOERNE LAKE/RESERVOIR"},
        {value: 35, label: "BONE SPRING-VICTORIO PEAK AQUIFER | HUDSPETH"},
        {value: 36, label: "BONHAM LAKE/RESERVOIR"},
        {value: 37, label: "BRADY CREEK LAKE/RESERVOIR"},
        {value: 38, label: "BRANDY BRANCH LAKE/RESERVOIR"},
        {value: 39, label: "BRAZORIA OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 952, label: "BRAZOS INDIRECT REUSE"},
        {value: 40, label: "BRAZOS RIVER ALLUVIUM AQUIFER | AUSTIN"},
        {value: 41, label: "BRAZOS RIVER ALLUVIUM AQUIFER | BOSQUE"},
        {value: 42, label: "BRAZOS RIVER ALLUVIUM AQUIFER | BRAZOS"},
        {value: 43, label: "BRAZOS RIVER ALLUVIUM AQUIFER | BURLESON"},
        {value: 44, label: "BRAZOS RIVER ALLUVIUM AQUIFER | FALLS"},
        {value: 45, label: "BRAZOS RIVER ALLUVIUM AQUIFER | FORT BEND"},
        {value: 46, label: "BRAZOS RIVER ALLUVIUM AQUIFER | GRIMES"},
        {value: 47, label: "BRAZOS RIVER ALLUVIUM AQUIFER | HILL"},
        {value: 48, label: "BRAZOS RIVER ALLUVIUM AQUIFER | MCLENNAN"},
        {value: 49, label: "BRAZOS RIVER ALLUVIUM AQUIFER | MILAM"},
        {value: 50, label: "BRAZOS RIVER ALLUVIUM AQUIFER | ROBERTSON"},
        {value: 51, label: "BRAZOS RIVER ALLUVIUM AQUIFER | WALLER"},
        {value: 52, label: "BRAZOS RIVER ALLUVIUM AQUIFER | WASHINGTON"},
        {value: 53, label: "BRAZOS RIVER AUTHORITY AQUILLA LAKE/RESERVOIR SYSTEM"},
        {value: 54, label: "BRAZOS RIVER AUTHORITY LITTLE RIVER LAKE/RESERVOIR SYSTEM"},
        {value: 55, label: "BRAZOS RIVER AUTHORITY MAIN STEM LAKE/RESERVOIR SYSTEM"},
        {value: 655, label: "BRAZOS RUN-OF-RIVER"},
        {value: 656, label: "BRAZOS-COLORADO RUN-OF-RIVER"},
        {value: 57, label: "BROWNWOOD LAKE/RESERVOIR"},
        {value: 59, label: "BRUSHY CREEK LAKE/RESERVOIR"},
        {value: 60, label: "BRYSON LAKE/RESERVOIR"},
        {value: 889, label: "BUDA LIMESTONE AQUIFER | UVALDE"},
        {value: 62, label: "CALAVERAS LAKE/RESERVOIR"},
        {value: 657, label: "CANADIAN RUN-OF-RIVER"},
        {value: 63, label: "CANEY LAKE/RESERVOIR"},
        {value: 64, label: "CANYON LAKE/RESERVOIR"},
        {value: 65, label: "CAPITAN REEF AQUIFER | BREWSTER"},
        {value: 66, label: "CAPITAN REEF AQUIFER | CULBERSON"},
        {value: 67, label: "CAPITAN REEF AQUIFER | HUDSPETH"},
        {value: 68, label: "CAPITAN REEF AQUIFER | PECOS"},
        {value: 890, label: "CAPITAN REEF AQUIFER | REEVES"},
        {value: 69, label: "CAPITAN REEF AQUIFER | WARD"},
        {value: 70, label: "CAPITAN REEF AQUIFER | WINKLER"},
        {value: 892, label: "CARRIZO-WILCOX AQUIFER ASR | BASTROP\r\n"},
        {value: 1066, label: "CARRIZO-WILCOX AQUIFER ASR | GONZALES\r\n"},
        {value: 893, label: "CARRIZO-WILCOX AQUIFER ASR | UVALDE\r\n"},
        {value: 71, label: "CARRIZO-WILCOX AQUIFER | ANDERSON"},
        {value: 72, label: "CARRIZO-WILCOX AQUIFER | ANGELINA"},
        {value: 73, label: "CARRIZO-WILCOX AQUIFER | ATASCOSA"},
        {value: 74, label: "CARRIZO-WILCOX AQUIFER | BASTROP"},
        {value: 75, label: "CARRIZO-WILCOX AQUIFER | BEE"},
        {value: 76, label: "CARRIZO-WILCOX AQUIFER | BEXAR"},
        {value: 77, label: "CARRIZO-WILCOX AQUIFER | BOWIE"},
        {value: 78, label: "CARRIZO-WILCOX AQUIFER | BRAZOS"},
        {value: 79, label: "CARRIZO-WILCOX AQUIFER | BURLESON"},
        {value: 80, label: "CARRIZO-WILCOX AQUIFER | CALDWELL"},
        {value: 81, label: "CARRIZO-WILCOX AQUIFER | CAMP"},
        {value: 82, label: "CARRIZO-WILCOX AQUIFER | CASS"},
        {value: 83, label: "CARRIZO-WILCOX AQUIFER | CHEROKEE"},
        {value: 84, label: "CARRIZO-WILCOX AQUIFER | DIMMIT"},
        {value: 85, label: "CARRIZO-WILCOX AQUIFER | FALLS"},
        {value: 86, label: "CARRIZO-WILCOX AQUIFER | FAYETTE"},
        {value: 87, label: "CARRIZO-WILCOX AQUIFER | FRANKLIN"},
        {value: 88, label: "CARRIZO-WILCOX AQUIFER | FREESTONE"},
        {value: 89, label: "CARRIZO-WILCOX AQUIFER | FRIO"},
        {value: 90, label: "CARRIZO-WILCOX AQUIFER | GONZALES"},
        {value: 91, label: "CARRIZO-WILCOX AQUIFER | GREGG"},
        {value: 92, label: "CARRIZO-WILCOX AQUIFER | GRIMES"},
        {value: 93, label: "CARRIZO-WILCOX AQUIFER | GUADALUPE"},
        {value: 94, label: "CARRIZO-WILCOX AQUIFER | HARRISON"},
        {value: 95, label: "CARRIZO-WILCOX AQUIFER | HENDERSON"},
        {value: 96, label: "CARRIZO-WILCOX AQUIFER | HOPKINS"},
        {value: 97, label: "CARRIZO-WILCOX AQUIFER | HOUSTON"},
        {value: 99, label: "CARRIZO-WILCOX AQUIFER | KARNES"},
        {value: 100, label: "CARRIZO-WILCOX AQUIFER | LA SALLE"},
        {value: 101, label: "CARRIZO-WILCOX AQUIFER | LEE"},
        {value: 102, label: "CARRIZO-WILCOX AQUIFER | LEON"},
        {value: 103, label: "CARRIZO-WILCOX AQUIFER | LIMESTONE"},
        {value: 104, label: "CARRIZO-WILCOX AQUIFER | LIVE OAK"},
        {value: 105, label: "CARRIZO-WILCOX AQUIFER | MADISON"},
        {value: 106, label: "CARRIZO-WILCOX AQUIFER | MARION"},
        {value: 107, label: "CARRIZO-WILCOX AQUIFER | MAVERICK"},
        {value: 108, label: "CARRIZO-WILCOX AQUIFER | MCMULLEN"},
        {value: 109, label: "CARRIZO-WILCOX AQUIFER | MEDINA"},
        {value: 110, label: "CARRIZO-WILCOX AQUIFER | MILAM"},
        {value: 111, label: "CARRIZO-WILCOX AQUIFER | MORRIS"},
        {value: 112, label: "CARRIZO-WILCOX AQUIFER | NACOGDOCHES"},
        {value: 113, label: "CARRIZO-WILCOX AQUIFER | NAVARRO"},
        {value: 114, label: "CARRIZO-WILCOX AQUIFER | PANOLA"},
        {value: 115, label: "CARRIZO-WILCOX AQUIFER | RAINS"},
        {value: 116, label: "CARRIZO-WILCOX AQUIFER | RED RIVER"},
        {value: 117, label: "CARRIZO-WILCOX AQUIFER | ROBERTSON"},
        {value: 118, label: "CARRIZO-WILCOX AQUIFER | RUSK"},
        {value: 119, label: "CARRIZO-WILCOX AQUIFER | SABINE"},
        {value: 120, label: "CARRIZO-WILCOX AQUIFER | SAN AUGUSTINE"},
        {value: 121, label: "CARRIZO-WILCOX AQUIFER | SHELBY"},
        {value: 122, label: "CARRIZO-WILCOX AQUIFER | SMITH"},
        {value: 123, label: "CARRIZO-WILCOX AQUIFER | TITUS"},
        {value: 124, label: "CARRIZO-WILCOX AQUIFER | TRINITY"},
        {value: 125, label: "CARRIZO-WILCOX AQUIFER | UPSHUR"},
        {value: 126, label: "CARRIZO-WILCOX AQUIFER | UVALDE"},
        {value: 127, label: "CARRIZO-WILCOX AQUIFER | VAN ZANDT"},
        {value: 128, label: "CARRIZO-WILCOX AQUIFER | WALKER"},
        {value: 129, label: "CARRIZO-WILCOX AQUIFER | WEBB"},
        {value: 891, label: "CARRIZO-WILCOX AQUIFER | WILLIAMSON"},
        {value: 130, label: "CARRIZO-WILCOX AQUIFER | WILSON"},
        {value: 131, label: "CARRIZO-WILCOX AQUIFER | WOOD"},
        {value: 132, label: "CARRIZO-WILCOX AQUIFER | ZAVALA"},
        {value: 137, label: "CEDAR RIDGE LAKE/RESERVOIR"},
        {value: 147, label: "CENTER LAKE/RESERVOIR"},
        {value: 148, label: "CHAPMAN/COOPER LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 149, label: "CHAPMAN/COOPER LAKE/RESERVOIR NORTH TEXAS MWD SYSTEM"},
        {value: 150, label: "CHEROKEE LAKE/RESERVOIR"},
        {value: 151, label: "CISCO LAKE/RESERVOIR"},
        {value: 894, label: "CITY OF HAMLIN LAKE/RESERVOIR"},
        {value: 152, label: "CLARK LAKE/RESERVOIR"},
        {value: 895, label: "CLIFTON LAKE/RESERVOIR"},
        {value: 153, label: "CLYDE LAKE/RESERVOIR"},
        {value: 155, label: "COLEMAN LAKE/RESERVOIR"},
        {value: 156, label: "COLETO CREEK LAKE/RESERVOIR"},
        {value: 157, label: "COLORADO CITY-CHAMPION LAKE/RESERVOIR SYSTEM"},
        {value: 381, label: "COLORADO INDIRECT REUSE"},
        {value: 158, label: "COLORADO RIVER MWD LAKE/RESERVOIR SYSTEM"},
        {value: 658, label: "COLORADO RUN-OF-RIVER"},
        {value: 659, label: "COLORADO-LAVACA RUN-OF-RIVER"},
        {value: 159, label: "COLUMBIA LAKE/RESERVOIR"},
        {value: 160, label: "CONROE LAKE/RESERVOIR"},
        {value: 163, label: "CORPUS CHRISTI-CHOKE CANYON LAKE/RESERVOIR SYSTEM"},
        {value: 164, label: "CORYELL COUNTY LAKE/RESERVOIR"},
        {value: 896, label: "CRAWFORD LAKE/RESERVOIR"},
        {value: 897, label: "CRMWD DIVERTED WATER SYSTEM"},
        {value: 165, label: "CROOK LAKE/RESERVOIR"},
        {value: 660, label: "CYPRESS RUN-OF-RIVER"},
        {value: 166, label: "CYPRESS SPRINGS LAKE/RESERVOIR"},
        {value: 167, label: "DANIEL LAKE/RESERVOIR"},
        {value: 168, label: "DANSBY POWER PLANT/BRYAN UTILITIES LAKE/RESERVOIR"},
        {value: 898, label: "DIMPLE LAKE/RESERVOIR"},
        {value: 169, label: "DIRECT REUSE"},
        {value: 170, label: "DOCKUM AQUIFER | ANDREWS"},
        {value: 171, label: "DOCKUM AQUIFER | ARMSTRONG"},
        {value: 899, label: "DOCKUM AQUIFER | BAILEY"},
        {value: 172, label: "DOCKUM AQUIFER | BORDEN"},
        {value: 173, label: "DOCKUM AQUIFER | BRISCOE"},
        {value: 174, label: "DOCKUM AQUIFER | CARSON"},
        {value: 900, label: "DOCKUM AQUIFER | CASTRO"},
        {value: 901, label: "DOCKUM AQUIFER | COCHRAN"},
        {value: 175, label: "DOCKUM AQUIFER | COKE"},
        {value: 176, label: "DOCKUM AQUIFER | CRANE"},
        {value: 902, label: "DOCKUM AQUIFER | CROCKETT"},
        {value: 903, label: "DOCKUM AQUIFER | CROSBY"},
        {value: 177, label: "DOCKUM AQUIFER | DALLAM"},
        {value: 904, label: "DOCKUM AQUIFER | DAWSON"},
        {value: 178, label: "DOCKUM AQUIFER | DEAF SMITH"},
        {value: 905, label: "DOCKUM AQUIFER | DICKENS"},
        {value: 179, label: "DOCKUM AQUIFER | ECTOR"},
        {value: 180, label: "DOCKUM AQUIFER | FISHER"},
        {value: 906, label: "DOCKUM AQUIFER | FLOYD"},
        {value: 907, label: "DOCKUM AQUIFER | GAINES"},
        {value: 181, label: "DOCKUM AQUIFER | GARZA"},
        {value: 182, label: "DOCKUM AQUIFER | GLASSCOCK"},
        {value: 908, label: "DOCKUM AQUIFER | HALE"},
        {value: 183, label: "DOCKUM AQUIFER | HARTLEY"},
        {value: 909, label: "DOCKUM AQUIFER | HOCKLEY"},
        {value: 184, label: "DOCKUM AQUIFER | HOWARD"},
        {value: 910, label: "DOCKUM AQUIFER | IRION"},
        {value: 185, label: "DOCKUM AQUIFER | KENT"},
        {value: 911, label: "DOCKUM AQUIFER | LAMB\r\n"},
        {value: 186, label: "DOCKUM AQUIFER | LOVING"},
        {value: 912, label: "DOCKUM AQUIFER | LUBBOCK"},
        {value: 913, label: "DOCKUM AQUIFER | LYNN"},
        {value: 914, label: "DOCKUM AQUIFER | MARTIN"},
        {value: 187, label: "DOCKUM AQUIFER | MIDLAND"},
        {value: 188, label: "DOCKUM AQUIFER | MITCHELL"},
        {value: 189, label: "DOCKUM AQUIFER | MOORE"},
        {value: 915, label: "DOCKUM AQUIFER | MOTLEY"},
        {value: 190, label: "DOCKUM AQUIFER | NOLAN"},
        {value: 191, label: "DOCKUM AQUIFER | OLDHAM"},
        {value: 916, label: "DOCKUM AQUIFER | PARMER"},
        {value: 192, label: "DOCKUM AQUIFER | PECOS"},
        {value: 193, label: "DOCKUM AQUIFER | POTTER"},
        {value: 194, label: "DOCKUM AQUIFER | RANDALL"},
        {value: 195, label: "DOCKUM AQUIFER | REAGAN"},
        {value: 196, label: "DOCKUM AQUIFER | REEVES"},
        {value: 197, label: "DOCKUM AQUIFER | SCURRY"},
        {value: 198, label: "DOCKUM AQUIFER | SHERMAN"},
        {value: 917, label: "DOCKUM AQUIFER | STERLING"},
        {value: 199, label: "DOCKUM AQUIFER | SWISHER"},
        {value: 200, label: "DOCKUM AQUIFER | TOM GREEN"},
        {value: 201, label: "DOCKUM AQUIFER | UPTON"},
        {value: 202, label: "DOCKUM AQUIFER | WARD"},
        {value: 203, label: "DOCKUM AQUIFER | WINKLER"},
        {value: 876, label: "DOW OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 918, label: "DWU ELLIS COUNTY OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 919, label: "EASTLAND LAKE/RESERVOIR"},
        {value: 206, label: "EDGEWOOD CITY LAKE/RESERVOIR"},
        {value: 920, label: "EDWARDS AQUIFER ASR | TRAVIS\r\n"},
        {value: 921, label: "EDWARDS AQUIFER ASR | WILLIAMSON\r\n"},
        {value: 207, label: "EDWARDS-BFZ AQUIFER | ATASCOSA"},
        {value: 208, label: "EDWARDS-BFZ AQUIFER | BELL"},
        {value: 209, label: "EDWARDS-BFZ AQUIFER | BEXAR"},
        {value: 923, label: "EDWARDS-BFZ AQUIFER | CALDWELL"},
        {value: 210, label: "EDWARDS-BFZ AQUIFER | COMAL"},
        {value: 924, label: "EDWARDS-BFZ AQUIFER | FRIO"},
        {value: 211, label: "EDWARDS-BFZ AQUIFER | GUADALUPE"},
        {value: 212, label: "EDWARDS-BFZ AQUIFER | HAYS"},
        {value: 213, label: "EDWARDS-BFZ AQUIFER | KINNEY"},
        {value: 214, label: "EDWARDS-BFZ AQUIFER | MEDINA"},
        {value: 215, label: "EDWARDS-BFZ AQUIFER | TRAVIS"},
        {value: 216, label: "EDWARDS-BFZ AQUIFER | UVALDE"},
        {value: 217, label: "EDWARDS-BFZ AQUIFER | WILLIAMSON"},
        {value: 925, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | BAILEY"},
        {value: 926, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | BORDEN"},
        {value: 927, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | COCHRAN"},
        {value: 928, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | DAWSON"},
        {value: 929, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | FLOYD"},
        {value: 930, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | GAINES"},
        {value: 931, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | GARZA"},
        {value: 932, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | HALE"},
        {value: 933, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | HOCKLEY"},
        {value: 934, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | LAMB"},
        {value: 218, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | LUBBOCK"},
        {value: 219, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | LYNN"},
        {value: 935, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | TERRY"},
        {value: 936, label: "EDWARDS-TRINITY-HIGH PLAINS AQUIFER | YOAKUM"},
        {value: 220, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | ANDREWS"},
        {value: 221, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | BANDERA"},
        {value: 222, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | BLANCO"},
        {value: 223, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | BREWSTER"},
        {value: 224, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | COKE"},
        {value: 225, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | CONCHO"},
        {value: 226, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | CRANE"},
        {value: 227, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | CROCKETT"},
        {value: 228, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | CULBERSON"},
        {value: 229, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | ECTOR"},
        {value: 230, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | EDWARDS"},
        {value: 231, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | GILLESPIE"},
        {value: 232, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | GLASSCOCK"},
        {value: 233, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | HOWARD"},
        {value: 234, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | IRION"},
        {value: 235, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | JEFF DAVIS"},
        {value: 236, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | KENDALL"},
        {value: 237, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | KERR"},
        {value: 238, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | KIMBLE"},
        {value: 239, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | KINNEY"},
        {value: 240, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | MARTIN"},
        {value: 241, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | MASON"},
        {value: 242, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | MCCULLOCH"},
        {value: 243, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | MENARD"},
        {value: 244, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | MIDLAND"},
        {value: 245, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | NOLAN"},
        {value: 246, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | PECOS"},
        {value: 247, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | REAGAN"},
        {value: 248, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | REAL"},
        {value: 249, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | REEVES"},
        {value: 250, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | SCHLEICHER"},
        {value: 251, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | STERLING"},
        {value: 252, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | SUTTON"},
        {value: 253, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | TAYLOR"},
        {value: 254, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | TERRELL"},
        {value: 255, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | TOM GREEN"},
        {value: 256, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | UPTON"},
        {value: 257, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | UVALDE"},
        {value: 258, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | VAL VERDE"},
        {value: 259, label: "EDWARDS-TRINITY-PLATEAU AQUIFER | WINKLER"},
        {value: 260, label: "ELECTRA CITY LAKE/RESERVOIR"},
        {value: 937, label: "ELLENBURGER AQUIFER | KERR"},
        {value: 261, label: "ELLENBURGER-SAN SABA AQUIFER | BLANCO"},
        {value: 938, label: "ELLENBURGER-SAN SABA AQUIFER | BROWN"},
        {value: 262, label: "ELLENBURGER-SAN SABA AQUIFER | BURNET"},
        {value: 939, label: "ELLENBURGER-SAN SABA AQUIFER | CONCHO"},
        {value: 263, label: "ELLENBURGER-SAN SABA AQUIFER | GILLESPIE"},
        {value: 264, label: "ELLENBURGER-SAN SABA AQUIFER | KIMBLE"},
        {value: 265, label: "ELLENBURGER-SAN SABA AQUIFER | LAMPASAS"},
        {value: 266, label: "ELLENBURGER-SAN SABA AQUIFER | LLANO"},
        {value: 267, label: "ELLENBURGER-SAN SABA AQUIFER | MASON"},
        {value: 268, label: "ELLENBURGER-SAN SABA AQUIFER | MCCULLOCH"},
        {value: 269, label: "ELLENBURGER-SAN SABA AQUIFER | MENARD"},
        {value: 270, label: "ELLENBURGER-SAN SABA AQUIFER | MILLS"},
        {value: 271, label: "ELLENBURGER-SAN SABA AQUIFER | SAN SABA"},
        {value: 272, label: "ELLIOT CREEK LAKE/RESERVOIR"},
        {value: 273, label: "ELLISON CREEK LAKE/RESERVOIR"},
        {value: 274, label: "EV SPENCE LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 275, label: "FAIRFIELD LAKE/RESERVOIR"},
        {value: 276, label: "FARMERS CREEK/NOCONA LAKE/RESERVOIR"},
        {value: 278, label: "FOREST GROVE LAKE/RESERVOIR"},
        {value: 279, label: "FORK LAKE/RESERVOIR"},
        {value: 280, label: "FORT BEND OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 281, label: "FORT PHANTOM HILL LAKE/RESERVOIR"},
        {value: 879, label: "GBRA LOWER BASIN OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 282, label: "GCWA OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 285, label: "GIBBONS CREEK LAKE/RESERVOIR"},
        {value: 287, label: "GILMER LAKE/RESERVOIR"},
        {value: 288, label: "GLADEWATER LAKE/RESERVOIR"},
        {value: 289, label: "GOLDTHWAITE LAKE/RESERVOIR"},
        {value: 940, label: "GORDON LAKE/RESERVOIR"},
        {value: 290, label: "GRAHAM/EDDLEMAN LAKE/RESERVOIR"},
        {value: 292, label: "GRAPEVINE LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 293, label: "GREENBELT LAKE/RESERVOIR"},
        {value: 294, label: "GREENVILLE CITY LAKE/RESERVOIR"},
        {value: 295, label: "GROESBECK OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 941, label: "GUADALUPE RIVER ALLUVIUM AQUIFER | CALDWELL"},
        {value: 942, label: "GUADALUPE RIVER OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 661, label: "GUADALUPE RUN-OF-RIVER"},
        {value: 943, label: "GULF COAST AQUIFER ASR | JACKSON\r\n"},
        {value: 944, label: "GULF COAST AQUIFER ASR | VICTORIA\r\n"},
        {value: 296, label: "GULF COAST AQUIFER | ARANSAS"},
        {value: 297, label: "GULF COAST AQUIFER | AUSTIN"},
        {value: 298, label: "GULF COAST AQUIFER | BEE"},
        {value: 299, label: "GULF COAST AQUIFER | BRAZORIA"},
        {value: 300, label: "GULF COAST AQUIFER | BRAZOS"},
        {value: 301, label: "GULF COAST AQUIFER | BROOKS"},
        {value: 302, label: "GULF COAST AQUIFER | CALHOUN"},
        {value: 303, label: "GULF COAST AQUIFER | CAMERON"},
        {value: 304, label: "GULF COAST AQUIFER | CHAMBERS"},
        {value: 305, label: "GULF COAST AQUIFER | COLORADO"},
        {value: 306, label: "GULF COAST AQUIFER | DEWITT"},
        {value: 307, label: "GULF COAST AQUIFER | DUVAL"},
        {value: 308, label: "GULF COAST AQUIFER | FAYETTE"},
        {value: 309, label: "GULF COAST AQUIFER | FORT BEND"},
        {value: 310, label: "GULF COAST AQUIFER | GALVESTON"},
        {value: 311, label: "GULF COAST AQUIFER | GOLIAD"},
        {value: 312, label: "GULF COAST AQUIFER | GONZALES"},
        {value: 313, label: "GULF COAST AQUIFER | GRIMES"},
        {value: 314, label: "GULF COAST AQUIFER | HARDIN"},
        {value: 315, label: "GULF COAST AQUIFER | HARRIS"},
        {value: 316, label: "GULF COAST AQUIFER | HIDALGO"},
        {value: 317, label: "GULF COAST AQUIFER | JACKSON"},
        {value: 318, label: "GULF COAST AQUIFER | JASPER"},
        {value: 319, label: "GULF COAST AQUIFER | JEFFERSON"},
        {value: 320, label: "GULF COAST AQUIFER | JIM HOGG"},
        {value: 321, label: "GULF COAST AQUIFER | JIM WELLS"},
        {value: 322, label: "GULF COAST AQUIFER | KARNES"},
        {value: 323, label: "GULF COAST AQUIFER | KENEDY"},
        {value: 324, label: "GULF COAST AQUIFER | KLEBERG"},
        {value: 325, label: "GULF COAST AQUIFER | LAVACA"},
        {value: 326, label: "GULF COAST AQUIFER | LIBERTY"},
        {value: 327, label: "GULF COAST AQUIFER | LIVE OAK"},
        {value: 328, label: "GULF COAST AQUIFER | MATAGORDA"},
        {value: 329, label: "GULF COAST AQUIFER | MCMULLEN"},
        {value: 330, label: "GULF COAST AQUIFER | MONTGOMERY"},
        {value: 331, label: "GULF COAST AQUIFER | NEWTON"},
        {value: 332, label: "GULF COAST AQUIFER | NUECES"},
        {value: 333, label: "GULF COAST AQUIFER | ORANGE"},
        {value: 334, label: "GULF COAST AQUIFER | POLK"},
        {value: 335, label: "GULF COAST AQUIFER | REFUGIO"},
        {value: 336, label: "GULF COAST AQUIFER | SABINE"},
        {value: 337, label: "GULF COAST AQUIFER | SAN JACINTO"},
        {value: 338, label: "GULF COAST AQUIFER | SAN PATRICIO"},
        {value: 339, label: "GULF COAST AQUIFER | STARR"},
        {value: 340, label: "GULF COAST AQUIFER | TRINITY"},
        {value: 341, label: "GULF COAST AQUIFER | TYLER"},
        {value: 342, label: "GULF COAST AQUIFER | VICTORIA"},
        {value: 343, label: "GULF COAST AQUIFER | WALKER"},
        {value: 344, label: "GULF COAST AQUIFER | WALLER"},
        {value: 345, label: "GULF COAST AQUIFER | WASHINGTON"},
        {value: 346, label: "GULF COAST AQUIFER | WEBB"},
        {value: 347, label: "GULF COAST AQUIFER | WHARTON"},
        {value: 348, label: "GULF COAST AQUIFER | WILLACY"},
        {value: 349, label: "GULF COAST AQUIFER | ZAPATA"},
        {value: 355, label: "GULF OF MEXICO"},
        {value: 356, label: "HALBERT LAKE/RESERVOIR"},
        {value: 358, label: "HICKORY AQUIFER | BLANCO"},
        {value: 945, label: "HICKORY AQUIFER | BROWN"},
        {value: 359, label: "HICKORY AQUIFER | BURNET"},
        {value: 946, label: "HICKORY AQUIFER | COLEMAN"},
        {value: 360, label: "HICKORY AQUIFER | CONCHO"},
        {value: 361, label: "HICKORY AQUIFER | GILLESPIE"},
        {value: 947, label: "HICKORY AQUIFER | KIMBLE"},
        {value: 948, label: "HICKORY AQUIFER | LAMPASAS"},
        {value: 362, label: "HICKORY AQUIFER | LLANO"},
        {value: 363, label: "HICKORY AQUIFER | MASON"},
        {value: 364, label: "HICKORY AQUIFER | MCCULLOCH"},
        {value: 365, label: "HICKORY AQUIFER | MENARD"},
        {value: 366, label: "HICKORY AQUIFER | MILLS"},
        {value: 367, label: "HICKORY AQUIFER | SAN SABA"},
        {value: 949, label: "HICKORY AQUIFER | TRAVIS"},
        {value: 950, label: "HICKORY AQUIFER | WILLIAMSON"},
        {value: 368, label: "HIGHLAND LAKES LAKE/RESERVOIR"},
        {value: 370, label: "HORDS CREEK LAKE/RESERVOIR"},
        {value: 371, label: "HOUSTON COUNTY LAKE/RESERVOIR"},
        {value: 372, label: "HOUSTON LAKE/RESERVOIR"},
        {value: 373, label: "HUBBARD CREEK LAKE/RESERVOIR"},
        {value: 374, label: "HUBERT H MOSS LAKE/RESERVOIR"},
        {value: 951, label: "HUECO-MESILLA BOLSON AQUIFER ASR | EL PASO\r\n"},
        {value: 375, label: "HUECO-MESILLA BOLSON AQUIFER | EL PASO"},
        {value: 376, label: "HUECO-MESILLA BOLSON AQUIFER | HUDSPETH"},
        {value: 377, label: "IGNEOUS AQUIFER | BREWSTER"},
        {value: 378, label: "IGNEOUS AQUIFER | CULBERSON"},
        {value: 379, label: "IGNEOUS AQUIFER | JEFF DAVIS"},
        {value: 380, label: "IGNEOUS AQUIFER | PRESIDIO"},
        {value: 391, label: "JACKSONVILLE LAKE/RESERVOIR"},
        {value: 392, label: "JOE POOL LAKE/RESERVOIR"},
        {value: 393, label: "JOHNSON CREEK LAKE/RESERVOIR"},
        {value: 394, label: "KEMP-DIVERSION LAKE/RESERVOIR SYSTEM"},
        {value: 396, label: "KIRBY LAKE/RESERVOIR"},
        {value: 397, label: "KURTH LAKE/RESERVOIR"},
        {value: 398, label: "LAKE 7 (JIM BERTRAM) LAKE/RESERVOIR SYSTEM"},
        {value: 399, label: "LAKE CREEK LAKE/RESERVOIR"},
        {value: 954, label: "LAKE DAVIS LAKE/RESERVOIR"},
        {value: 955, label: "LAKE LONG/RESERVOIR"},
        {value: 400, label: "LAKE NACONICHE LAKE/RESERVOIR"},
        {value: 401, label: "LANGFORD LAKE/RESERVOIR"},
        {value: 402, label: "LAVACA RIVER OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 662, label: "LAVACA RUN-OF-RIVER"},
        {value: 403, label: "LAVON LAKE/RESERVOIR NORTH TEXAS MWD SYSTEM"},
        {value: 956, label: "LCRA NEW OFF-CHANNEL RESERVOIR (2030 DECADE)"},
        {value: 957, label: "LCRA NEW OFF-CHANNEL RESERVOIRS (2020 DECADE)"},
        {value: 404, label: "LEON LAKE/RESERVOIR"},
        {value: 958, label: "LEONA GRAVEL AQUIFER | MEDINA\r\n"},
        {value: 959, label: "LEONA GRAVEL AQUIFER | UVALDE\r\n"},
        {value: 405, label: "LEWISVILLE LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 406, label: "LIPAN AQUIFER | CONCHO"},
        {value: 960, label: "LIPAN AQUIFER | GLASSCOCK"},
        {value: 961, label: "LIPAN AQUIFER | IRION"},
        {value: 407, label: "LIPAN AQUIFER | RUNNELS"},
        {value: 962, label: "LIPAN AQUIFER | STERLING"},
        {value: 408, label: "LIPAN AQUIFER | TOM GREEN"},
        {value: 409, label: "LITTLE RIVER OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 830, label: "LITTLE WICHITA RIVER LAKE/RESERVOIR SYSTEM"},
        {value: 410, label: "LIVINGSTON-WALLISVILLE LAKE/RESERVOIR SYSTEM"},
        {value: 411, label: "LLANO LAKE/RESERVOIR"},
        {value: 412, label: "LOCAL SURFACE WATER SUPPLY"},
        {value: 413, label: "LOMA LAKE/RESERVOIR"},
        {value: 414, label: "LOST CREEK-JACKSBORO LAKE/RESERVOIR SYSTEM"},
        {value: 415, label: "LOWER BOIS D ARC LAKE/RESERVOIR"},
        {value: 963, label: "LYTLE LAKE/RESERVOIR"},
        {value: 416, label: "MACKENZIE LAKE/RESERVOIR"},
        {value: 417, label: "MARATHON AQUIFER | BREWSTER"},
        {value: 418, label: "MARBLE FALLS AQUIFER | BLANCO"},
        {value: 419, label: "MARBLE FALLS AQUIFER | BURNET"},
        {value: 964, label: "MARBLE FALLS AQUIFER | KIMBLE"},
        {value: 420, label: "MARBLE FALLS AQUIFER | LAMPASAS"},
        {value: 421, label: "MARBLE FALLS AQUIFER | MASON"},
        {value: 422, label: "MARBLE FALLS AQUIFER | MCCULLOCH"},
        {value: 423, label: "MARBLE FALLS AQUIFER | SAN SABA"},
        {value: 424, label: "MARTIN LAKE/RESERVOIR"},
        {value: 425, label: "MARVIN NICHOLS LAKE/RESERVOIR"},
        {value: 965, label: "MCCARTY LAKE/RESERVOIR"},
        {value: 426, label: "MEDINA LAKE/RESERVOIR"},
        {value: 427, label: "MEREDITH LAKE/RESERVOIR"},
        {value: 966, label: "MERIDIAN OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 428, label: "MEXIA LAKE/RESERVOIR"},
        {value: 429, label: "MILL CREEK LAKE/RESERVOIR"},
        {value: 430, label: "MILLERS CREEK LAKE/RESERVOIR"},
        {value: 432, label: "MINERAL WELLS LAKE/RESERVOIR"},
        {value: 433, label: "MONTICELLO LAKE/RESERVOIR"},
        {value: 967, label: "MORAN LAKE/RESERVOIR"},
        {value: 434, label: "MOUNTAIN CREEK LAKE/RESERVOIR (COLORADO BASIN)"},
        {value: 435, label: "MOUNTAIN CREEK LAKE/RESERVOIR (TRINITY BASIN)"},
        {value: 436, label: "MUENSTER LAKE/RESERVOIR"},
        {value: 437, label: "MURVAUL LAKE/RESERVOIR"},
        {value: 438, label: "NACATOCH AQUIFER | BOWIE"},
        {value: 439, label: "NACATOCH AQUIFER | DELTA"},
        {value: 968, label: "NACATOCH AQUIFER | ELLIS"},
        {value: 440, label: "NACATOCH AQUIFER | FRANKLIN"},
        {value: 441, label: "NACATOCH AQUIFER | HENDERSON"},
        {value: 442, label: "NACATOCH AQUIFER | HOPKINS"},
        {value: 443, label: "NACATOCH AQUIFER | HUNT"},
        {value: 444, label: "NACATOCH AQUIFER | KAUFMAN"},
        {value: 445, label: "NACATOCH AQUIFER | LAMAR"},
        {value: 446, label: "NACATOCH AQUIFER | NAVARRO"},
        {value: 447, label: "NACATOCH AQUIFER | RAINS"},
        {value: 448, label: "NACATOCH AQUIFER | RED RIVER"},
        {value: 449, label: "NACATOCH AQUIFER | ROCKWALL"},
        {value: 450, label: "NACATOCH AQUIFER | TITUS"},
        {value: 451, label: "NACOGDOCHES LAKE/RESERVOIR"},
        {value: 453, label: "NAVARRO MILLS LAKE/RESERVOIR"},
        {value: 969, label: "NAVASOTA RIVER ALLUVIUM AQUIFER | GRIMES\r\n"},
        {value: 382, label: "NECHES INDIRECT REUSE"},
        {value: 663, label: "NECHES RUN-OF-RIVER"},
        {value: 383, label: "NECHES-TRINITY INDIRECT REUSE"},
        {value: 664, label: "NECHES-TRINITY RUN-OF-RIVER"},
        {value: 454, label: "NORTH FORK BUFFALO CREEK LAKE/RESERVOIR"},
        {value: 970, label: "NUECES RIVER ALLUVIUM AQUIFER | EDWARDS"},
        {value: 971, label: "NUECES RIVER ALLUVIUM AQUIFER | REAL"},
        {value: 665, label: "NUECES RUN-OF-RIVER"},
        {value: 1064, label: "NUECES-RIO GRANDE INDIRECT REUSE"},
        {value: 666, label: "NUECES-RIO GRANDE RUN-OF-RIVER"},
        {value: 457, label: "O' THE PINES LAKE/RESERVOIR"},
        {value: 458, label: "OAK CREEK LAKE/RESERVOIR"},
        {value: 972, label: "OGALLALA AQUIFER ASR | CARSON"},
        {value: 973, label: "OGALLALA AQUIFER ASR | DAWSON"},
        {value: 974, label: "OGALLALA AQUIFER ASR | HALE"},
        {value: 975, label: "OGALLALA AQUIFER ASR | HOCKLEY"},
        {value: 976, label: "OGALLALA AQUIFER ASR | HUTCHINSON"},
        {value: 977, label: "OGALLALA AQUIFER ASR | LUBBOCK"},
        {value: 978, label: "OGALLALA AQUIFER ASR | LYNN"},
        {value: 979, label: "OGALLALA AQUIFER ASR | TERRY"},
        {value: 460, label: "OGALLALA AQUIFER | ANDREWS"},
        {value: 461, label: "OGALLALA AQUIFER | ARMSTRONG"},
        {value: 462, label: "OGALLALA AQUIFER | BAILEY"},
        {value: 463, label: "OGALLALA AQUIFER | BORDEN"},
        {value: 464, label: "OGALLALA AQUIFER | BRISCOE"},
        {value: 465, label: "OGALLALA AQUIFER | CARSON"},
        {value: 466, label: "OGALLALA AQUIFER | CASTRO"},
        {value: 467, label: "OGALLALA AQUIFER | COCHRAN"},
        {value: 468, label: "OGALLALA AQUIFER | COLLINGSWORTH"},
        {value: 469, label: "OGALLALA AQUIFER | CROSBY"},
        {value: 470, label: "OGALLALA AQUIFER | DALLAM"},
        {value: 471, label: "OGALLALA AQUIFER | DAWSON"},
        {value: 472, label: "OGALLALA AQUIFER | DEAF SMITH"},
        {value: 473, label: "OGALLALA AQUIFER | DICKENS"},
        {value: 474, label: "OGALLALA AQUIFER | DONLEY"},
        {value: 475, label: "OGALLALA AQUIFER | ECTOR"},
        {value: 476, label: "OGALLALA AQUIFER | FLOYD"},
        {value: 477, label: "OGALLALA AQUIFER | GAINES"},
        {value: 478, label: "OGALLALA AQUIFER | GARZA"},
        {value: 479, label: "OGALLALA AQUIFER | GLASSCOCK"},
        {value: 480, label: "OGALLALA AQUIFER | GRAY"},
        {value: 481, label: "OGALLALA AQUIFER | HALE"},
        {value: 482, label: "OGALLALA AQUIFER | HANSFORD"},
        {value: 483, label: "OGALLALA AQUIFER | HARTLEY"},
        {value: 484, label: "OGALLALA AQUIFER | HEMPHILL"},
        {value: 485, label: "OGALLALA AQUIFER | HOCKLEY"},
        {value: 486, label: "OGALLALA AQUIFER | HOWARD"},
        {value: 487, label: "OGALLALA AQUIFER | HUTCHINSON"},
        {value: 488, label: "OGALLALA AQUIFER | LAMB"},
        {value: 489, label: "OGALLALA AQUIFER | LIPSCOMB"},
        {value: 490, label: "OGALLALA AQUIFER | LUBBOCK"},
        {value: 491, label: "OGALLALA AQUIFER | LYNN"},
        {value: 492, label: "OGALLALA AQUIFER | MARTIN"},
        {value: 493, label: "OGALLALA AQUIFER | MIDLAND"},
        {value: 494, label: "OGALLALA AQUIFER | MOORE"},
        {value: 495, label: "OGALLALA AQUIFER | MOTLEY"},
        {value: 496, label: "OGALLALA AQUIFER | OCHILTREE"},
        {value: 497, label: "OGALLALA AQUIFER | OLDHAM"},
        {value: 498, label: "OGALLALA AQUIFER | PARMER"},
        {value: 499, label: "OGALLALA AQUIFER | POTTER"},
        {value: 500, label: "OGALLALA AQUIFER | RANDALL"},
        {value: 501, label: "OGALLALA AQUIFER | ROBERTS"},
        {value: 502, label: "OGALLALA AQUIFER | SHERMAN"},
        {value: 503, label: "OGALLALA AQUIFER | SWISHER"},
        {value: 504, label: "OGALLALA AQUIFER | TERRY"},
        {value: 505, label: "OGALLALA AQUIFER | WHEELER"},
        {value: 506, label: "OGALLALA AQUIFER | YOAKUM"},
        {value: 980, label: "OGALLALA-RITA BLANCA AQUIFER | DALLAM"},
        {value: 981, label: "OGALLALA-RITA BLANCA AQUIFER | HARTLEY"},
        {value: 507, label: "OH IVIE LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 509, label: "OLNEY-COOPER LAKE/RESERVOIR SYSTEM"},
        {value: 510, label: "OTHER AQUIFER | ANDERSON"},
        {value: 511, label: "OTHER AQUIFER | ANGELINA"},
        {value: 512, label: "OTHER AQUIFER | ARCHER"},
        {value: 513, label: "OTHER AQUIFER | ARMSTRONG"},
        {value: 514, label: "OTHER AQUIFER | BASTROP"},
        {value: 983, label: "OTHER AQUIFER | BAYLOR"},
        {value: 515, label: "OTHER AQUIFER | BORDEN\r\n"},
        {value: 518, label: "OTHER AQUIFER | BREWSTER"},
        {value: 519, label: "OTHER AQUIFER | BRISCOE"},
        {value: 520, label: "OTHER AQUIFER | BROWN\r\n"},
        {value: 521, label: "OTHER AQUIFER | BURNET"},
        {value: 984, label: "OTHER AQUIFER | CHEROKEE"},
        {value: 522, label: "OTHER AQUIFER | CHILDRESS"},
        {value: 523, label: "OTHER AQUIFER | CLAY"},
        {value: 524, label: "OTHER AQUIFER | COKE"},
        {value: 525, label: "OTHER AQUIFER | COLEMAN"},
        {value: 527, label: "OTHER AQUIFER | COLLINGSWORTH"},
        {value: 529, label: "OTHER AQUIFER | CONCHO"},
        {value: 531, label: "OTHER AQUIFER | COTTLE"},
        {value: 985, label: "OTHER AQUIFER | CROSBY\r\n"},
        {value: 535, label: "OTHER AQUIFER | DICKENS"},
        {value: 536, label: "OTHER AQUIFER | DONLEY"},
        {value: 538, label: "OTHER AQUIFER | EL PASO"},
        {value: 540, label: "OTHER AQUIFER | FANNIN"},
        {value: 541, label: "OTHER AQUIFER | FAYETTE"},
        {value: 986, label: "OTHER AQUIFER | FLOYD"},
        {value: 987, label: "OTHER AQUIFER | FOARD"},
        {value: 988, label: "OTHER AQUIFER | GARZA"},
        {value: 989, label: "OTHER AQUIFER | HALE"},
        {value: 544, label: "OTHER AQUIFER | HALL"},
        {value: 990, label: "OTHER AQUIFER | HARDEMAN"},
        {value: 545, label: "OTHER AQUIFER | HENDERSON"},
        {value: 546, label: "OTHER AQUIFER | HIDALGO"},
        {value: 548, label: "OTHER AQUIFER | HOUSTON"},
        {value: 549, label: "OTHER AQUIFER | HUDSPETH"},
        {value: 550, label: "OTHER AQUIFER | IRION\r\n"},
        {value: 551, label: "OTHER AQUIFER | JACK"},
        {value: 553, label: "OTHER AQUIFER | JEFF DAVIS"},
        {value: 555, label: "OTHER AQUIFER | KING"},
        {value: 557, label: "OTHER AQUIFER | LLANO"},
        {value: 559, label: "OTHER AQUIFER | MAVERICK"},
        {value: 560, label: "OTHER AQUIFER | MCCULLOCH"},
        {value: 561, label: "OTHER AQUIFER | MENARD"},
        {value: 562, label: "OTHER AQUIFER | MITCHELL\r\n"},
        {value: 563, label: "OTHER AQUIFER | MONTAGUE"},
        {value: 564, label: "OTHER AQUIFER | MOTLEY"},
        {value: 565, label: "OTHER AQUIFER | NACOGDOCHES"},
        {value: 568, label: "OTHER AQUIFER | PARKER\r\n"},
        {value: 569, label: "OTHER AQUIFER | PECOS\r\n"},
        {value: 570, label: "OTHER AQUIFER | POLK"},
        {value: 571, label: "OTHER AQUIFER | PRESIDIO\r\n"},
        {value: 575, label: "OTHER AQUIFER | RUNNELS"},
        {value: 991, label: "OTHER AQUIFER | RUSK"},
        {value: 576, label: "OTHER AQUIFER | SABINE"},
        {value: 577, label: "OTHER AQUIFER | SAN AUGUSTINE"},
        {value: 578, label: "OTHER AQUIFER | SCURRY"},
        {value: 579, label: "OTHER AQUIFER | SHACKELFORD"},
        {value: 580, label: "OTHER AQUIFER | SMITH"},
        {value: 581, label: "OTHER AQUIFER | STARR"},
        {value: 582, label: "OTHER AQUIFER | STEPHENS"},
        {value: 583, label: "OTHER AQUIFER | STERLING"},
        {value: 585, label: "OTHER AQUIFER | THROCKMORTON"},
        {value: 586, label: "OTHER AQUIFER | TOM GREEN"},
        {value: 587, label: "OTHER AQUIFER | TRAVIS"},
        {value: 588, label: "OTHER AQUIFER | TRINITY"},
        {value: 591, label: "OTHER AQUIFER | WEBB"},
        {value: 592, label: "OTHER AQUIFER | WHEELER"},
        {value: 593, label: "OTHER AQUIFER | WICHITA"},
        {value: 594, label: "OTHER AQUIFER | WILBARGER"},
        {value: 595, label: "OTHER AQUIFER | WILLIAMSON"},
        {value: 597, label: "OTHER AQUIFER | YOUNG\r\n"},
        {value: 598, label: "OTHER AQUIFER | ZAPATA"},
        {value: 600, label: "PALESTINE LAKE/RESERVOIR"},
        {value: 601, label: "PALO DURO LAKE/RESERVOIR"},
        {value: 602, label: "PALO PINTO LAKE/RESERVOIR"},
        {value: 1065, label: "PALO PINTO OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 603, label: "PAT CLEBURNE LAKE/RESERVOIR"},
        {value: 604, label: "PAT MAYSE LAKE/RESERVOIR"},
        {value: 138, label: "PECOS VALLEY AQUIFER | ANDREWS"},
        {value: 139, label: "PECOS VALLEY AQUIFER | CRANE"},
        {value: 993, label: "PECOS VALLEY AQUIFER | CROCKETT"},
        {value: 140, label: "PECOS VALLEY AQUIFER | ECTOR"},
        {value: 141, label: "PECOS VALLEY AQUIFER | LOVING"},
        {value: 142, label: "PECOS VALLEY AQUIFER | PECOS"},
        {value: 143, label: "PECOS VALLEY AQUIFER | REEVES"},
        {value: 144, label: "PECOS VALLEY AQUIFER | UPTON"},
        {value: 145, label: "PECOS VALLEY AQUIFER | WARD"},
        {value: 146, label: "PECOS VALLEY AQUIFER | WINKLER"},
        {value: 999, label: "PECOS VALLEY/EDWARDS-TRINITY (PLATEAU) AQUIFER | CRANE"},
        {value: 1000, label: "PECOS VALLEY/EDWARDS-TRINITY (PLATEAU) AQUIFER | PECOS\r\n\r\n"},
        {value: 1001, label: "PECOS VALLEY/EDWARDS-TRINITY (PLATEAU) AQUIFER | REEVES"},
        {value: 1002, label: "PECOS VALLEY/EDWARDS-TRINITY (PLATEAU) AQUIFER | WINKLER"},
        {value: 607, label: "PINKSTON LAKE/RESERVOIR"},
        {value: 608, label: "POST LAKE/RESERVOIR"},
        {value: 609, label: "QUEEN CITY AQUIFER | ANDERSON"},
        {value: 610, label: "QUEEN CITY AQUIFER | ANGELINA"},
        {value: 611, label: "QUEEN CITY AQUIFER | ATASCOSA"},
        {value: 612, label: "QUEEN CITY AQUIFER | BASTROP"},
        {value: 613, label: "QUEEN CITY AQUIFER | BRAZOS"},
        {value: 614, label: "QUEEN CITY AQUIFER | BURLESON"},
        {value: 615, label: "QUEEN CITY AQUIFER | CALDWELL"},
        {value: 616, label: "QUEEN CITY AQUIFER | CAMP"},
        {value: 617, label: "QUEEN CITY AQUIFER | CASS"},
        {value: 618, label: "QUEEN CITY AQUIFER | CHEROKEE"},
        {value: 1003, label: "QUEEN CITY AQUIFER | DIMMIT"},
        {value: 619, label: "QUEEN CITY AQUIFER | FAYETTE"},
        {value: 620, label: "QUEEN CITY AQUIFER | FREESTONE"},
        {value: 621, label: "QUEEN CITY AQUIFER | FRIO"},
        {value: 622, label: "QUEEN CITY AQUIFER | GONZALES"},
        {value: 623, label: "QUEEN CITY AQUIFER | GREGG"},
        {value: 624, label: "QUEEN CITY AQUIFER | GRIMES"},
        {value: 1004, label: "QUEEN CITY AQUIFER | GUADALUPE"},
        {value: 625, label: "QUEEN CITY AQUIFER | HARRISON"},
        {value: 626, label: "QUEEN CITY AQUIFER | HENDERSON"},
        {value: 627, label: "QUEEN CITY AQUIFER | HOUSTON"},
        {value: 1005, label: "QUEEN CITY AQUIFER | KARNES"},
        {value: 628, label: "QUEEN CITY AQUIFER | LA SALLE"},
        {value: 629, label: "QUEEN CITY AQUIFER | LEE"},
        {value: 630, label: "QUEEN CITY AQUIFER | LEON"},
        {value: 631, label: "QUEEN CITY AQUIFER | MADISON"},
        {value: 632, label: "QUEEN CITY AQUIFER | MARION"},
        {value: 633, label: "QUEEN CITY AQUIFER | MCMULLEN"},
        {value: 634, label: "QUEEN CITY AQUIFER | MILAM"},
        {value: 635, label: "QUEEN CITY AQUIFER | MORRIS"},
        {value: 636, label: "QUEEN CITY AQUIFER | NACOGDOCHES"},
        {value: 637, label: "QUEEN CITY AQUIFER | ROBERTSON"},
        {value: 638, label: "QUEEN CITY AQUIFER | RUSK"},
        {value: 1008, label: "QUEEN CITY AQUIFER | SAN AUGUSTINE"},
        {value: 639, label: "QUEEN CITY AQUIFER | SMITH"},
        {value: 1010, label: "QUEEN CITY AQUIFER | TITUS"},
        {value: 1011, label: "QUEEN CITY AQUIFER | TRINITY"},
        {value: 640, label: "QUEEN CITY AQUIFER | UPSHUR"},
        {value: 641, label: "QUEEN CITY AQUIFER | VAN ZANDT"},
        {value: 642, label: "QUEEN CITY AQUIFER | WALKER"},
        {value: 1012, label: "QUEEN CITY AQUIFER | WASHINGTON"},
        {value: 1013, label: "QUEEN CITY AQUIFER | WEBB\r\n"},
        {value: 643, label: "QUEEN CITY AQUIFER | WILSON"},
        {value: 644, label: "QUEEN CITY AQUIFER | WOOD"},
        {value: 1014, label: "QUEEN CITY AQUIFER | ZAVALA"},
        {value: 646, label: "RALPH HALL LAKE/RESERVOIR"},
        {value: 647, label: "RANDELL LAKE/RESERVOIR"},
        {value: 648, label: "RAY HUBBARD LAKE/RESERVOIR"},
        {value: 649, label: "RAY ROBERTS LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 650, label: "RAY ROBERTS-LEWISVILLE-GRAPEVINE LAKE/RESERVOIR SYSTEM"},
        {value: 651, label: "RED BLUFF LAKE/RESERVOIR"},
        {value: 386, label: "RED INDIRECT REUSE"},
        {value: 667, label: "RED RUN-OF-RIVER"},
        {value: 1015, label: "REGULATING LAKE/RESERVOIR"},
        {value: 652, label: "RICHLAND CHAMBERS LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 653, label: "RINGGOLD LAKE/RESERVOIR"},
        {value: 387, label: "RIO GRANDE INDIRECT REUSE"},
        {value: 668, label: "RIO GRANDE RUN-OF-RIVER"},
        {value: 679, label: "RUSK CITY LAKE/RESERVOIR"},
        {value: 1017, label: "RUSTLER AQUIFER | BREWSTER"},
        {value: 680, label: "RUSTLER AQUIFER | CULBERSON"},
        {value: 1018, label: "RUSTLER AQUIFER | LOVING"},
        {value: 681, label: "RUSTLER AQUIFER | PECOS"},
        {value: 682, label: "RUSTLER AQUIFER | REEVES"},
        {value: 1019, label: "RUSTLER AQUIFER | WARD"},
        {value: 953, label: "SABINE INDIRECT REUSE"},
        {value: 669, label: "SABINE RUN-OF-RIVER"},
        {value: 683, label: "SAM RAYBURN-STEINHAGEN LAKE/RESERVOIR SYSTEM"},
        {value: 1020, label: "SAN ANGELO LAKES LAKE/SYSTEM"},
        {value: 670, label: "SAN ANTONIO RUN-OF-RIVER"},
        {value: 671, label: "SAN ANTONIO-NUECES RUN-OF-RIVER"},
        {value: 684, label: "SAN AUGUSTINE LAKE/RESERVOIR"},
        {value: 1021, label: "SAN BERNARD RIVER ALLUVIUM AQUIFER | AUSTIN"},
        {value: 388, label: "SAN JACINTO INDIRECT REUSE"},
        {value: 1022, label: "SAN JACINTO RIVER ALLUVIUM AQUIFER | WALKER"},
        {value: 672, label: "SAN JACINTO RUN-OF-RIVER"},
        {value: 673, label: "SAN JACINTO-BRAZOS RUN-OF-RIVER"},
        {value: 685, label: "SANTA ROSA LAKE/RESERVOIR"},
        {value: 1023, label: "SEYMOUR AQUIFER | ARCHER"},
        {value: 686, label: "SEYMOUR AQUIFER | BAYLOR"},
        {value: 687, label: "SEYMOUR AQUIFER | BRISCOE"},
        {value: 688, label: "SEYMOUR AQUIFER | CHILDRESS"},
        {value: 689, label: "SEYMOUR AQUIFER | CLAY"},
        {value: 690, label: "SEYMOUR AQUIFER | COLLINGSWORTH"},
        {value: 694, label: "SEYMOUR AQUIFER | FISHER"},
        {value: 695, label: "SEYMOUR AQUIFER | FOARD"},
        {value: 696, label: "SEYMOUR AQUIFER | HALL"},
        {value: 697, label: "SEYMOUR AQUIFER | HARDEMAN"},
        {value: 698, label: "SEYMOUR AQUIFER | HASKELL"},
        {value: 699, label: "SEYMOUR AQUIFER | JONES"},
        {value: 700, label: "SEYMOUR AQUIFER | KENT"},
        {value: 701, label: "SEYMOUR AQUIFER | KNOX"},
        {value: 702, label: "SEYMOUR AQUIFER | MOTLEY"},
        {value: 703, label: "SEYMOUR AQUIFER | STONEWALL"},
        {value: 1024, label: "SEYMOUR AQUIFER | THROCKMORTON"},
        {value: 705, label: "SEYMOUR AQUIFER | WICHITA"},
        {value: 706, label: "SEYMOUR AQUIFER | WILBARGER"},
        {value: 1025, label: "SEYMOUR AQUIFER | YOUNG"},
        {value: 1026, label: "SIMSBORO AQUIFER ASR | BRAZOS\r\n"},
        {value: 1036, label: "SPARTA AQUIFER ASR | BRAZOS\r\n"},
        {value: 708, label: "SPARTA AQUIFER | ANDERSON"},
        {value: 709, label: "SPARTA AQUIFER | ANGELINA"},
        {value: 710, label: "SPARTA AQUIFER | ATASCOSA"},
        {value: 711, label: "SPARTA AQUIFER | BASTROP"},
        {value: 712, label: "SPARTA AQUIFER | BRAZOS"},
        {value: 713, label: "SPARTA AQUIFER | BURLESON"},
        {value: 714, label: "SPARTA AQUIFER | CHEROKEE"},
        {value: 1027, label: "SPARTA AQUIFER | DIMMIT\r\n"},
        {value: 715, label: "SPARTA AQUIFER | FAYETTE"},
        {value: 716, label: "SPARTA AQUIFER | FRIO"},
        {value: 717, label: "SPARTA AQUIFER | GONZALES"},
        {value: 718, label: "SPARTA AQUIFER | GRIMES"},
        {value: 719, label: "SPARTA AQUIFER | HOUSTON"},
        {value: 1028, label: "SPARTA AQUIFER | KARNES\r\n"},
        {value: 720, label: "SPARTA AQUIFER | LA SALLE"},
        {value: 721, label: "SPARTA AQUIFER | LEE"},
        {value: 722, label: "SPARTA AQUIFER | LEON"},
        {value: 723, label: "SPARTA AQUIFER | MADISON"},
        {value: 724, label: "SPARTA AQUIFER | MCMULLEN"},
        {value: 725, label: "SPARTA AQUIFER | NACOGDOCHES"},
        {value: 726, label: "SPARTA AQUIFER | ROBERTSON"},
        {value: 727, label: "SPARTA AQUIFER | SABINE"},
        {value: 728, label: "SPARTA AQUIFER | SAN AUGUSTINE"},
        {value: 1030, label: "SPARTA AQUIFER | SMITH\r\n"},
        {value: 729, label: "SPARTA AQUIFER | TRINITY"},
        {value: 1031, label: "SPARTA AQUIFER | UPSHUR"},
        {value: 730, label: "SPARTA AQUIFER | WALKER"},
        {value: 1032, label: "SPARTA AQUIFER | WASHINGTON"},
        {value: 1033, label: "SPARTA AQUIFER | WEBB\r\n"},
        {value: 731, label: "SPARTA AQUIFER | WILSON"},
        {value: 1034, label: "SPARTA AQUIFER | WOOD"},
        {value: 1035, label: "SPARTA AQUIFER | ZAVALA\r\n"},
        {value: 732, label: "SQUAW CREEK LAKE/RESERVOIR"},
        {value: 733, label: "STAMFORD LAKE/RESERVOIR"},
        {value: 1037, label: "STRAWN LAKE/RESERVOIR"},
        {value: 734, label: "STRIKER LAKE/RESERVOIR"},
        {value: 389, label: "SULPHUR INDIRECT REUSE"},
        {value: 674, label: "SULPHUR RUN-OF-RIVER"},
        {value: 735, label: "SULPHUR SPRINGS LAKE/RESERVOIR"},
        {value: 736, label: "SWEETWATER LAKE/RESERVOIR"},
        {value: 737, label: "TANKERSLEY LAKE/RESERVOIR"},
        {value: 738, label: "TAWAKONI LAKE/RESERVOIR"},
        {value: 739, label: "TEAGUE CITY LAKE/RESERVOIR"},
        {value: 740, label: "TEHUACANA LAKE/RESERVOIR"},
        {value: 741, label: "TERRELL LAKE/RESERVOIR"},
        {value: 742, label: "TEXANA LAKE/RESERVOIR"},
        {value: 744, label: "TEXOMA LAKE/RESERVOIR NON-SYSTEM PORTION"},
        {value: 745, label: "TEXOMA LAKE/RESERVOIR NORTH TEXAS MWD SYSTEM"},
        {value: 746, label: "THROCKMORTON LAKE/RESERVOIR"},
        {value: 747, label: "TIMPSON LAKE/RESERVOIR"},
        {value: 748, label: "TOLEDO BEND LAKE/RESERVOIR"},
        {value: 1038, label: "TRAMMEL LAKE/RESERVOIR"},
        {value: 751, label: "TRINIDAD CITY LAKE/RESERVOIR"},
        {value: 752, label: "TRINIDAD LAKE/RESERVOIR"},
        {value: 1039, label: "TRINITY AND/OR BRACKISH EDWARDS AQUIFER ASR | COMAL\r\n"},
        {value: 1041, label: "TRINITY AQUIFER ASR | BANDERA\r\n"},
        {value: 1042, label: "TRINITY AQUIFER ASR | HAYS\r\n"},
        {value: 1043, label: "TRINITY AQUIFER ASR | JOHNSON\r\n"},
        {value: 1044, label: "TRINITY AQUIFER ASR | KERR"},
        {value: 1045, label: "TRINITY AQUIFER ASR | MCLENNAN\r\n"},
        {value: 1046, label: "TRINITY AQUIFER ASR | TRAVIS\r\n"},
        {value: 1047, label: "TRINITY AQUIFER ASR | WILLIAMSON\r\n"},
        {value: 753, label: "TRINITY AQUIFER | BANDERA"},
        {value: 754, label: "TRINITY AQUIFER | BASTROP"},
        {value: 755, label: "TRINITY AQUIFER | BELL"},
        {value: 756, label: "TRINITY AQUIFER | BEXAR"},
        {value: 757, label: "TRINITY AQUIFER | BLANCO"},
        {value: 758, label: "TRINITY AQUIFER | BOSQUE"},
        {value: 759, label: "TRINITY AQUIFER | BROWN"},
        {value: 760, label: "TRINITY AQUIFER | BURNET"},
        {value: 761, label: "TRINITY AQUIFER | CALDWELL"},
        {value: 762, label: "TRINITY AQUIFER | CALLAHAN"},
        {value: 763, label: "TRINITY AQUIFER | COLLIN"},
        {value: 764, label: "TRINITY AQUIFER | COMAL"},
        {value: 765, label: "TRINITY AQUIFER | COMANCHE"},
        {value: 766, label: "TRINITY AQUIFER | COOKE"},
        {value: 767, label: "TRINITY AQUIFER | CORYELL"},
        {value: 768, label: "TRINITY AQUIFER | DALLAS"},
        {value: 769, label: "TRINITY AQUIFER | DELTA"},
        {value: 770, label: "TRINITY AQUIFER | DENTON"},
        {value: 771, label: "TRINITY AQUIFER | EASTLAND"},
        {value: 772, label: "TRINITY AQUIFER | ELLIS"},
        {value: 773, label: "TRINITY AQUIFER | ERATH"},
        {value: 774, label: "TRINITY AQUIFER | FALLS"},
        {value: 775, label: "TRINITY AQUIFER | FANNIN"},
        {value: 776, label: "TRINITY AQUIFER | GILLESPIE"},
        {value: 777, label: "TRINITY AQUIFER | GRAYSON"},
        {value: 1040, label: "TRINITY AQUIFER | GUADALUPE"},
        {value: 778, label: "TRINITY AQUIFER | HAMILTON"},
        {value: 779, label: "TRINITY AQUIFER | HAYS"},
        {value: 780, label: "TRINITY AQUIFER | HILL"},
        {value: 781, label: "TRINITY AQUIFER | HOOD"},
        {value: 782, label: "TRINITY AQUIFER | HUNT"},
        {value: 783, label: "TRINITY AQUIFER | JACK"},
        {value: 784, label: "TRINITY AQUIFER | JOHNSON"},
        {value: 785, label: "TRINITY AQUIFER | KAUFMAN"},
        {value: 786, label: "TRINITY AQUIFER | KENDALL"},
        {value: 787, label: "TRINITY AQUIFER | KERR"},
        {value: 788, label: "TRINITY AQUIFER | LAMAR"},
        {value: 789, label: "TRINITY AQUIFER | LAMPASAS"},
        {value: 790, label: "TRINITY AQUIFER | LIMESTONE"},
        {value: 791, label: "TRINITY AQUIFER | MCLENNAN"},
        {value: 792, label: "TRINITY AQUIFER | MEDINA"},
        {value: 793, label: "TRINITY AQUIFER | MILAM"},
        {value: 794, label: "TRINITY AQUIFER | MILLS"},
        {value: 795, label: "TRINITY AQUIFER | MONTAGUE"},
        {value: 796, label: "TRINITY AQUIFER | NAVARRO"},
        {value: 797, label: "TRINITY AQUIFER | PALO PINTO"},
        {value: 798, label: "TRINITY AQUIFER | PARKER"},
        {value: 799, label: "TRINITY AQUIFER | REAL"},
        {value: 800, label: "TRINITY AQUIFER | RED RIVER"},
        {value: 801, label: "TRINITY AQUIFER | ROCKWALL"},
        {value: 802, label: "TRINITY AQUIFER | SOMERVELL"},
        {value: 803, label: "TRINITY AQUIFER | TARRANT"},
        {value: 804, label: "TRINITY AQUIFER | TAYLOR"},
        {value: 805, label: "TRINITY AQUIFER | TRAVIS"},
        {value: 806, label: "TRINITY AQUIFER | UVALDE"},
        {value: 807, label: "TRINITY AQUIFER | WILLIAMSON"},
        {value: 808, label: "TRINITY AQUIFER | WISE"},
        {value: 390, label: "TRINITY INDIRECT REUSE"},
        {value: 1048, label: "TRINITY RIVER ALLUVIUM AQUIFER | WALKER\r\n"},
        {value: 675, label: "TRINITY RUN-OF-RIVER"},
        {value: 676, label: "TRINITY-SAN JACINTO RUN-OF-RIVER"},
        {value: 810, label: "TRWD LAKE/RESERVOIR SYSTEM"},
        {value: 811, label: "TURKEY CREEK LAKE/RESERVOIR"},
        {value: 812, label: "TURKEY PEAK LAKE/RESERVOIR"},
        {value: 1049, label: "TURTLE CREEK LAKE/RESERVOIR"},
        {value: 814, label: "TWIN OAK LAKE/RESERVOIR"},
        {value: 815, label: "TYLER LAKE/RESERVOIR"},
        {value: 817, label: "VICTOR BRAUNIG LAKE/RESERVOIR"},
        {value: 818, label: "WACO LAKE/RESERVOIR"},
        {value: 819, label: "WAXAHACHIE LAKE/RESERVOIR"},
        {value: 821, label: "WEATHERFORD LAKE/RESERVOIR"},
        {value: 822, label: "WELSH LAKE/RESERVOIR"},
        {value: 823, label: "WEST TEXAS BOLSONS AQUIFER | CULBERSON"},
        {value: 824, label: "WEST TEXAS BOLSONS AQUIFER | HUDSPETH"},
        {value: 825, label: "WEST TEXAS BOLSONS AQUIFER | JEFF DAVIS"},
        {value: 826, label: "WEST TEXAS BOLSONS AQUIFER | PRESIDIO"},
        {value: 827, label: "WHEELER BRANCH OFF-CHANNEL LAKE/RESERVOIR"},
        {value: 828, label: "WHITE RIVER LAKE/RESERVOIR"},
        {value: 829, label: "WHITE ROCK LAKE/RESERVOIR"},
        {value: 832, label: "WINTERS LAKE/RESERVOIR"},
        {value: 833, label: "WOODBINE AQUIFER | COLLIN"},
        {value: 834, label: "WOODBINE AQUIFER | COOKE"},
        {value: 835, label: "WOODBINE AQUIFER | DALLAS"},
        {value: 837, label: "WOODBINE AQUIFER | DENTON"},
        {value: 838, label: "WOODBINE AQUIFER | ELLIS"},
        {value: 839, label: "WOODBINE AQUIFER | FANNIN"},
        {value: 840, label: "WOODBINE AQUIFER | GRAYSON"},
        {value: 841, label: "WOODBINE AQUIFER | HILL"},
        {value: 842, label: "WOODBINE AQUIFER | HUNT"},
        {value: 843, label: "WOODBINE AQUIFER | JOHNSON"},
        {value: 844, label: "WOODBINE AQUIFER | KAUFMAN"},
        {value: 845, label: "WOODBINE AQUIFER | LAMAR"},
        {value: 846, label: "WOODBINE AQUIFER | LIMESTONE"},
        {value: 847, label: "WOODBINE AQUIFER | MCLENNAN"},
        {value: 848, label: "WOODBINE AQUIFER | NAVARRO"},
        {value: 850, label: "WOODBINE AQUIFER | RED RIVER"},
        {value: 851, label: "WOODBINE AQUIFER | ROCKWALL"},
        {value: 852, label: "WOODBINE AQUIFER | TARRANT"},
        {value: 1054, label: "WOODSON LAKE/RESERVOIR"},
        {value: 854, label: "WRIGHT PATMAN LAKE/RESERVOIR"},
        {value: 855, label: "YEGUA-JACKSON AQUIFER | ANGELINA"},
        {value: 1055, label: "YEGUA-JACKSON AQUIFER | ATASCOSA"},
        {value: 0, label: "YEGUA-JACKSON AQUIFER | BASTROP"},
        {value: 856, label: "YEGUA-JACKSON AQUIFER | BRAZOS"},
        {value: 857, label: "YEGUA-JACKSON AQUIFER | BURLESON"},
        {value: 858, label: "YEGUA-JACKSON AQUIFER | FAYETTE"},
        {value: 1056, label: "YEGUA-JACKSON AQUIFER | FRIO"},
        {value: 1057, label: "YEGUA-JACKSON AQUIFER | GONZALES"},
        {value: 859, label: "YEGUA-JACKSON AQUIFER | GRIMES"},
        {value: 860, label: "YEGUA-JACKSON AQUIFER | HOUSTON"},
        {value: 861, label: "YEGUA-JACKSON AQUIFER | JIM HOGG"},
        {value: 1058, label: "YEGUA-JACKSON AQUIFER | KARNES"},
        {value: 1059, label: "YEGUA-JACKSON AQUIFER | LA SALLE"},
        {value: 862, label: "YEGUA-JACKSON AQUIFER | LEE"},
        {value: 1060, label: "YEGUA-JACKSON AQUIFER | LEON"},
        {value: 1061, label: "YEGUA-JACKSON AQUIFER | MADISON"},
        {value: 1062, label: "YEGUA-JACKSON AQUIFER | MCMULLEN"},
        {value: 863, label: "YEGUA-JACKSON AQUIFER | NACOGDOCHES"},
        {value: 864, label: "YEGUA-JACKSON AQUIFER | POLK"},
        {value: 865, label: "YEGUA-JACKSON AQUIFER | SABINE"},
        {value: 866, label: "YEGUA-JACKSON AQUIFER | SAN AUGUSTINE"},
        {value: 867, label: "YEGUA-JACKSON AQUIFER | STARR"},
        {value: 868, label: "YEGUA-JACKSON AQUIFER | TRINITY"},
        {value: 869, label: "YEGUA-JACKSON AQUIFER | TYLER"},
        {value: 870, label: "YEGUA-JACKSON AQUIFER | WALKER"},
        {value: 871, label: "YEGUA-JACKSON AQUIFER | WASHINGTON"},
        {value: 872, label: "YEGUA-JACKSON AQUIFER | WEBB"},
        {value: 1063, label: "YEGUA-JACKSON AQUIFER | WILSON"},
        {value: 873, label: "YEGUA-JACKSON AQUIFER | ZAPATA"}
    ];


    getThemeTitles() {
        return this.#theme_titles;
    }

    getDecades() {
        return this.#decades;
    }

    getUsageTypes() {
        return this.#usage_types;
    }

    getThemes() {
        return this.#themes;
    }

    getYear() {
        return this.#year;
    }

    getRegions() {
        return this.#regions;
    }

    getCountyNames() {
        return this.#countyNames;
    }
}
