export const sourceNames = [
	{"label":1,"value":"Abilene Lake/Reservoir"},
	{"label":2,"value":"Alan Henry Lake/Reservoir"},
	{"label":3,"value":"Alcoa Lake/Reservoir"},
	{"label":4,"value":"Allens Creek Lake/Reservoir"},
	{"label":5,"value":"Alvarado Lake/Reservoir"},
	{"label":6,"value":"Amistad-Falcon Lake/Reservoir System"},
	{"label":7,"value":"Amon G. Carter Lake/Reservoir"},
	{"label":884,"value":"Anson North Lake/Reservoir"},
	{"label":9,"value":"Athens Lake/Reservoir"},
	{"label":820,"value":"Atmosphere"},
	{"label":885,"value":"Austin Chalk Aquifer | Kinney"},
	{"label":886,"value":"Austin Chalk Aquifer | Uvalde"},
	{"label":1079,"value":"Austin Off-Channel Lake/Reservoir"},
	{"label":1076,"value":"BRA System Operations Permit Supply"},
	{"label":887,"value":"Baird Lake/Reservoir"},
	{"label":10,"value":"Ballinger/Moonen Lake/Reservoir"},
	{"label":11,"value":"Balmorhea Lake/Reservoir"},
	{"label":12,"value":"Bardwell Lake/Reservoir"},
	{"label":888,"value":"Baylor Creek Lake/Reservoir"},
	{"label":1132,"value":"Beaumont West Regional Lake/Reservoir"},
	{"label":14,"value":"Bellwood Lake/Reservoir"},
	{"label":15,"value":"Big Creek Lake/Reservoir"},
	{"label":16,"value":"Big Sandy Creek Lake/Reservoir"},
	{"label":17,"value":"Blaine Aquifer | Childress"},
	{"label":18,"value":"Blaine Aquifer | Collingsworth"},
	{"label":19,"value":"Blaine Aquifer | Cottle"},
	{"label":20,"value":"Blaine Aquifer | Fisher"},
	{"label":21,"value":"Blaine Aquifer | Foard"},
	{"label":22,"value":"Blaine Aquifer | Hall"},
	{"label":23,"value":"Blaine Aquifer | Hardeman"},
	{"label":24,"value":"Blaine Aquifer | King"},
	{"label":25,"value":"Blaine Aquifer | Knox"},
	{"label":26,"value":"Blaine Aquifer | Nolan"},
	{"label":27,"value":"Blaine Aquifer | Stonewall"},
	{"label":28,"value":"Blaine Aquifer | Wheeler"},
	{"label":29,"value":"Blanco Lake/Reservoir"},
	{"label":30,"value":"Blossom Aquifer | Bowie"},
	{"label":31,"value":"Blossom Aquifer | Lamar"},
	{"label":32,"value":"Blossom Aquifer | Red River"},
	{"label":33,"value":"Bob Sandlin Lake/Reservoir"},
	{"label":34,"value":"Boerne Lake/Reservoir"},
	{"label":415,"value":"Bois D'Arc Lake/Reservoir"},
	{"label":35,"value":"Bone Spring-Victorio Peak Aquifer | Hudspeth"},
	{"label":36,"value":"Bonham Lake/Reservoir"},
	{"label":37,"value":"Brady Creek Lake/Reservoir"},
	{"label":38,"value":"Brandy Branch Lake/Reservoir"},
	{"label":952,"value":"Brazos Indirect Reuse"},
	{"label":40,"value":"Brazos River Alluvium Aquifer | Austin"},
	{"label":41,"value":"Brazos River Alluvium Aquifer | Bosque"},
	{"label":42,"value":"Brazos River Alluvium Aquifer | Brazos"},
	{"label":43,"value":"Brazos River Alluvium Aquifer | Burleson"},
	{"label":44,"value":"Brazos River Alluvium Aquifer | Falls"},
	{"label":46,"value":"Brazos River Alluvium Aquifer | Grimes"},
	{"label":47,"value":"Brazos River Alluvium Aquifer | Hill"},
	{"label":48,"value":"Brazos River Alluvium Aquifer | McLennan"},
	{"label":49,"value":"Brazos River Alluvium Aquifer | Milam"},
	{"label":50,"value":"Brazos River Alluvium Aquifer | Robertson"},
	{"label":51,"value":"Brazos River Alluvium Aquifer | Waller"},
	{"label":52,"value":"Brazos River Alluvium Aquifer | Washington"},
	{"label":53,"value":"Brazos River Authority Aquilla Lake/Reservoir System"},
	{"label":54,"value":"Brazos River Authority Little River Lake/Reservoir System"},
	{"label":55,"value":"Brazos River Authority Main Stem Lake/Reservoir System"},
	{"label":655,"value":"Brazos Run-of-River"},
	{"label":656,"value":"Brazos-Colorado Run-of-River"},
	{"label":57,"value":"Brownwood Lake/Reservoir"},
	{"label":59,"value":"Brushy Creek Lake/Reservoir"},
	{"label":60,"value":"Bryson Lake/Reservoir"},
	{"label":889,"value":"Buda Limestone Aquifer | Uvalde"},
	{"label":897,"value":"CRMWD Diverted Water System"},
	{"label":61,"value":"Caddo Lake/Reservoir"},
	{"label":62,"value":"Calaveras Lake/Reservoir"},
	{"label":657,"value":"Canadian Run-of-River"},
	{"label":63,"value":"Caney Creek Lake/Reservoir"},
	{"label":64,"value":"Canyon Lake/Reservoir"},
	{"label":65,"value":"Capitan Reef Complex Aquifer | Brewster"},
	{"label":66,"value":"Capitan Reef Complex Aquifer | Culberson"},
	{"label":67,"value":"Capitan Reef Complex Aquifer | Hudspeth"},
	{"label":1087,"value":"Capitan Reef Complex Aquifer | Jeff Davis"},
	{"label":68,"value":"Capitan Reef Complex Aquifer | Pecos"},
	{"label":890,"value":"Capitan Reef Complex Aquifer | Reeves"},
	{"label":69,"value":"Capitan Reef Complex Aquifer | Ward"},
	{"label":70,"value":"Capitan Reef Complex Aquifer | Winkler"},
	{"label":1088,"value":"Carrizo-Aquifer ASR | Bexar"},
	{"label":892,"value":"Carrizo-Wilcox Aquifer ASR | Bastrop"},
	{"label":1066,"value":"Carrizo-Wilcox Aquifer ASR | Gonzales"},
	{"label":1089,"value":"Carrizo-Wilcox Aquifer ASR | Maverick"},
	{"label":71,"value":"Carrizo-Wilcox Aquifer | Anderson"},
	{"label":72,"value":"Carrizo-Wilcox Aquifer | Angelina"},
	{"label":73,"value":"Carrizo-Wilcox Aquifer | Atascosa"},
	{"label":74,"value":"Carrizo-Wilcox Aquifer | Bastrop"},
	{"label":76,"value":"Carrizo-Wilcox Aquifer | Bexar"},
	{"label":77,"value":"Carrizo-Wilcox Aquifer | Bowie"},
	{"label":78,"value":"Carrizo-Wilcox Aquifer | Brazos"},
	{"label":79,"value":"Carrizo-Wilcox Aquifer | Burleson"},
	{"label":80,"value":"Carrizo-Wilcox Aquifer | Caldwell"},
	{"label":81,"value":"Carrizo-Wilcox Aquifer | Camp"},
	{"label":82,"value":"Carrizo-Wilcox Aquifer | Cass"},
	{"label":83,"value":"Carrizo-Wilcox Aquifer | Cherokee"},
	{"label":84,"value":"Carrizo-Wilcox Aquifer | Dimmit"},
	{"label":85,"value":"Carrizo-Wilcox Aquifer | Falls"},
	{"label":86,"value":"Carrizo-Wilcox Aquifer | Fayette"},
	{"label":87,"value":"Carrizo-Wilcox Aquifer | Franklin"},
	{"label":88,"value":"Carrizo-Wilcox Aquifer | Freestone"},
	{"label":89,"value":"Carrizo-Wilcox Aquifer | Frio"},
	{"label":90,"value":"Carrizo-Wilcox Aquifer | Gonzales"},
	{"label":91,"value":"Carrizo-Wilcox Aquifer | Gregg"},
	{"label":92,"value":"Carrizo-Wilcox Aquifer | Grimes"},
	{"label":93,"value":"Carrizo-Wilcox Aquifer | Guadalupe"},
	{"label":94,"value":"Carrizo-Wilcox Aquifer | Harrison"},
	{"label":95,"value":"Carrizo-Wilcox Aquifer | Henderson"},
	{"label":96,"value":"Carrizo-Wilcox Aquifer | Hopkins"},
	{"label":97,"value":"Carrizo-Wilcox Aquifer | Houston"},
	{"label":99,"value":"Carrizo-Wilcox Aquifer | Karnes"},
	{"label":100,"value":"Carrizo-Wilcox Aquifer | La Salle"},
	{"label":101,"value":"Carrizo-Wilcox Aquifer | Lee"},
	{"label":102,"value":"Carrizo-Wilcox Aquifer | Leon"},
	{"label":103,"value":"Carrizo-Wilcox Aquifer | Limestone"},
	{"label":105,"value":"Carrizo-Wilcox Aquifer | Madison"},
	{"label":106,"value":"Carrizo-Wilcox Aquifer | Marion"},
	{"label":107,"value":"Carrizo-Wilcox Aquifer | Maverick"},
	{"label":108,"value":"Carrizo-Wilcox Aquifer | McMullen"},
	{"label":109,"value":"Carrizo-Wilcox Aquifer | Medina"},
	{"label":110,"value":"Carrizo-Wilcox Aquifer | Milam"},
	{"label":111,"value":"Carrizo-Wilcox Aquifer | Morris"},
	{"label":112,"value":"Carrizo-Wilcox Aquifer | Nacogdoches"},
	{"label":113,"value":"Carrizo-Wilcox Aquifer | Navarro"},
	{"label":114,"value":"Carrizo-Wilcox Aquifer | Panola"},
	{"label":115,"value":"Carrizo-Wilcox Aquifer | Rains"},
	{"label":116,"value":"Carrizo-Wilcox Aquifer | Red River"},
	{"label":117,"value":"Carrizo-Wilcox Aquifer | Robertson"},
	{"label":118,"value":"Carrizo-Wilcox Aquifer | Rusk"},
	{"label":119,"value":"Carrizo-Wilcox Aquifer | Sabine"},
	{"label":120,"value":"Carrizo-Wilcox Aquifer | San Augustine"},
	{"label":121,"value":"Carrizo-Wilcox Aquifer | Shelby"},
	{"label":122,"value":"Carrizo-Wilcox Aquifer | Smith"},
	{"label":123,"value":"Carrizo-Wilcox Aquifer | Titus"},
	{"label":124,"value":"Carrizo-Wilcox Aquifer | Trinity"},
	{"label":125,"value":"Carrizo-Wilcox Aquifer | Upshur"},
	{"label":126,"value":"Carrizo-Wilcox Aquifer | Uvalde"},
	{"label":127,"value":"Carrizo-Wilcox Aquifer | Van Zandt"},
	{"label":128,"value":"Carrizo-Wilcox Aquifer | Walker"},
	{"label":129,"value":"Carrizo-Wilcox Aquifer | Webb"},
	{"label":891,"value":"Carrizo-Wilcox Aquifer | Williamson"},
	{"label":130,"value":"Carrizo-Wilcox Aquifer | Wilson"},
	{"label":131,"value":"Carrizo-Wilcox Aquifer | Wood"},
	{"label":132,"value":"Carrizo-Wilcox Aquifer | Zavala"},
	{"label":137,"value":"Cedar Ridge Lake/Reservoir"},
	{"label":147,"value":"Center Lake/Reservoir"},
	{"label":148,"value":"Chapman/Cooper Lake/Reservoir Non-System Portion"},
	{"label":150,"value":"Cherokee Lake/Reservoir"},
	{"label":151,"value":"Cisco Lake/Reservoir"},
	{"label":894,"value":"City of Hamlin Lake/Reservoir"},
	{"label":152,"value":"Clark Lake/Reservoir"},
	{"label":895,"value":"Clifton Lake/Reservoir"},
	{"label":153,"value":"Clyde Lake/Reservoir"},
	{"label":155,"value":"Coleman Lake/Reservoir"},
	{"label":156,"value":"Coleto Creek Lake/Reservoir"},
	{"label":157,"value":"Colorado City-Champion Lake/Reservoir System"},
	{"label":381,"value":"Colorado Indirect Reuse"},
	{"label":158,"value":"Colorado River MWD Lake/Reservoir System"},
	{"label":658,"value":"Colorado Run-of-River"},
	{"label":659,"value":"Colorado-Lavaca Run-of-River"},
	{"label":159,"value":"Columbia Lake/Reservoir"},
	{"label":160,"value":"Conroe Lake/Reservoir"},
	{"label":162,"value":"Coolidge Lake/Reservoir"},
	{"label":163,"value":"Corpus Christi-Choke Canyon Lake/Reservoir System"},
	{"label":164,"value":"Coryell County Off-Channel Lake/Reservoir"},
	{"label":896,"value":"Crawford Lake/Reservoir"},
	{"label":165,"value":"Crook Lake/Reservoir"},
	{"label":1090,"value":"Cross Timbers Aquifer | Archer"},
	{"label":1091,"value":"Cross Timbers Aquifer | Baylor"},
	{"label":1070,"value":"Cross Timbers Aquifer | Brown"},
	{"label":1092,"value":"Cross Timbers Aquifer | Clay"},
	{"label":1093,"value":"Cross Timbers Aquifer | Coleman"},
	{"label":1071,"value":"Cross Timbers Aquifer | Jack"},
	{"label":1094,"value":"Cross Timbers Aquifer | McCulloch"},
	{"label":1095,"value":"Cross Timbers Aquifer | Montague"},
	{"label":1072,"value":"Cross Timbers Aquifer | Parker"},
	{"label":1096,"value":"Cross Timbers Aquifer | Shackelford"},
	{"label":1097,"value":"Cross Timbers Aquifer | Stephens"},
	{"label":1073,"value":"Cross Timbers Aquifer | Throckmorton"},
	{"label":1098,"value":"Cross Timbers Aquifer | Wichita"},
	{"label":1074,"value":"Cross Timbers Aquifer | Young"},
	{"label":1099,"value":"Cross Timbers Aquifer | Young"},
	{"label":660,"value":"Cypress Run-of-River"},
	{"label":166,"value":"Cypress Springs Lake/Reservoir"},
	{"label":167,"value":"Daniel Lake/Reservoir"},
	{"label":168,"value":"Dansby Power Plant/Bryan Utilities Lake/Reservoir"},
	{"label":1140,"value":"Delta Panchita Lake/Reservoir"},
	{"label":898,"value":"Dimple Lake/Reservoir"},
	{"label":169,"value":"Direct Reuse"},
	{"label":170,"value":"Dockum Aquifer | Andrews"},
	{"label":171,"value":"Dockum Aquifer | Armstrong"},
	{"label":899,"value":"Dockum Aquifer | Bailey"},
	{"label":172,"value":"Dockum Aquifer | Borden"},
	{"label":173,"value":"Dockum Aquifer | Briscoe"},
	{"label":174,"value":"Dockum Aquifer | Carson"},
	{"label":900,"value":"Dockum Aquifer | Castro"},
	{"label":901,"value":"Dockum Aquifer | Cochran"},
	{"label":1100,"value":"Dockum Aquifer | Coke"},
	{"label":176,"value":"Dockum Aquifer | Crane"},
	{"label":902,"value":"Dockum Aquifer | Crockett"},
	{"label":903,"value":"Dockum Aquifer | Crosby"},
	{"label":177,"value":"Dockum Aquifer | Dallam"},
	{"label":178,"value":"Dockum Aquifer | Deaf Smith"},
	{"label":905,"value":"Dockum Aquifer | Dickens"},
	{"label":179,"value":"Dockum Aquifer | Ector"},
	{"label":180,"value":"Dockum Aquifer | Fisher"},
	{"label":906,"value":"Dockum Aquifer | Floyd"},
	{"label":907,"value":"Dockum Aquifer | Gaines"},
	{"label":181,"value":"Dockum Aquifer | Garza"},
	{"label":182,"value":"Dockum Aquifer | Glasscock"},
	{"label":908,"value":"Dockum Aquifer | Hale"},
	{"label":183,"value":"Dockum Aquifer | Hartley"},
	{"label":909,"value":"Dockum Aquifer | Hockley"},
	{"label":184,"value":"Dockum Aquifer | Howard"},
	{"label":910,"value":"Dockum Aquifer | Irion"},
	{"label":185,"value":"Dockum Aquifer | Kent"},
	{"label":911,"value":"Dockum Aquifer | Lamb"},
	{"label":186,"value":"Dockum Aquifer | Loving"},
	{"label":912,"value":"Dockum Aquifer | Lubbock"},
	{"label":913,"value":"Dockum Aquifer | Lynn"},
	{"label":914,"value":"Dockum Aquifer | Martin"},
	{"label":187,"value":"Dockum Aquifer | Midland"},
	{"label":188,"value":"Dockum Aquifer | Mitchell"},
	{"label":189,"value":"Dockum Aquifer | Moore"},
	{"label":915,"value":"Dockum Aquifer | Motley"},
	{"label":190,"value":"Dockum Aquifer | Nolan"},
	{"label":191,"value":"Dockum Aquifer | Oldham"},
	{"label":916,"value":"Dockum Aquifer | Parmer"},
	{"label":192,"value":"Dockum Aquifer | Pecos"},
	{"label":193,"value":"Dockum Aquifer | Potter"},
	{"label":194,"value":"Dockum Aquifer | Randall"},
	{"label":195,"value":"Dockum Aquifer | Reagan"},
	{"label":196,"value":"Dockum Aquifer | Reeves"},
	{"label":197,"value":"Dockum Aquifer | Scurry"},
	{"label":198,"value":"Dockum Aquifer | Sherman"},
	{"label":917,"value":"Dockum Aquifer | Sterling"},
	{"label":199,"value":"Dockum Aquifer | Swisher"},
	{"label":1101,"value":"Dockum Aquifer | Tom Green"},
	{"label":201,"value":"Dockum Aquifer | Upton"},
	{"label":202,"value":"Dockum Aquifer | Ward"},
	{"label":203,"value":"Dockum Aquifer | Winkler"},
	{"label":1127,"value":"Dow Harris Reservoir Expansion"},
	{"label":274,"value":"EV Spence Lake/Reservoir Non-System Portion"},
	{"label":919,"value":"Eastland Lake/Reservoir"},
	{"label":206,"value":"Edgewood City Lake/Reservoir"},
	{"label":1136,"value":"Edwards-BFZ Aquifer (Saline Portion) ASR | Travis"},
	{"label":207,"value":"Edwards-BFZ Aquifer | Atascosa"},
	{"label":208,"value":"Edwards-BFZ Aquifer | Bell"},
	{"label":209,"value":"Edwards-BFZ Aquifer | Bexar"},
	{"label":923,"value":"Edwards-BFZ Aquifer | Caldwell"},
	{"label":210,"value":"Edwards-BFZ Aquifer | Comal"},
	{"label":924,"value":"Edwards-BFZ Aquifer | Frio"},
	{"label":211,"value":"Edwards-BFZ Aquifer | Guadalupe"},
	{"label":212,"value":"Edwards-BFZ Aquifer | Hays"},
	{"label":213,"value":"Edwards-BFZ Aquifer | Kinney"},
	{"label":214,"value":"Edwards-BFZ Aquifer | Medina"},
	{"label":215,"value":"Edwards-BFZ Aquifer | Travis"},
	{"label":216,"value":"Edwards-BFZ Aquifer | Uvalde"},
	{"label":217,"value":"Edwards-BFZ Aquifer | Williamson"},
	{"label":141,"value":"Edwards-Trinity-Plateau And Pecos Valley Aquifers | Loving"},
	{"label":145,"value":"Edwards-Trinity-Plateau And Pecos Valley Aquifers | Ward"},
	{"label":220,"value":"Edwards-Trinity-Plateau Aquifer | Andrews"},
	{"label":221,"value":"Edwards-Trinity-Plateau Aquifer | Bandera"},
	{"label":1084,"value":"Edwards-Trinity-Plateau Aquifer | Blanco"},
	{"label":223,"value":"Edwards-Trinity-Plateau Aquifer | Brewster"},
	{"label":228,"value":"Edwards-Trinity-Plateau Aquifer | Culberson"},
	{"label":233,"value":"Edwards-Trinity-Plateau Aquifer | Howard"},
	{"label":236,"value":"Edwards-Trinity-Plateau Aquifer | Kendall"},
	{"label":237,"value":"Edwards-Trinity-Plateau Aquifer | Kerr"},
	{"label":240,"value":"Edwards-Trinity-Plateau Aquifer | Martin"},
	{"label":1130,"value":"Edwards-Trinity-Plateau and Pecos Valley Aquifers ASR | Reeves"},
	{"label":999,"value":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Crane"},
	{"label":235,"value":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Jeff Davis"},
	{"label":1000,"value":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Pecos"},
	{"label":1001,"value":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Reeves"},
	{"label":1002,"value":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Winkler"},
	{"label":224,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Coke"},
	{"label":225,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Concho"},
	{"label":227,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Crockett"},
	{"label":229,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Ector"},
	{"label":230,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Edwards"},
	{"label":231,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Gillespie"},
	{"label":232,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Glasscock"},
	{"label":234,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Irion"},
	{"label":238,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Kimble"},
	{"label":239,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Kinney"},
	{"label":241,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Mason"},
	{"label":242,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | McCulloch"},
	{"label":243,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Menard"},
	{"label":244,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Midland"},
	{"label":245,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Nolan"},
	{"label":246,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Pecos"},
	{"label":247,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Reagan"},
	{"label":248,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Real"},
	{"label":250,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Schleicher"},
	{"label":251,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Sterling"},
	{"label":252,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Sutton"},
	{"label":253,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Taylor"},
	{"label":254,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Terrell"},
	{"label":255,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Tom Green"},
	{"label":256,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Upton"},
	{"label":257,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Uvalde"},
	{"label":258,"value":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Val Verde"},
	{"label":260,"value":"Electra City Lake/Reservoir"},
	{"label":261,"value":"Ellenburger-San Saba Aquifer | Blanco"},
	{"label":938,"value":"Ellenburger-San Saba Aquifer | Brown"},
	{"label":262,"value":"Ellenburger-San Saba Aquifer | Burnet"},
	{"label":263,"value":"Ellenburger-San Saba Aquifer | Gillespie"},
	{"label":1082,"value":"Ellenburger-San Saba Aquifer | Kendall"},
	{"label":937,"value":"Ellenburger-San Saba Aquifer | Kerr"},
	{"label":264,"value":"Ellenburger-San Saba Aquifer | Kimble"},
	{"label":265,"value":"Ellenburger-San Saba Aquifer | Lampasas"},
	{"label":266,"value":"Ellenburger-San Saba Aquifer | Llano"},
	{"label":267,"value":"Ellenburger-San Saba Aquifer | Mason"},
	{"label":268,"value":"Ellenburger-San Saba Aquifer | McCulloch"},
	{"label":269,"value":"Ellenburger-San Saba Aquifer | Menard"},
	{"label":270,"value":"Ellenburger-San Saba Aquifer | Mills"},
	{"label":271,"value":"Ellenburger-San Saba Aquifer | San Saba"},
	{"label":272,"value":"Elliot Creek Lake/Reservoir"},
	{"label":273,"value":"Ellison Creek Lake/Reservoir"},
	{"label":1142,"value":"Engleman Lake/Reservoir"},
	{"label":275,"value":"Fairfield Lake/Reservoir"},
	{"label":276,"value":"Farmers Creek/Nocona Lake/Reservoir"},
	{"label":278,"value":"Forest Grove Lake/Reservoir"},
	{"label":279,"value":"Fork Lake/Reservoir"},
	{"label":281,"value":"Fort Phantom Hill Lake/Reservoir"},
	{"label":1069,"value":"Frio River Alluvium Aquifer | Real"},
	{"label":1126,"value":"GBRA Lower Basin New Appropriation Off-Channel Reservoir"},
	{"label":879,"value":"GBRA Lower Basin Off-Channel Lake/Reservoir"},
	{"label":283,"value":"George Parkhouse North Lake/Reservoir"},
	{"label":284,"value":"George Parkhouse South Lake/Reservoir"},
	{"label":285,"value":"Gibbons Creek Lake/Reservoir"},
	{"label":287,"value":"Gilmer Lake/Reservoir"},
	{"label":288,"value":"Gladewater Lake/Reservoir"},
	{"label":289,"value":"Goldthwaite Lake/Reservoir"},
	{"label":940,"value":"Gordon Lake/Reservoir"},
	{"label":290,"value":"Graham/Eddleman Lake/Reservoir"},
	{"label":291,"value":"Grand Saline Lake/Reservoir"},
	{"label":292,"value":"Grapevine Lake/Reservoir Non-System Portion"},
	{"label":293,"value":"Greenbelt Lake/Reservoir"},
	{"label":294,"value":"Greenville City Lake/Reservoir"},
	{"label":295,"value":"Groesbeck Off-Channel Lake/Reservoir"},
	{"label":942,"value":"Guadalupe River Off-Channel Lake/Reservoir"},
	{"label":661,"value":"Guadalupe Run-of-River"},
	{"label":943,"value":"Gulf Coast Aquifer ASR | Jackson"},
	{"label":1103,"value":"Gulf Coast Aquifer ASR | Montgomery"},
	{"label":944,"value":"Gulf Coast Aquifer ASR | Victoria"},
	{"label":1105,"value":"Gulf Coast Aquifer System ASR (Corpus Christi) | Nueces"},
	{"label":296,"value":"Gulf Coast Aquifer System | Aransas"},
	{"label":297,"value":"Gulf Coast Aquifer System | Austin"},
	{"label":298,"value":"Gulf Coast Aquifer System | Bee"},
	{"label":299,"value":"Gulf Coast Aquifer System | Brazoria"},
	{"label":300,"value":"Gulf Coast Aquifer System | Brazos"},
	{"label":301,"value":"Gulf Coast Aquifer System | Brooks"},
	{"label":302,"value":"Gulf Coast Aquifer System | Calhoun"},
	{"label":303,"value":"Gulf Coast Aquifer System | Cameron"},
	{"label":304,"value":"Gulf Coast Aquifer System | Chambers"},
	{"label":305,"value":"Gulf Coast Aquifer System | Colorado"},
	{"label":306,"value":"Gulf Coast Aquifer System | DeWitt"},
	{"label":307,"value":"Gulf Coast Aquifer System | Duval"},
	{"label":308,"value":"Gulf Coast Aquifer System | Fayette"},
	{"label":309,"value":"Gulf Coast Aquifer System | Fort Bend"},
	{"label":310,"value":"Gulf Coast Aquifer System | Galveston"},
	{"label":311,"value":"Gulf Coast Aquifer System | Goliad"},
	{"label":312,"value":"Gulf Coast Aquifer System | Gonzales"},
	{"label":313,"value":"Gulf Coast Aquifer System | Grimes"},
	{"label":314,"value":"Gulf Coast Aquifer System | Hardin"},
	{"label":315,"value":"Gulf Coast Aquifer System | Harris"},
	{"label":316,"value":"Gulf Coast Aquifer System | Hidalgo"},
	{"label":317,"value":"Gulf Coast Aquifer System | Jackson"},
	{"label":318,"value":"Gulf Coast Aquifer System | Jasper"},
	{"label":319,"value":"Gulf Coast Aquifer System | Jefferson"},
	{"label":320,"value":"Gulf Coast Aquifer System | Jim Hogg"},
	{"label":321,"value":"Gulf Coast Aquifer System | Jim Wells"},
	{"label":322,"value":"Gulf Coast Aquifer System | Karnes"},
	{"label":323,"value":"Gulf Coast Aquifer System | Kenedy"},
	{"label":324,"value":"Gulf Coast Aquifer System | Kleberg"},
	{"label":325,"value":"Gulf Coast Aquifer System | Lavaca"},
	{"label":326,"value":"Gulf Coast Aquifer System | Liberty"},
	{"label":327,"value":"Gulf Coast Aquifer System | Live Oak"},
	{"label":328,"value":"Gulf Coast Aquifer System | Matagorda"},
	{"label":329,"value":"Gulf Coast Aquifer System | McMullen"},
	{"label":330,"value":"Gulf Coast Aquifer System | Montgomery"},
	{"label":331,"value":"Gulf Coast Aquifer System | Newton"},
	{"label":332,"value":"Gulf Coast Aquifer System | Nueces"},
	{"label":333,"value":"Gulf Coast Aquifer System | Orange"},
	{"label":334,"value":"Gulf Coast Aquifer System | Polk"},
	{"label":335,"value":"Gulf Coast Aquifer System | Refugio"},
	{"label":337,"value":"Gulf Coast Aquifer System | San Jacinto"},
	{"label":338,"value":"Gulf Coast Aquifer System | San Patricio"},
	{"label":339,"value":"Gulf Coast Aquifer System | Starr"},
	{"label":1104,"value":"Gulf Coast Aquifer System | Trinity"},
	{"label":341,"value":"Gulf Coast Aquifer System | Tyler"},
	{"label":342,"value":"Gulf Coast Aquifer System | Victoria"},
	{"label":343,"value":"Gulf Coast Aquifer System | Walker"},
	{"label":344,"value":"Gulf Coast Aquifer System | Waller"},
	{"label":345,"value":"Gulf Coast Aquifer System | Washington"},
	{"label":346,"value":"Gulf Coast Aquifer System | Webb"},
	{"label":347,"value":"Gulf Coast Aquifer System | Wharton"},
	{"label":348,"value":"Gulf Coast Aquifer System | Willacy"},
	{"label":355,"value":"Gulf of Mexico"},
	{"label":356,"value":"Halbert Lake/Reservoir"},
	{"label":358,"value":"Hickory Aquifer | Blanco"},
	{"label":945,"value":"Hickory Aquifer | Brown"},
	{"label":359,"value":"Hickory Aquifer | Burnet"},
	{"label":946,"value":"Hickory Aquifer | Coleman"},
	{"label":360,"value":"Hickory Aquifer | Concho"},
	{"label":361,"value":"Hickory Aquifer | Gillespie"},
	{"label":1085,"value":"Hickory Aquifer | Hays"},
	{"label":1083,"value":"Hickory Aquifer | Kendall"},
	{"label":947,"value":"Hickory Aquifer | Kimble"},
	{"label":948,"value":"Hickory Aquifer | Lampasas"},
	{"label":362,"value":"Hickory Aquifer | Llano"},
	{"label":363,"value":"Hickory Aquifer | Mason"},
	{"label":364,"value":"Hickory Aquifer | McCulloch"},
	{"label":365,"value":"Hickory Aquifer | Menard"},
	{"label":366,"value":"Hickory Aquifer | Mills"},
	{"label":367,"value":"Hickory Aquifer | San Saba"},
	{"label":950,"value":"Hickory Aquifer | Williamson"},
	{"label":368,"value":"Highland Lakes Lake/Reservoir System"},
	{"label":370,"value":"Hords Creek Lake/Reservoir"},
	{"label":371,"value":"Houston County Lake/Reservoir"},
	{"label":372,"value":"Houston Lake/Reservoir"},
	{"label":373,"value":"Hubbard Creek Lake/Reservoir"},
	{"label":374,"value":"Hubert H Moss Lake/Reservoir"},
	{"label":951,"value":"Hueco-Mesilla Bolson Aquifer ASR | El Paso"},
	{"label":375,"value":"Hueco-Mesilla Bolson Aquifer | El Paso"},
	{"label":376,"value":"Hueco-Mesilla Bolson Aquifer | Hudspeth"},
	{"label":377,"value":"Igneous Aquifer | Brewster"},
	{"label":378,"value":"Igneous Aquifer | Culberson"},
	{"label":379,"value":"Igneous Aquifer | Jeff Davis"},
	{"label":1106,"value":"Igneous Aquifer | Pecos"},
	{"label":380,"value":"Igneous Aquifer | Presidio"},
	{"label":1107,"value":"Igneous Aquifer | Reeves"},
	{"label":391,"value":"Jacksonville Lake/Reservoir"},
	{"label":392,"value":"Joe Pool Lake/Reservoir"},
	{"label":393,"value":"Johnson Creek Lake/Reservoir"},
	{"label":394,"value":"Kemp-Diversion Lake/Reservoir System"},
	{"label":396,"value":"Kirby Lake/Reservoir"},
	{"label":397,"value":"Kurth Lake/Reservoir"},
	{"label":956,"value":"LCRA New Off-Channel Reservoir (2030 Decade)"},
	{"label":398,"value":"Lake 7 (Jim Bertram Lake/Reservoir System)"},
	{"label":399,"value":"Lake Creek Lake/Reservoir"},
	{"label":954,"value":"Lake Davis Lake/Reservoir"},
	{"label":400,"value":"Lake Naconiche Lake/Reservoir"},
	{"label":1135,"value":"Lake Whitney Off-Channel Reservoir"},
	{"label":401,"value":"Langford Lake/Reservoir"},
	{"label":402,"value":"Lavaca River Off-Channel Lake/Reservoir"},
	{"label":662,"value":"Lavaca Run-of-River"},
	{"label":404,"value":"Leon Lake/Reservoir"},
	{"label":958,"value":"Leona Gravel Aquifer | Medina"},
	{"label":959,"value":"Leona Gravel Aquifer | Uvalde"},
	{"label":405,"value":"Lewisville Lake/Reservoir Non-System Portion"},
	{"label":1108,"value":"Lipan Aquifer | Coke"},
	{"label":406,"value":"Lipan Aquifer | Concho"},
	{"label":960,"value":"Lipan Aquifer | Glasscock"},
	{"label":961,"value":"Lipan Aquifer | Irion"},
	{"label":407,"value":"Lipan Aquifer | Runnels"},
	{"label":962,"value":"Lipan Aquifer | Sterling"},
	{"label":408,"value":"Lipan Aquifer | Tom Green"},
	{"label":830,"value":"Little Wichita River Lake/Reservoir System"},
	{"label":410,"value":"Livingston-Wallisville Lake/Reservoir System"},
	{"label":411,"value":"Llano Lake/Reservoir"},
	{"label":412,"value":"Local Surface Water Supply"},
	{"label":413,"value":"Loma Lake/Reservoir"},
	{"label":414,"value":"Lost Creek-Jacksboro Lake/Reservoir System"},
	{"label":963,"value":"Lytle Lake/Reservoir"},
	{"label":416,"value":"Mackenzie Lake/Reservoir"},
	{"label":1128,"value":"Manvel Mustang Bayou Reservoir"},
	{"label":417,"value":"Marathon Aquifer | Brewster"},
	{"label":418,"value":"Marble Falls Aquifer | Blanco"},
	{"label":1109,"value":"Marble Falls Aquifer | Brown"},
	{"label":419,"value":"Marble Falls Aquifer | Burnet"},
	{"label":964,"value":"Marble Falls Aquifer | Kimble"},
	{"label":420,"value":"Marble Falls Aquifer | Lampasas"},
	{"label":421,"value":"Marble Falls Aquifer | Mason"},
	{"label":422,"value":"Marble Falls Aquifer | McCulloch"},
	{"label":1110,"value":"Marble Falls Aquifer | Mills"},
	{"label":423,"value":"Marble Falls Aquifer | San Saba"},
	{"label":424,"value":"Martin Lake/Reservoir"},
	{"label":425,"value":"Marvin Nichols Lake/Reservoir"},
	{"label":965,"value":"McCarty Lake/Reservoir"},
	{"label":426,"value":"Medina Lake/Reservoir"},
	{"label":427,"value":"Meredith Lake/Reservoir"},
	{"label":428,"value":"Mexia Lake/Reservoir"},
	{"label":429,"value":"Mill Creek Lake/Reservoir"},
	{"label":430,"value":"Millers Creek Lake/Reservoir"},
	{"label":432,"value":"Mineral Wells Lake/Reservoir"},
	{"label":433,"value":"Monticello Lake/Reservoir"},
	{"label":967,"value":"Moran Lake/Reservoir"},
	{"label":434,"value":"Mountain Creek Lake/Reservoir | Colorado"},
	{"label":435,"value":"Mountain Creek Lake/Reservoir | Trinity"},
	{"label":436,"value":"Muenster Lake/Reservoir"},
	{"label":437,"value":"Murvaul Lake/Reservoir"},
	{"label":1138,"value":"NCTMWA Lake Creek Lake/Reservoir"},
	{"label":438,"value":"Nacatoch Aquifer | Bowie"},
	{"label":439,"value":"Nacatoch Aquifer | Delta"},
	{"label":968,"value":"Nacatoch Aquifer | Ellis"},
	{"label":440,"value":"Nacatoch Aquifer | Franklin"},
	{"label":442,"value":"Nacatoch Aquifer | Hopkins"},
	{"label":443,"value":"Nacatoch Aquifer | Hunt"},
	{"label":444,"value":"Nacatoch Aquifer | Kaufman"},
	{"label":445,"value":"Nacatoch Aquifer | Lamar"},
	{"label":446,"value":"Nacatoch Aquifer | Navarro"},
	{"label":447,"value":"Nacatoch Aquifer | Rains"},
	{"label":448,"value":"Nacatoch Aquifer | Red River"},
	{"label":449,"value":"Nacatoch Aquifer | Rockwall"},
	{"label":451,"value":"Nacogdoches Lake/Reservoir"},
	{"label":453,"value":"Navarro Mills Lake/Reservoir"},
	{"label":969,"value":"Navasota River Alluvium Aquifer | Grimes"},
	{"label":382,"value":"Neches Indirect Reuse"},
	{"label":663,"value":"Neches Run-of-River"},
	{"label":383,"value":"Neches-Trinity Indirect Reuse"},
	{"label":664,"value":"Neches-Trinity Run-of-River"},
	{"label":1139,"value":"New Marlin City Lake/Reservoir"},
	{"label":1137,"value":"New Throckmorton Lake/Reservoir"},
	{"label":454,"value":"North Fork Buffalo Creek Lake/Reservoir"},
	{"label":1068,"value":"North Texas MWD Lake/Reservoir System"},
	{"label":1129,"value":"Nueces Local Balancing Reservoir"},
	{"label":970,"value":"Nueces River Alluvium Aquifer | Edwards"},
	{"label":971,"value":"Nueces River Alluvium Aquifer | Real"},
	{"label":665,"value":"Nueces Run-of-River"},
	{"label":1064,"value":"Nueces-Rio Grande Indirect Reuse"},
	{"label":666,"value":"Nueces-Rio Grande Run-of-River"},
	{"label":1124,"value":"Nueces-Rio Grande Run-of-River Storage (Banco Morales)"},
	{"label":457,"value":"O' the Pines Lake/Reservoir"},
	{"label":507,"value":"OH Ivie Lake/Reservoir Non-System Portion"},
	{"label":458,"value":"Oak Creek Lake/Reservoir"},
	{"label":1112,"value":"Ogallala Aquifer ASR | Gray"},
	{"label":974,"value":"Ogallala Aquifer ASR | Hale"},
	{"label":977,"value":"Ogallala Aquifer ASR | Lubbock"},
	{"label":1113,"value":"Ogallala Aquifer ASR | Randall"},
	{"label":461,"value":"Ogallala Aquifer | Armstrong"},
	{"label":465,"value":"Ogallala Aquifer | Carson"},
	{"label":1086,"value":"Ogallala Aquifer | Collingsworth"},
	{"label":473,"value":"Ogallala Aquifer | Dickens"},
	{"label":474,"value":"Ogallala Aquifer | Donley"},
	{"label":475,"value":"Ogallala Aquifer | Ector"},
	{"label":479,"value":"Ogallala Aquifer | Glasscock"},
	{"label":480,"value":"Ogallala Aquifer | Gray"},
	{"label":482,"value":"Ogallala Aquifer | Hansford"},
	{"label":484,"value":"Ogallala Aquifer | Hemphill"},
	{"label":487,"value":"Ogallala Aquifer | Hutchinson"},
	{"label":489,"value":"Ogallala Aquifer | Lipscomb"},
	{"label":493,"value":"Ogallala Aquifer | Midland"},
	{"label":494,"value":"Ogallala Aquifer | Moore"},
	{"label":495,"value":"Ogallala Aquifer | Motley"},
	{"label":496,"value":"Ogallala Aquifer | Ochiltree"},
	{"label":497,"value":"Ogallala Aquifer | Oldham"},
	{"label":499,"value":"Ogallala Aquifer | Potter"},
	{"label":500,"value":"Ogallala Aquifer | Randall"},
	{"label":501,"value":"Ogallala Aquifer | Roberts"},
	{"label":502,"value":"Ogallala Aquifer | Sherman"},
	{"label":505,"value":"Ogallala Aquifer | Wheeler"},
	{"label":1111,"value":"Ogallala Aquifer | Winkler"},
	{"label":460,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Andrews"},
	{"label":462,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Bailey"},
	{"label":463,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Borden"},
	{"label":464,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Briscoe"},
	{"label":466,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Castro"},
	{"label":467,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Cochran"},
	{"label":469,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Crosby"},
	{"label":471,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Dawson"},
	{"label":472,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Deaf Smith"},
	{"label":476,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Floyd"},
	{"label":477,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Gaines"},
	{"label":478,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Garza"},
	{"label":931,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Garza"},
	{"label":481,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Hale"},
	{"label":485,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Hockley"},
	{"label":486,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Howard"},
	{"label":488,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Lamb"},
	{"label":490,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Lubbock"},
	{"label":491,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Lynn"},
	{"label":492,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Martin"},
	{"label":498,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Parmer"},
	{"label":503,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Swisher"},
	{"label":504,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Terry"},
	{"label":506,"value":"Ogallala and Edwards-Trinity-High Plains Aquifers | Yoakum"},
	{"label":980,"value":"Ogallala and Rita Blanca Aquifers | Dallam"},
	{"label":981,"value":"Ogallala and Rita Blanca Aquifers | Hartley"},
	{"label":982,"value":"Oklahoma Hugo Lake/Reservoir"},
	{"label":1016,"value":"Oklahoma Run-of-River"},
	{"label":509,"value":"Olney-Cooper Lake/Reservoir System"},
	{"label":510,"value":"Other Aquifer | Anderson"},
	{"label":511,"value":"Other Aquifer | Angelina"},
	{"label":513,"value":"Other Aquifer | Armstrong"},
	{"label":514,"value":"Other Aquifer | Bastrop"},
	{"label":515,"value":"Other Aquifer | Borden"},
	{"label":518,"value":"Other Aquifer | Brewster"},
	{"label":519,"value":"Other Aquifer | Briscoe"},
	{"label":521,"value":"Other Aquifer | Burnet"},
	{"label":984,"value":"Other Aquifer | Cherokee"},
	{"label":522,"value":"Other Aquifer | Childress"},
	{"label":524,"value":"Other Aquifer | Coke"},
	{"label":525,"value":"Other Aquifer | Coleman"},
	{"label":527,"value":"Other Aquifer | Collingsworth"},
	{"label":529,"value":"Other Aquifer | Concho"},
	{"label":531,"value":"Other Aquifer | Cottle"},
	{"label":985,"value":"Other Aquifer | Crosby"},
	{"label":535,"value":"Other Aquifer | Dickens"},
	{"label":536,"value":"Other Aquifer | Donley"},
	{"label":538,"value":"Other Aquifer | El Paso"},
	{"label":540,"value":"Other Aquifer | Fannin"},
	{"label":541,"value":"Other Aquifer | Fayette"},
	{"label":986,"value":"Other Aquifer | Floyd"},
	{"label":987,"value":"Other Aquifer | Foard"},
	{"label":988,"value":"Other Aquifer | Garza"},
	{"label":544,"value":"Other Aquifer | Hall"},
	{"label":990,"value":"Other Aquifer | Hardeman"},
	{"label":545,"value":"Other Aquifer | Henderson"},
	{"label":548,"value":"Other Aquifer | Houston"},
	{"label":549,"value":"Other Aquifer | Hudspeth"},
	{"label":1134,"value":"Other Aquifer | Kent"},
	{"label":555,"value":"Other Aquifer | King"},
	{"label":557,"value":"Other Aquifer | Llano"},
	{"label":1114,"value":"Other Aquifer | Mason"},
	{"label":560,"value":"Other Aquifer | McCulloch"},
	{"label":562,"value":"Other Aquifer | Mitchell"},
	{"label":564,"value":"Other Aquifer | Motley"},
	{"label":565,"value":"Other Aquifer | Nacogdoches"},
	{"label":1115,"value":"Other Aquifer | Navarro"},
	{"label":569,"value":"Other Aquifer | Pecos"},
	{"label":575,"value":"Other Aquifer | Runnels"},
	{"label":991,"value":"Other Aquifer | Rusk"},
	{"label":576,"value":"Other Aquifer | Sabine"},
	{"label":577,"value":"Other Aquifer | San Augustine"},
	{"label":578,"value":"Other Aquifer | Scurry"},
	{"label":579,"value":"Other Aquifer | Shackelford"},
	{"label":580,"value":"Other Aquifer | Smith"},
	{"label":582,"value":"Other Aquifer | Stephens"},
	{"label":1133,"value":"Other Aquifer | Stonewall"},
	{"label":587,"value":"Other Aquifer | Travis"},
	{"label":588,"value":"Other Aquifer | Trinity"},
	{"label":592,"value":"Other Aquifer | Wheeler"},
	{"label":594,"value":"Other Aquifer | Wilbarger"},
	{"label":595,"value":"Other Aquifer | Williamson"},
	{"label":600,"value":"Palestine Lake/Reservoir"},
	{"label":601,"value":"Palo Duro Lake/Reservoir"},
	{"label":602,"value":"Palo Pinto Lake/Reservoir"},
	{"label":603,"value":"Pat Cleburne Lake/Reservoir"},
	{"label":604,"value":"Pat Mayse Lake/Reservoir"},
	{"label":138,"value":"Pecos Valley Aquifer | Andrews"},
	{"label":607,"value":"Pinkston Lake/Reservoir"},
	{"label":608,"value":"Post Lake/Reservoir"},
	{"label":609,"value":"Queen City Aquifer | Anderson"},
	{"label":610,"value":"Queen City Aquifer | Angelina"},
	{"label":611,"value":"Queen City Aquifer | Atascosa"},
	{"label":612,"value":"Queen City Aquifer | Bastrop"},
	{"label":613,"value":"Queen City Aquifer | Brazos"},
	{"label":614,"value":"Queen City Aquifer | Burleson"},
	{"label":615,"value":"Queen City Aquifer | Caldwell"},
	{"label":616,"value":"Queen City Aquifer | Camp"},
	{"label":617,"value":"Queen City Aquifer | Cass"},
	{"label":618,"value":"Queen City Aquifer | Cherokee"},
	{"label":619,"value":"Queen City Aquifer | Fayette"},
	{"label":620,"value":"Queen City Aquifer | Freestone"},
	{"label":621,"value":"Queen City Aquifer | Frio"},
	{"label":622,"value":"Queen City Aquifer | Gonzales"},
	{"label":623,"value":"Queen City Aquifer | Gregg"},
	{"label":624,"value":"Queen City Aquifer | Grimes"},
	{"label":1004,"value":"Queen City Aquifer | Guadalupe"},
	{"label":625,"value":"Queen City Aquifer | Harrison"},
	{"label":626,"value":"Queen City Aquifer | Henderson"},
	{"label":627,"value":"Queen City Aquifer | Houston"},
	{"label":628,"value":"Queen City Aquifer | La Salle"},
	{"label":629,"value":"Queen City Aquifer | Lee"},
	{"label":630,"value":"Queen City Aquifer | Leon"},
	{"label":631,"value":"Queen City Aquifer | Madison"},
	{"label":632,"value":"Queen City Aquifer | Marion"},
	{"label":633,"value":"Queen City Aquifer | McMullen"},
	{"label":634,"value":"Queen City Aquifer | Milam"},
	{"label":635,"value":"Queen City Aquifer | Morris"},
	{"label":636,"value":"Queen City Aquifer | Nacogdoches"},
	{"label":637,"value":"Queen City Aquifer | Robertson"},
	{"label":638,"value":"Queen City Aquifer | Rusk"},
	{"label":639,"value":"Queen City Aquifer | Smith"},
	{"label":1010,"value":"Queen City Aquifer | Titus"},
	{"label":1011,"value":"Queen City Aquifer | Trinity"},
	{"label":640,"value":"Queen City Aquifer | Upshur"},
	{"label":641,"value":"Queen City Aquifer | Van Zandt"},
	{"label":642,"value":"Queen City Aquifer | Walker"},
	{"label":643,"value":"Queen City Aquifer | Wilson"},
	{"label":644,"value":"Queen City Aquifer | Wood"},
	{"label":1067,"value":"Rainwater Harvesting"},
	{"label":646,"value":"Ralph Hall Lake/Reservoir"},
	{"label":647,"value":"Randell Lake/Reservoir"},
	{"label":648,"value":"Ray Hubbard Lake/Reservoir"},
	{"label":649,"value":"Ray Roberts Lake/Reservoir Non-System Portion"},
	{"label":650,"value":"Ray Roberts-Lewisville-Grapevine Lake/Reservoir System"},
	{"label":651,"value":"Red Bluff Lake/Reservoir"},
	{"label":386,"value":"Red Indirect Reuse"},
	{"label":1131,"value":"Red River Off-Channel Reservoir"},
	{"label":667,"value":"Red Run-of-River"},
	{"label":1015,"value":"Regulating Lake/Reservoir"},
	{"label":1075,"value":"Rhines Lake/Reservoir"},
	{"label":652,"value":"Richland Chambers Lake/Reservoir Non-System Portion"},
	{"label":653,"value":"Ringgold Lake/Reservoir"},
	{"label":387,"value":"Rio Grande Indirect Reuse"},
	{"label":668,"value":"Rio Grande Run-of-River"},
	{"label":1081,"value":"Rio Grande Run-of-River Storage"},
	{"label":679,"value":"Rusk City Lake/Reservoir"},
	{"label":1017,"value":"Rustler Aquifer | Brewster"},
	{"label":1116,"value":"Rustler Aquifer | Crane"},
	{"label":680,"value":"Rustler Aquifer | Culberson"},
	{"label":1117,"value":"Rustler Aquifer | Jeff Davis"},
	{"label":1018,"value":"Rustler Aquifer | Loving"},
	{"label":681,"value":"Rustler Aquifer | Pecos"},
	{"label":682,"value":"Rustler Aquifer | Reeves"},
	{"label":1019,"value":"Rustler Aquifer | Ward"},
	{"label":1118,"value":"Rustler Aquifer | Winkler"},
	{"label":1077,"value":"STPNOC Lake/Reservoir"},
	{"label":953,"value":"Sabine Indirect Reuse"},
	{"label":669,"value":"Sabine Run-of-River"},
	{"label":683,"value":"Sam Rayburn-Steinhagen Lake/Reservoir System"},
	{"label":1020,"value":"San Angelo Lakes Lake/Reservoir System"},
	{"label":1125,"value":"San Antonio Indirect Reuse"},
	{"label":670,"value":"San Antonio Run-of-River"},
	{"label":671,"value":"San Antonio-Nueces Run-of-River"},
	{"label":684,"value":"San Augustine Lake/Reservoir"},
	{"label":1021,"value":"San Bernard River Alluvium Aquifer | Austin"},
	{"label":388,"value":"San Jacinto Indirect Reuse"},
	{"label":1022,"value":"San Jacinto River Alluvium Aquifer | Walker"},
	{"label":672,"value":"San Jacinto Run-of-River"},
	{"label":673,"value":"San Jacinto-Brazos Run-of-River"},
	{"label":1119,"value":"San Marcos River Alluvium Aquifer | Caldwell"},
	{"label":1141,"value":"Santa Cruz Lake/Reservoir"},
	{"label":685,"value":"Santa Rosa Lake/Reservoir"},
	{"label":1023,"value":"Seymour Aquifer | Archer"},
	{"label":686,"value":"Seymour Aquifer | Baylor"},
	{"label":687,"value":"Seymour Aquifer | Briscoe"},
	{"label":688,"value":"Seymour Aquifer | Childress"},
	{"label":689,"value":"Seymour Aquifer | Clay"},
	{"label":690,"value":"Seymour Aquifer | Collingsworth"},
	{"label":694,"value":"Seymour Aquifer | Fisher"},
	{"label":695,"value":"Seymour Aquifer | Foard"},
	{"label":696,"value":"Seymour Aquifer | Hall"},
	{"label":697,"value":"Seymour Aquifer | Hardeman"},
	{"label":698,"value":"Seymour Aquifer | Haskell"},
	{"label":699,"value":"Seymour Aquifer | Jones"},
	{"label":700,"value":"Seymour Aquifer | Kent"},
	{"label":701,"value":"Seymour Aquifer | Knox"},
	{"label":702,"value":"Seymour Aquifer | Motley"},
	{"label":1120,"value":"Seymour Aquifer | Scurry"},
	{"label":703,"value":"Seymour Aquifer | Stonewall"},
	{"label":1024,"value":"Seymour Aquifer | Throckmorton"},
	{"label":705,"value":"Seymour Aquifer | Wichita"},
	{"label":706,"value":"Seymour Aquifer | Wilbarger"},
	{"label":1025,"value":"Seymour Aquifer | Young"},
	{"label":1026,"value":"Simsboro Aquifer ASR | Brazos"},
	{"label":708,"value":"Sparta Aquifer | Anderson"},
	{"label":709,"value":"Sparta Aquifer | Angelina"},
	{"label":710,"value":"Sparta Aquifer | Atascosa"},
	{"label":711,"value":"Sparta Aquifer | Bastrop"},
	{"label":712,"value":"Sparta Aquifer | Brazos"},
	{"label":713,"value":"Sparta Aquifer | Burleson"},
	{"label":714,"value":"Sparta Aquifer | Cherokee"},
	{"label":715,"value":"Sparta Aquifer | Fayette"},
	{"label":716,"value":"Sparta Aquifer | Frio"},
	{"label":717,"value":"Sparta Aquifer | Gonzales"},
	{"label":718,"value":"Sparta Aquifer | Grimes"},
	{"label":719,"value":"Sparta Aquifer | Houston"},
	{"label":720,"value":"Sparta Aquifer | La Salle"},
	{"label":721,"value":"Sparta Aquifer | Lee"},
	{"label":722,"value":"Sparta Aquifer | Leon"},
	{"label":723,"value":"Sparta Aquifer | Madison"},
	{"label":724,"value":"Sparta Aquifer | McMullen"},
	{"label":725,"value":"Sparta Aquifer | Nacogdoches"},
	{"label":726,"value":"Sparta Aquifer | Robertson"},
	{"label":727,"value":"Sparta Aquifer | Sabine"},
	{"label":728,"value":"Sparta Aquifer | San Augustine"},
	{"label":729,"value":"Sparta Aquifer | Trinity"},
	{"label":730,"value":"Sparta Aquifer | Walker"},
	{"label":731,"value":"Sparta Aquifer | Wilson"},
	{"label":1036,"value":"Sparta and Queen City Aquifer ASR | Brazos"},
	{"label":732,"value":"Squaw Creek Lake/Reservoir"},
	{"label":733,"value":"Stamford Lake/Reservoir"},
	{"label":1037,"value":"Strawn Lake/Reservoir"},
	{"label":734,"value":"Striker Lake/Reservoir"},
	{"label":389,"value":"Sulphur Indirect Reuse"},
	{"label":674,"value":"Sulphur Run-of-River"},
	{"label":735,"value":"Sulphur Springs Lake/Reservoir"},
	{"label":736,"value":"Sweetwater Lake/Reservoir"},
	{"label":810,"value":"TRWD Lake/Reservoir System"},
	{"label":737,"value":"Tankersley Lake/Reservoir"},
	{"label":738,"value":"Tawakoni Lake/Reservoir"},
	{"label":739,"value":"Teague City Lake/Reservoir"},
	{"label":740,"value":"Tehuacana Lake/Reservoir"},
	{"label":741,"value":"Terrell Lake/Reservoir"},
	{"label":742,"value":"Texana Lake/Reservoir"},
	{"label":744,"value":"Texoma Lake/Reservoir Non-System Portion"},
	{"label":746,"value":"Throckmorton Lake/Reservoir"},
	{"label":747,"value":"Timpson Lake/Reservoir"},
	{"label":748,"value":"Toledo Bend Lake/Reservoir"},
	{"label":1049,"value":"Tradinghouse Creek Lake/Reservoir"},
	{"label":1038,"value":"Trammel Lake/Reservoir"},
	{"label":751,"value":"Trinidad City Lake/Reservoir"},
	{"label":752,"value":"Trinidad Lake/Reservoir"},
	{"label":1041,"value":"Trinity Aquifer ASR | Bandera"},
	{"label":1122,"value":"Trinity Aquifer ASR | Collin"},
	{"label":1042,"value":"Trinity Aquifer ASR | Hays"},
	{"label":1043,"value":"Trinity Aquifer ASR | Johnson"},
	{"label":1044,"value":"Trinity Aquifer ASR | Kerr"},
	{"label":1045,"value":"Trinity Aquifer ASR | McLennan"},
	{"label":1123,"value":"Trinity Aquifer ASR | Tarrant"},
	{"label":1047,"value":"Trinity Aquifer ASR | Williamson"},
	{"label":753,"value":"Trinity Aquifer | Bandera"},
	{"label":755,"value":"Trinity Aquifer | Bell"},
	{"label":756,"value":"Trinity Aquifer | Bexar"},
	{"label":757,"value":"Trinity Aquifer | Blanco"},
	{"label":758,"value":"Trinity Aquifer | Bosque"},
	{"label":759,"value":"Trinity Aquifer | Brown"},
	{"label":760,"value":"Trinity Aquifer | Burnet"},
	{"label":761,"value":"Trinity Aquifer | Caldwell"},
	{"label":762,"value":"Trinity Aquifer | Callahan"},
	{"label":763,"value":"Trinity Aquifer | Collin"},
	{"label":764,"value":"Trinity Aquifer | Comal"},
	{"label":765,"value":"Trinity Aquifer | Comanche"},
	{"label":766,"value":"Trinity Aquifer | Cooke"},
	{"label":767,"value":"Trinity Aquifer | Coryell"},
	{"label":768,"value":"Trinity Aquifer | Dallas"},
	{"label":769,"value":"Trinity Aquifer | Delta"},
	{"label":770,"value":"Trinity Aquifer | Denton"},
	{"label":771,"value":"Trinity Aquifer | Eastland"},
	{"label":772,"value":"Trinity Aquifer | Ellis"},
	{"label":773,"value":"Trinity Aquifer | Erath"},
	{"label":774,"value":"Trinity Aquifer | Falls"},
	{"label":775,"value":"Trinity Aquifer | Fannin"},
	{"label":777,"value":"Trinity Aquifer | Grayson"},
	{"label":1040,"value":"Trinity Aquifer | Guadalupe"},
	{"label":778,"value":"Trinity Aquifer | Hamilton"},
	{"label":779,"value":"Trinity Aquifer | Hays"},
	{"label":780,"value":"Trinity Aquifer | Hill"},
	{"label":781,"value":"Trinity Aquifer | Hood"},
	{"label":782,"value":"Trinity Aquifer | Hunt"},
	{"label":784,"value":"Trinity Aquifer | Johnson"},
	{"label":785,"value":"Trinity Aquifer | Kaufman"},
	{"label":786,"value":"Trinity Aquifer | Kendall"},
	{"label":787,"value":"Trinity Aquifer | Kerr"},
	{"label":788,"value":"Trinity Aquifer | Lamar"},
	{"label":789,"value":"Trinity Aquifer | Lampasas"},
	{"label":1121,"value":"Trinity Aquifer | Lee"},
	{"label":790,"value":"Trinity Aquifer | Limestone"},
	{"label":791,"value":"Trinity Aquifer | McLennan"},
	{"label":792,"value":"Trinity Aquifer | Medina"},
	{"label":793,"value":"Trinity Aquifer | Milam"},
	{"label":794,"value":"Trinity Aquifer | Mills"},
	{"label":795,"value":"Trinity Aquifer | Montague"},
	{"label":796,"value":"Trinity Aquifer | Navarro"},
	{"label":797,"value":"Trinity Aquifer | Palo Pinto"},
	{"label":798,"value":"Trinity Aquifer | Parker"},
	{"label":800,"value":"Trinity Aquifer | Red River"},
	{"label":801,"value":"Trinity Aquifer | Rockwall"},
	{"label":802,"value":"Trinity Aquifer | Somervell"},
	{"label":803,"value":"Trinity Aquifer | Tarrant"},
	{"label":804,"value":"Trinity Aquifer | Taylor"},
	{"label":805,"value":"Trinity Aquifer | Travis"},
	{"label":806,"value":"Trinity Aquifer | Uvalde"},
	{"label":807,"value":"Trinity Aquifer | Williamson"},
	{"label":808,"value":"Trinity Aquifer | Wise"},
	{"label":390,"value":"Trinity Indirect Reuse"},
	{"label":1048,"value":"Trinity River Alluvium Aquifer | Walker"},
	{"label":675,"value":"Trinity Run-of-River"},
	{"label":1039,"value":"Trinity and/or Brackish Edwards Aquifer ASR | Comal"},
	{"label":676,"value":"Trinity-San Jacinto Run-of-River"},
	{"label":811,"value":"Turkey Creek Lake/Reservoir"},
	{"label":812,"value":"Turkey Peak Lake/Reservoir"},
	{"label":814,"value":"Twin Oak Lake/Reservoir"},
	{"label":815,"value":"Tyler Lake/Reservoir"},
	{"label":817,"value":"Victor Braunig Lake/Reservoir"},
	{"label":818,"value":"Waco Lake/Reservoir"},
	{"label":819,"value":"Waxahachie Lake/Reservoir"},
	{"label":821,"value":"Weatherford Lake/Reservoir"},
	{"label":822,"value":"Welsh Lake/Reservoir"},
	{"label":823,"value":"West Texas Bolsons Aquifer | Culberson"},
	{"label":824,"value":"West Texas Bolsons Aquifer | Hudspeth"},
	{"label":825,"value":"West Texas Bolsons Aquifer | Jeff Davis"},
	{"label":826,"value":"West Texas Bolsons Aquifer | Presidio"},
	{"label":827,"value":"Wheeler Branch Off-Channel Lake/Reservoir"},
	{"label":828,"value":"White River Lake/Reservoir"},
	{"label":829,"value":"White Rock Lake/Reservoir"},
	{"label":832,"value":"Winters Lake/Reservoir"},
	{"label":833,"value":"Woodbine Aquifer | Collin"},
	{"label":834,"value":"Woodbine Aquifer | Cooke"},
	{"label":835,"value":"Woodbine Aquifer | Dallas"},
	{"label":837,"value":"Woodbine Aquifer | Denton"},
	{"label":838,"value":"Woodbine Aquifer | Ellis"},
	{"label":839,"value":"Woodbine Aquifer | Fannin"},
	{"label":840,"value":"Woodbine Aquifer | Grayson"},
	{"label":841,"value":"Woodbine Aquifer | Hill"},
	{"label":842,"value":"Woodbine Aquifer | Hunt"},
	{"label":843,"value":"Woodbine Aquifer | Johnson"},
	{"label":844,"value":"Woodbine Aquifer | Kaufman"},
	{"label":845,"value":"Woodbine Aquifer | Lamar"},
	{"label":847,"value":"Woodbine Aquifer | McLennan"},
	{"label":848,"value":"Woodbine Aquifer | Navarro"},
	{"label":850,"value":"Woodbine Aquifer | Red River"},
	{"label":851,"value":"Woodbine Aquifer | Rockwall"},
	{"label":852,"value":"Woodbine Aquifer | Tarrant"},
	{"label":1054,"value":"Woodson Lake/Reservoir"},
	{"label":854,"value":"Wright Patman Lake/Reservoir"},
	{"label":855,"value":"Yegua-Jackson Aquifer | Angelina"},
	{"label":1055,"value":"Yegua-Jackson Aquifer | Atascosa"},
	{"label":856,"value":"Yegua-Jackson Aquifer | Brazos"},
	{"label":857,"value":"Yegua-Jackson Aquifer | Burleson"},
	{"label":858,"value":"Yegua-Jackson Aquifer | Fayette"},
	{"label":1057,"value":"Yegua-Jackson Aquifer | Gonzales"},
	{"label":859,"value":"Yegua-Jackson Aquifer | Grimes"},
	{"label":860,"value":"Yegua-Jackson Aquifer | Houston"},
	{"label":1058,"value":"Yegua-Jackson Aquifer | Karnes"},
	{"label":1059,"value":"Yegua-Jackson Aquifer | La Salle"},
	{"label":862,"value":"Yegua-Jackson Aquifer | Lee"},
	{"label":1060,"value":"Yegua-Jackson Aquifer | Leon"},
	{"label":1061,"value":"Yegua-Jackson Aquifer | Madison"},
	{"label":863,"value":"Yegua-Jackson Aquifer | Nacogdoches"},
	{"label":864,"value":"Yegua-Jackson Aquifer | Polk"},
	{"label":865,"value":"Yegua-Jackson Aquifer | Sabine"},
	{"label":866,"value":"Yegua-Jackson Aquifer | San Augustine"},
	{"label":867,"value":"Yegua-Jackson Aquifer | Starr"},
	{"label":868,"value":"Yegua-Jackson Aquifer | Trinity"},
	{"label":870,"value":"Yegua-Jackson Aquifer | Walker"},
	{"label":871,"value":"Yegua-Jackson Aquifer | Washington"},
	{"label":872,"value":"Yegua-Jackson Aquifer | Webb"},
	{"label":1063,"value":"Yegua-Jackson Aquifer | Wilson"},
	{"label":873,"value":"Yegua-Jackson Aquifer | Zapata"}
];