export const sourceNames = [
	{"value":1,"label":"Abilene Lake/Reservoir"},
	{"value":2,"label":"Alan Henry Lake/Reservoir"},
	{"value":3,"label":"Alcoa Lake/Reservoir"},
	{"value":4,"label":"Allens Creek Lake/Reservoir"},
	{"value":5,"label":"Alvarado Lake/Reservoir"},
	{"value":6,"label":"Amistad-Falcon Lake/Reservoir System"},
	{"value":7,"label":"Amon G. Carter Lake/Reservoir"},
	{"value":884,"label":"Anson North Lake/Reservoir"},
	{"value":9,"label":"Athens Lake/Reservoir"},
	{"value":820,"label":"Atmosphere"},
	{"value":885,"label":"Austin Chalk Aquifer | Kinney"},
	{"value":886,"label":"Austin Chalk Aquifer | Uvalde"},
	{"value":1079,"label":"Austin Off-Channel Lake/Reservoir"},
	{"value":1076,"label":"BRA System Operations Permit Supply"},
	{"value":887,"label":"Baird Lake/Reservoir"},
	{"value":10,"label":"Ballinger/Moonen Lake/Reservoir"},
	{"value":11,"label":"Balmorhea Lake/Reservoir"},
	{"value":12,"label":"Bardwell Lake/Reservoir"},
	{"value":888,"label":"Baylor Creek Lake/Reservoir"},
	{"value":1132,"label":"Beaumont West Regional Lake/Reservoir"},
	{"value":14,"label":"Bellwood Lake/Reservoir"},
	{"value":15,"label":"Big Creek Lake/Reservoir"},
	{"value":16,"label":"Big Sandy Creek Lake/Reservoir"},
	{"value":17,"label":"Blaine Aquifer | Childress"},
	{"value":18,"label":"Blaine Aquifer | Collingsworth"},
	{"value":19,"label":"Blaine Aquifer | Cottle"},
	{"value":20,"label":"Blaine Aquifer | Fisher"},
	{"value":21,"label":"Blaine Aquifer | Foard"},
	{"value":22,"label":"Blaine Aquifer | Hall"},
	{"value":23,"label":"Blaine Aquifer | Hardeman"},
	{"value":24,"label":"Blaine Aquifer | King"},
	{"value":25,"label":"Blaine Aquifer | Knox"},
	{"value":26,"label":"Blaine Aquifer | Nolan"},
	{"value":27,"label":"Blaine Aquifer | Stonewall"},
	{"value":28,"label":"Blaine Aquifer | Wheeler"},
	{"value":29,"label":"Blanco Lake/Reservoir"},
	{"value":30,"label":"Blossom Aquifer | Bowie"},
	{"value":31,"label":"Blossom Aquifer | Lamar"},
	{"value":32,"label":"Blossom Aquifer | Red River"},
	{"value":33,"label":"Bob Sandlin Lake/Reservoir"},
	{"value":34,"label":"Boerne Lake/Reservoir"},
	{"value":415,"label":"Bois D'Arc Lake/Reservoir"},
	{"value":35,"label":"Bone Spring-Victorio Peak Aquifer | Hudspeth"},
	{"value":36,"label":"Bonham Lake/Reservoir"},
	{"value":37,"label":"Brady Creek Lake/Reservoir"},
	{"value":38,"label":"Brandy Branch Lake/Reservoir"},
	{"value":952,"label":"Brazos Indirect Reuse"},
	{"value":40,"label":"Brazos River Alluvium Aquifer | Austin"},
	{"value":41,"label":"Brazos River Alluvium Aquifer | Bosque"},
	{"value":42,"label":"Brazos River Alluvium Aquifer | Brazos"},
	{"value":43,"label":"Brazos River Alluvium Aquifer | Burleson"},
	{"value":44,"label":"Brazos River Alluvium Aquifer | Falls"},
	{"value":46,"label":"Brazos River Alluvium Aquifer | Grimes"},
	{"value":47,"label":"Brazos River Alluvium Aquifer | Hill"},
	{"value":48,"label":"Brazos River Alluvium Aquifer | McLennan"},
	{"value":49,"label":"Brazos River Alluvium Aquifer | Milam"},
	{"value":50,"label":"Brazos River Alluvium Aquifer | Robertson"},
	{"value":51,"label":"Brazos River Alluvium Aquifer | Waller"},
	{"value":52,"label":"Brazos River Alluvium Aquifer | Washington"},
	{"value":53,"label":"Brazos River Authority Aquilla Lake/Reservoir System"},
	{"value":54,"label":"Brazos River Authority Little River Lake/Reservoir System"},
	{"value":55,"label":"Brazos River Authority Main Stem Lake/Reservoir System"},
	{"value":655,"label":"Brazos Run-of-River"},
	{"value":656,"label":"Brazos-Colorado Run-of-River"},
	{"value":57,"label":"Brownwood Lake/Reservoir"},
	{"value":59,"label":"Brushy Creek Lake/Reservoir"},
	{"value":60,"label":"Bryson Lake/Reservoir"},
	{"value":889,"label":"Buda Limestone Aquifer | Uvalde"},
	{"value":897,"label":"CRMWD Diverted Water System"},
	{"value":61,"label":"Caddo Lake/Reservoir"},
	{"value":62,"label":"Calaveras Lake/Reservoir"},
	{"value":657,"label":"Canadian Run-of-River"},
	{"value":63,"label":"Caney Creek Lake/Reservoir"},
	{"value":64,"label":"Canyon Lake/Reservoir"},
	{"value":65,"label":"Capitan Reef Complex Aquifer | Brewster"},
	{"value":66,"label":"Capitan Reef Complex Aquifer | Culberson"},
	{"value":67,"label":"Capitan Reef Complex Aquifer | Hudspeth"},
	{"value":1087,"label":"Capitan Reef Complex Aquifer | Jeff Davis"},
	{"value":68,"label":"Capitan Reef Complex Aquifer | Pecos"},
	{"value":890,"label":"Capitan Reef Complex Aquifer | Reeves"},
	{"value":69,"label":"Capitan Reef Complex Aquifer | Ward"},
	{"value":70,"label":"Capitan Reef Complex Aquifer | Winkler"},
	{"value":1088,"label":"Carrizo-Aquifer ASR | Bexar"},
	{"value":892,"label":"Carrizo-Wilcox Aquifer ASR | Bastrop"},
	{"value":1066,"label":"Carrizo-Wilcox Aquifer ASR | Gonzales"},
	{"value":1089,"label":"Carrizo-Wilcox Aquifer ASR | Maverick"},
	{"value":71,"label":"Carrizo-Wilcox Aquifer | Anderson"},
	{"value":72,"label":"Carrizo-Wilcox Aquifer | Angelina"},
	{"value":73,"label":"Carrizo-Wilcox Aquifer | Atascosa"},
	{"value":74,"label":"Carrizo-Wilcox Aquifer | Bastrop"},
	{"value":76,"label":"Carrizo-Wilcox Aquifer | Bexar"},
	{"value":77,"label":"Carrizo-Wilcox Aquifer | Bowie"},
	{"value":78,"label":"Carrizo-Wilcox Aquifer | Brazos"},
	{"value":79,"label":"Carrizo-Wilcox Aquifer | Burleson"},
	{"value":80,"label":"Carrizo-Wilcox Aquifer | Caldwell"},
	{"value":81,"label":"Carrizo-Wilcox Aquifer | Camp"},
	{"value":82,"label":"Carrizo-Wilcox Aquifer | Cass"},
	{"value":83,"label":"Carrizo-Wilcox Aquifer | Cherokee"},
	{"value":84,"label":"Carrizo-Wilcox Aquifer | Dimmit"},
	{"value":85,"label":"Carrizo-Wilcox Aquifer | Falls"},
	{"value":86,"label":"Carrizo-Wilcox Aquifer | Fayette"},
	{"value":87,"label":"Carrizo-Wilcox Aquifer | Franklin"},
	{"value":88,"label":"Carrizo-Wilcox Aquifer | Freestone"},
	{"value":89,"label":"Carrizo-Wilcox Aquifer | Frio"},
	{"value":90,"label":"Carrizo-Wilcox Aquifer | Gonzales"},
	{"value":91,"label":"Carrizo-Wilcox Aquifer | Gregg"},
	{"value":92,"label":"Carrizo-Wilcox Aquifer | Grimes"},
	{"value":93,"label":"Carrizo-Wilcox Aquifer | Guadalupe"},
	{"value":94,"label":"Carrizo-Wilcox Aquifer | Harrison"},
	{"value":95,"label":"Carrizo-Wilcox Aquifer | Henderson"},
	{"value":96,"label":"Carrizo-Wilcox Aquifer | Hopkins"},
	{"value":97,"label":"Carrizo-Wilcox Aquifer | Houston"},
	{"value":99,"label":"Carrizo-Wilcox Aquifer | Karnes"},
	{"value":100,"label":"Carrizo-Wilcox Aquifer | La Salle"},
	{"value":101,"label":"Carrizo-Wilcox Aquifer | Lee"},
	{"value":102,"label":"Carrizo-Wilcox Aquifer | Leon"},
	{"value":103,"label":"Carrizo-Wilcox Aquifer | Limestone"},
	{"value":105,"label":"Carrizo-Wilcox Aquifer | Madison"},
	{"value":106,"label":"Carrizo-Wilcox Aquifer | Marion"},
	{"value":107,"label":"Carrizo-Wilcox Aquifer | Maverick"},
	{"value":108,"label":"Carrizo-Wilcox Aquifer | McMullen"},
	{"value":109,"label":"Carrizo-Wilcox Aquifer | Medina"},
	{"value":110,"label":"Carrizo-Wilcox Aquifer | Milam"},
	{"value":111,"label":"Carrizo-Wilcox Aquifer | Morris"},
	{"value":112,"label":"Carrizo-Wilcox Aquifer | Nacogdoches"},
	{"value":113,"label":"Carrizo-Wilcox Aquifer | Navarro"},
	{"value":114,"label":"Carrizo-Wilcox Aquifer | Panola"},
	{"value":115,"label":"Carrizo-Wilcox Aquifer | Rains"},
	{"value":116,"label":"Carrizo-Wilcox Aquifer | Red River"},
	{"value":117,"label":"Carrizo-Wilcox Aquifer | Robertson"},
	{"value":118,"label":"Carrizo-Wilcox Aquifer | Rusk"},
	{"value":119,"label":"Carrizo-Wilcox Aquifer | Sabine"},
	{"value":120,"label":"Carrizo-Wilcox Aquifer | San Augustine"},
	{"value":121,"label":"Carrizo-Wilcox Aquifer | Shelby"},
	{"value":122,"label":"Carrizo-Wilcox Aquifer | Smith"},
	{"value":123,"label":"Carrizo-Wilcox Aquifer | Titus"},
	{"value":124,"label":"Carrizo-Wilcox Aquifer | Trinity"},
	{"value":125,"label":"Carrizo-Wilcox Aquifer | Upshur"},
	{"value":126,"label":"Carrizo-Wilcox Aquifer | Uvalde"},
	{"value":127,"label":"Carrizo-Wilcox Aquifer | Van Zandt"},
	{"value":128,"label":"Carrizo-Wilcox Aquifer | Walker"},
	{"value":129,"label":"Carrizo-Wilcox Aquifer | Webb"},
	{"value":891,"label":"Carrizo-Wilcox Aquifer | Williamson"},
	{"value":130,"label":"Carrizo-Wilcox Aquifer | Wilson"},
	{"value":131,"label":"Carrizo-Wilcox Aquifer | Wood"},
	{"value":132,"label":"Carrizo-Wilcox Aquifer | Zavala"},
	{"value":137,"label":"Cedar Ridge Lake/Reservoir"},
	{"value":147,"label":"Center Lake/Reservoir"},
	{"value":148,"label":"Chapman/Cooper Lake/Reservoir Non-System Portion"},
	{"value":150,"label":"Cherokee Lake/Reservoir"},
	{"value":151,"label":"Cisco Lake/Reservoir"},
	{"value":894,"label":"City of Hamlin Lake/Reservoir"},
	{"value":152,"label":"Clark Lake/Reservoir"},
	{"value":895,"label":"Clifton Lake/Reservoir"},
	{"value":153,"label":"Clyde Lake/Reservoir"},
	{"value":155,"label":"Coleman Lake/Reservoir"},
	{"value":156,"label":"Coleto Creek Lake/Reservoir"},
	{"value":157,"label":"Colorado City-Champion Lake/Reservoir System"},
	{"value":381,"label":"Colorado Indirect Reuse"},
	{"value":158,"label":"Colorado River MWD Lake/Reservoir System"},
	{"value":658,"label":"Colorado Run-of-River"},
	{"value":659,"label":"Colorado-Lavaca Run-of-River"},
	{"value":159,"label":"Columbia Lake/Reservoir"},
	{"value":160,"label":"Conroe Lake/Reservoir"},
	{"value":162,"label":"Coolidge Lake/Reservoir"},
	{"value":163,"label":"Corpus Christi-Choke Canyon Lake/Reservoir System"},
	{"value":164,"label":"Coryell County Off-Channel Lake/Reservoir"},
	{"value":896,"label":"Crawford Lake/Reservoir"},
	{"value":165,"label":"Crook Lake/Reservoir"},
	{"value":1090,"label":"Cross Timbers Aquifer | Archer"},
	{"value":1091,"label":"Cross Timbers Aquifer | Baylor"},
	{"value":1070,"label":"Cross Timbers Aquifer | Brown"},
	{"value":1092,"label":"Cross Timbers Aquifer | Clay"},
	{"value":1093,"label":"Cross Timbers Aquifer | Coleman"},
	{"value":1071,"label":"Cross Timbers Aquifer | Jack"},
	{"value":1094,"label":"Cross Timbers Aquifer | McCulloch"},
	{"value":1095,"label":"Cross Timbers Aquifer | Montague"},
	{"value":1072,"label":"Cross Timbers Aquifer | Parker"},
	{"value":1096,"label":"Cross Timbers Aquifer | Shackelford"},
	{"value":1097,"label":"Cross Timbers Aquifer | Stephens"},
	{"value":1073,"label":"Cross Timbers Aquifer | Throckmorton"},
	{"value":1098,"label":"Cross Timbers Aquifer | Wichita"},
	{"value":1074,"label":"Cross Timbers Aquifer | Young"},
	{"value":1099,"label":"Cross Timbers Aquifer | Young"},
	{"value":660,"label":"Cypress Run-of-River"},
	{"value":166,"label":"Cypress Springs Lake/Reservoir"},
	{"value":167,"label":"Daniel Lake/Reservoir"},
	{"value":168,"label":"Dansby Power Plant/Bryan Utilities Lake/Reservoir"},
	{"value":1140,"label":"Delta Panchita Lake/Reservoir"},
	{"value":898,"label":"Dimple Lake/Reservoir"},
	{"value":169,"label":"Direct Reuse"},
	{"value":170,"label":"Dockum Aquifer | Andrews"},
	{"value":171,"label":"Dockum Aquifer | Armstrong"},
	{"value":899,"label":"Dockum Aquifer | Bailey"},
	{"value":172,"label":"Dockum Aquifer | Borden"},
	{"value":173,"label":"Dockum Aquifer | Briscoe"},
	{"value":174,"label":"Dockum Aquifer | Carson"},
	{"value":900,"label":"Dockum Aquifer | Castro"},
	{"value":901,"label":"Dockum Aquifer | Cochran"},
	{"value":1100,"label":"Dockum Aquifer | Coke"},
	{"value":176,"label":"Dockum Aquifer | Crane"},
	{"value":902,"label":"Dockum Aquifer | Crockett"},
	{"value":903,"label":"Dockum Aquifer | Crosby"},
	{"value":177,"label":"Dockum Aquifer | Dallam"},
	{"value":178,"label":"Dockum Aquifer | Deaf Smith"},
	{"value":905,"label":"Dockum Aquifer | Dickens"},
	{"value":179,"label":"Dockum Aquifer | Ector"},
	{"value":180,"label":"Dockum Aquifer | Fisher"},
	{"value":906,"label":"Dockum Aquifer | Floyd"},
	{"value":907,"label":"Dockum Aquifer | Gaines"},
	{"value":181,"label":"Dockum Aquifer | Garza"},
	{"value":182,"label":"Dockum Aquifer | Glasscock"},
	{"value":908,"label":"Dockum Aquifer | Hale"},
	{"value":183,"label":"Dockum Aquifer | Hartley"},
	{"value":909,"label":"Dockum Aquifer | Hockley"},
	{"value":184,"label":"Dockum Aquifer | Howard"},
	{"value":910,"label":"Dockum Aquifer | Irion"},
	{"value":185,"label":"Dockum Aquifer | Kent"},
	{"value":911,"label":"Dockum Aquifer | Lamb"},
	{"value":186,"label":"Dockum Aquifer | Loving"},
	{"value":912,"label":"Dockum Aquifer | Lubbock"},
	{"value":913,"label":"Dockum Aquifer | Lynn"},
	{"value":914,"label":"Dockum Aquifer | Martin"},
	{"value":187,"label":"Dockum Aquifer | Midland"},
	{"value":188,"label":"Dockum Aquifer | Mitchell"},
	{"value":189,"label":"Dockum Aquifer | Moore"},
	{"value":915,"label":"Dockum Aquifer | Motley"},
	{"value":190,"label":"Dockum Aquifer | Nolan"},
	{"value":191,"label":"Dockum Aquifer | Oldham"},
	{"value":916,"label":"Dockum Aquifer | Parmer"},
	{"value":192,"label":"Dockum Aquifer | Pecos"},
	{"value":193,"label":"Dockum Aquifer | Potter"},
	{"value":194,"label":"Dockum Aquifer | Randall"},
	{"value":195,"label":"Dockum Aquifer | Reagan"},
	{"value":196,"label":"Dockum Aquifer | Reeves"},
	{"value":197,"label":"Dockum Aquifer | Scurry"},
	{"value":198,"label":"Dockum Aquifer | Sherman"},
	{"value":917,"label":"Dockum Aquifer | Sterling"},
	{"value":199,"label":"Dockum Aquifer | Swisher"},
	{"value":1101,"label":"Dockum Aquifer | Tom Green"},
	{"value":201,"label":"Dockum Aquifer | Upton"},
	{"value":202,"label":"Dockum Aquifer | Ward"},
	{"value":203,"label":"Dockum Aquifer | Winkler"},
	{"value":1127,"label":"Dow Harris Reservoir Expansion"},
	{"value":274,"label":"EV Spence Lake/Reservoir Non-System Portion"},
	{"value":919,"label":"Eastland Lake/Reservoir"},
	{"value":206,"label":"Edgewood City Lake/Reservoir"},
	{"value":1136,"label":"Edwards-BFZ Aquifer (Saline Portion) ASR | Travis"},
	{"value":207,"label":"Edwards-BFZ Aquifer | Atascosa"},
	{"value":208,"label":"Edwards-BFZ Aquifer | Bell"},
	{"value":209,"label":"Edwards-BFZ Aquifer | Bexar"},
	{"value":923,"label":"Edwards-BFZ Aquifer | Caldwell"},
	{"value":210,"label":"Edwards-BFZ Aquifer | Comal"},
	{"value":924,"label":"Edwards-BFZ Aquifer | Frio"},
	{"value":211,"label":"Edwards-BFZ Aquifer | Guadalupe"},
	{"value":212,"label":"Edwards-BFZ Aquifer | Hays"},
	{"value":213,"label":"Edwards-BFZ Aquifer | Kinney"},
	{"value":214,"label":"Edwards-BFZ Aquifer | Medina"},
	{"value":215,"label":"Edwards-BFZ Aquifer | Travis"},
	{"value":216,"label":"Edwards-BFZ Aquifer | Uvalde"},
	{"value":217,"label":"Edwards-BFZ Aquifer | Williamson"},
	{"value":141,"label":"Edwards-Trinity-Plateau And Pecos Valley Aquifers | Loving"},
	{"value":145,"label":"Edwards-Trinity-Plateau And Pecos Valley Aquifers | Ward"},
	{"value":220,"label":"Edwards-Trinity-Plateau Aquifer | Andrews"},
	{"value":221,"label":"Edwards-Trinity-Plateau Aquifer | Bandera"},
	{"value":1084,"label":"Edwards-Trinity-Plateau Aquifer | Blanco"},
	{"value":223,"label":"Edwards-Trinity-Plateau Aquifer | Brewster"},
	{"value":228,"label":"Edwards-Trinity-Plateau Aquifer | Culberson"},
	{"value":233,"label":"Edwards-Trinity-Plateau Aquifer | Howard"},
	{"value":236,"label":"Edwards-Trinity-Plateau Aquifer | Kendall"},
	{"value":237,"label":"Edwards-Trinity-Plateau Aquifer | Kerr"},
	{"value":240,"label":"Edwards-Trinity-Plateau Aquifer | Martin"},
	{"value":1130,"label":"Edwards-Trinity-Plateau and Pecos Valley Aquifers ASR | Reeves"},
	{"value":999,"label":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Crane"},
	{"value":235,"label":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Jeff Davis"},
	{"value":1000,"label":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Pecos"},
	{"value":1001,"label":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Reeves"},
	{"value":1002,"label":"Edwards-Trinity-Plateau and Pecos Valley Aquifers | Winkler"},
	{"value":224,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Coke"},
	{"value":225,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Concho"},
	{"value":227,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Crockett"},
	{"value":229,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Ector"},
	{"value":230,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Edwards"},
	{"value":231,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Gillespie"},
	{"value":232,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Glasscock"},
	{"value":234,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Irion"},
	{"value":238,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Kimble"},
	{"value":239,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Kinney"},
	{"value":241,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Mason"},
	{"value":242,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | McCulloch"},
	{"value":243,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Menard"},
	{"value":244,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Midland"},
	{"value":245,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Nolan"},
	{"value":246,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Pecos"},
	{"value":247,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Reagan"},
	{"value":248,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Real"},
	{"value":250,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Schleicher"},
	{"value":251,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Sterling"},
	{"value":252,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Sutton"},
	{"value":253,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Taylor"},
	{"value":254,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Terrell"},
	{"value":255,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Tom Green"},
	{"value":256,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Upton"},
	{"value":257,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Uvalde"},
	{"value":258,"label":"Edwards-Trinity-Plateau, Pecos Valley, and Trinity Aquifers | Val Verde"},
	{"value":260,"label":"Electra City Lake/Reservoir"},
	{"value":261,"label":"Ellenburger-San Saba Aquifer | Blanco"},
	{"value":938,"label":"Ellenburger-San Saba Aquifer | Brown"},
	{"value":262,"label":"Ellenburger-San Saba Aquifer | Burnet"},
	{"value":263,"label":"Ellenburger-San Saba Aquifer | Gillespie"},
	{"value":1082,"label":"Ellenburger-San Saba Aquifer | Kendall"},
	{"value":937,"label":"Ellenburger-San Saba Aquifer | Kerr"},
	{"value":264,"label":"Ellenburger-San Saba Aquifer | Kimble"},
	{"value":265,"label":"Ellenburger-San Saba Aquifer | Lampasas"},
	{"value":266,"label":"Ellenburger-San Saba Aquifer | Llano"},
	{"value":267,"label":"Ellenburger-San Saba Aquifer | Mason"},
	{"value":268,"label":"Ellenburger-San Saba Aquifer | McCulloch"},
	{"value":269,"label":"Ellenburger-San Saba Aquifer | Menard"},
	{"value":270,"label":"Ellenburger-San Saba Aquifer | Mills"},
	{"value":271,"label":"Ellenburger-San Saba Aquifer | San Saba"},
	{"value":272,"label":"Elliot Creek Lake/Reservoir"},
	{"value":273,"label":"Ellison Creek Lake/Reservoir"},
	{"value":1142,"label":"Engleman Lake/Reservoir"},
	{"value":275,"label":"Fairfield Lake/Reservoir"},
	{"value":276,"label":"Farmers Creek/Nocona Lake/Reservoir"},
	{"value":278,"label":"Forest Grove Lake/Reservoir"},
	{"value":279,"label":"Fork Lake/Reservoir"},
	{"value":281,"label":"Fort Phantom Hill Lake/Reservoir"},
	{"value":1069,"label":"Frio River Alluvium Aquifer | Real"},
	{"value":1126,"label":"GBRA Lower Basin New Appropriation Off-Channel Reservoir"},
	{"value":879,"label":"GBRA Lower Basin Off-Channel Lake/Reservoir"},
	{"value":283,"label":"George Parkhouse North Lake/Reservoir"},
	{"value":284,"label":"George Parkhouse South Lake/Reservoir"},
	{"value":285,"label":"Gibbons Creek Lake/Reservoir"},
	{"value":287,"label":"Gilmer Lake/Reservoir"},
	{"value":288,"label":"Gladewater Lake/Reservoir"},
	{"value":289,"label":"Goldthwaite Lake/Reservoir"},
	{"value":940,"label":"Gordon Lake/Reservoir"},
	{"value":290,"label":"Graham/Eddleman Lake/Reservoir"},
	{"value":291,"label":"Grand Saline Lake/Reservoir"},
	{"value":292,"label":"Grapevine Lake/Reservoir Non-System Portion"},
	{"value":293,"label":"Greenbelt Lake/Reservoir"},
	{"value":294,"label":"Greenville City Lake/Reservoir"},
	{"value":295,"label":"Groesbeck Off-Channel Lake/Reservoir"},
	{"value":942,"label":"Guadalupe River Off-Channel Lake/Reservoir"},
	{"value":661,"label":"Guadalupe Run-of-River"},
	{"value":943,"label":"Gulf Coast Aquifer ASR | Jackson"},
	{"value":1103,"label":"Gulf Coast Aquifer ASR | Montgomery"},
	{"value":944,"label":"Gulf Coast Aquifer ASR | Victoria"},
	{"value":1105,"label":"Gulf Coast Aquifer System ASR (Corpus Christi) | Nueces"},
	{"value":296,"label":"Gulf Coast Aquifer System | Aransas"},
	{"value":297,"label":"Gulf Coast Aquifer System | Austin"},
	{"value":298,"label":"Gulf Coast Aquifer System | Bee"},
	{"value":299,"label":"Gulf Coast Aquifer System | Brazoria"},
	{"value":300,"label":"Gulf Coast Aquifer System | Brazos"},
	{"value":301,"label":"Gulf Coast Aquifer System | Brooks"},
	{"value":302,"label":"Gulf Coast Aquifer System | Calhoun"},
	{"value":303,"label":"Gulf Coast Aquifer System | Cameron"},
	{"value":304,"label":"Gulf Coast Aquifer System | Chambers"},
	{"value":305,"label":"Gulf Coast Aquifer System | Colorado"},
	{"value":306,"label":"Gulf Coast Aquifer System | DeWitt"},
	{"value":307,"label":"Gulf Coast Aquifer System | Duval"},
	{"value":308,"label":"Gulf Coast Aquifer System | Fayette"},
	{"value":309,"label":"Gulf Coast Aquifer System | Fort Bend"},
	{"value":310,"label":"Gulf Coast Aquifer System | Galveston"},
	{"value":311,"label":"Gulf Coast Aquifer System | Goliad"},
	{"value":312,"label":"Gulf Coast Aquifer System | Gonzales"},
	{"value":313,"label":"Gulf Coast Aquifer System | Grimes"},
	{"value":314,"label":"Gulf Coast Aquifer System | Hardin"},
	{"value":315,"label":"Gulf Coast Aquifer System | Harris"},
	{"value":316,"label":"Gulf Coast Aquifer System | Hidalgo"},
	{"value":317,"label":"Gulf Coast Aquifer System | Jackson"},
	{"value":318,"label":"Gulf Coast Aquifer System | Jasper"},
	{"value":319,"label":"Gulf Coast Aquifer System | Jefferson"},
	{"value":320,"label":"Gulf Coast Aquifer System | Jim Hogg"},
	{"value":321,"label":"Gulf Coast Aquifer System | Jim Wells"},
	{"value":322,"label":"Gulf Coast Aquifer System | Karnes"},
	{"value":323,"label":"Gulf Coast Aquifer System | Kenedy"},
	{"value":324,"label":"Gulf Coast Aquifer System | Kleberg"},
	{"value":325,"label":"Gulf Coast Aquifer System | Lavaca"},
	{"value":326,"label":"Gulf Coast Aquifer System | Liberty"},
	{"value":327,"label":"Gulf Coast Aquifer System | Live Oak"},
	{"value":328,"label":"Gulf Coast Aquifer System | Matagorda"},
	{"value":329,"label":"Gulf Coast Aquifer System | McMullen"},
	{"value":330,"label":"Gulf Coast Aquifer System | Montgomery"},
	{"value":331,"label":"Gulf Coast Aquifer System | Newton"},
	{"value":332,"label":"Gulf Coast Aquifer System | Nueces"},
	{"value":333,"label":"Gulf Coast Aquifer System | Orange"},
	{"value":334,"label":"Gulf Coast Aquifer System | Polk"},
	{"value":335,"label":"Gulf Coast Aquifer System | Refugio"},
	{"value":337,"label":"Gulf Coast Aquifer System | San Jacinto"},
	{"value":338,"label":"Gulf Coast Aquifer System | San Patricio"},
	{"value":339,"label":"Gulf Coast Aquifer System | Starr"},
	{"value":1104,"label":"Gulf Coast Aquifer System | Trinity"},
	{"value":341,"label":"Gulf Coast Aquifer System | Tyler"},
	{"value":342,"label":"Gulf Coast Aquifer System | Victoria"},
	{"value":343,"label":"Gulf Coast Aquifer System | Walker"},
	{"value":344,"label":"Gulf Coast Aquifer System | Waller"},
	{"value":345,"label":"Gulf Coast Aquifer System | Washington"},
	{"value":346,"label":"Gulf Coast Aquifer System | Webb"},
	{"value":347,"label":"Gulf Coast Aquifer System | Wharton"},
	{"value":348,"label":"Gulf Coast Aquifer System | Willacy"},
	{"value":355,"label":"Gulf of Mexico"},
	{"value":356,"label":"Halbert Lake/Reservoir"},
	{"value":358,"label":"Hickory Aquifer | Blanco"},
	{"value":945,"label":"Hickory Aquifer | Brown"},
	{"value":359,"label":"Hickory Aquifer | Burnet"},
	{"value":946,"label":"Hickory Aquifer | Coleman"},
	{"value":360,"label":"Hickory Aquifer | Concho"},
	{"value":361,"label":"Hickory Aquifer | Gillespie"},
	{"value":1085,"label":"Hickory Aquifer | Hays"},
	{"value":1083,"label":"Hickory Aquifer | Kendall"},
	{"value":947,"label":"Hickory Aquifer | Kimble"},
	{"value":948,"label":"Hickory Aquifer | Lampasas"},
	{"value":362,"label":"Hickory Aquifer | Llano"},
	{"value":363,"label":"Hickory Aquifer | Mason"},
	{"value":364,"label":"Hickory Aquifer | McCulloch"},
	{"value":365,"label":"Hickory Aquifer | Menard"},
	{"value":366,"label":"Hickory Aquifer | Mills"},
	{"value":367,"label":"Hickory Aquifer | San Saba"},
	{"value":950,"label":"Hickory Aquifer | Williamson"},
	{"value":368,"label":"Highland Lakes Lake/Reservoir System"},
	{"value":370,"label":"Hords Creek Lake/Reservoir"},
	{"value":371,"label":"Houston County Lake/Reservoir"},
	{"value":372,"label":"Houston Lake/Reservoir"},
	{"value":373,"label":"Hubbard Creek Lake/Reservoir"},
	{"value":374,"label":"Hubert H Moss Lake/Reservoir"},
	{"value":951,"label":"Hueco-Mesilla Bolson Aquifer ASR | El Paso"},
	{"value":375,"label":"Hueco-Mesilla Bolson Aquifer | El Paso"},
	{"value":376,"label":"Hueco-Mesilla Bolson Aquifer | Hudspeth"},
	{"value":377,"label":"Igneous Aquifer | Brewster"},
	{"value":378,"label":"Igneous Aquifer | Culberson"},
	{"value":379,"label":"Igneous Aquifer | Jeff Davis"},
	{"value":1106,"label":"Igneous Aquifer | Pecos"},
	{"value":380,"label":"Igneous Aquifer | Presidio"},
	{"value":1107,"label":"Igneous Aquifer | Reeves"},
	{"value":391,"label":"Jacksonville Lake/Reservoir"},
	{"value":392,"label":"Joe Pool Lake/Reservoir"},
	{"value":393,"label":"Johnson Creek Lake/Reservoir"},
	{"value":394,"label":"Kemp-Diversion Lake/Reservoir System"},
	{"value":396,"label":"Kirby Lake/Reservoir"},
	{"value":397,"label":"Kurth Lake/Reservoir"},
	{"value":956,"label":"LCRA New Off-Channel Reservoir (2030 Decade)"},
	{"value":398,"label":"Lake 7 (Jim Bertram Lake/Reservoir System)"},
	{"value":399,"label":"Lake Creek Lake/Reservoir"},
	{"value":954,"label":"Lake Davis Lake/Reservoir"},
	{"value":400,"label":"Lake Naconiche Lake/Reservoir"},
	{"value":1135,"label":"Lake Whitney Off-Channel Reservoir"},
	{"value":401,"label":"Langford Lake/Reservoir"},
	{"value":402,"label":"Lavaca River Off-Channel Lake/Reservoir"},
	{"value":662,"label":"Lavaca Run-of-River"},
	{"value":404,"label":"Leon Lake/Reservoir"},
	{"value":958,"label":"Leona Gravel Aquifer | Medina"},
	{"value":959,"label":"Leona Gravel Aquifer | Uvalde"},
	{"value":405,"label":"Lewisville Lake/Reservoir Non-System Portion"},
	{"value":1108,"label":"Lipan Aquifer | Coke"},
	{"value":406,"label":"Lipan Aquifer | Concho"},
	{"value":960,"label":"Lipan Aquifer | Glasscock"},
	{"value":961,"label":"Lipan Aquifer | Irion"},
	{"value":407,"label":"Lipan Aquifer | Runnels"},
	{"value":962,"label":"Lipan Aquifer | Sterling"},
	{"value":408,"label":"Lipan Aquifer | Tom Green"},
	{"value":830,"label":"Little Wichita River Lake/Reservoir System"},
	{"value":410,"label":"Livingston-Wallisville Lake/Reservoir System"},
	{"value":411,"label":"Llano Lake/Reservoir"},
	{"value":412,"label":"Local Surface Water Supply"},
	{"value":413,"label":"Loma Lake/Reservoir"},
	{"value":414,"label":"Lost Creek-Jacksboro Lake/Reservoir System"},
	{"value":963,"label":"Lytle Lake/Reservoir"},
	{"value":416,"label":"Mackenzie Lake/Reservoir"},
	{"value":1128,"label":"Manvel Mustang Bayou Reservoir"},
	{"value":417,"label":"Marathon Aquifer | Brewster"},
	{"value":418,"label":"Marble Falls Aquifer | Blanco"},
	{"value":1109,"label":"Marble Falls Aquifer | Brown"},
	{"value":419,"label":"Marble Falls Aquifer | Burnet"},
	{"value":964,"label":"Marble Falls Aquifer | Kimble"},
	{"value":420,"label":"Marble Falls Aquifer | Lampasas"},
	{"value":421,"label":"Marble Falls Aquifer | Mason"},
	{"value":422,"label":"Marble Falls Aquifer | McCulloch"},
	{"value":1110,"label":"Marble Falls Aquifer | Mills"},
	{"value":423,"label":"Marble Falls Aquifer | San Saba"},
	{"value":424,"label":"Martin Lake/Reservoir"},
	{"value":425,"label":"Marvin Nichols Lake/Reservoir"},
	{"value":965,"label":"McCarty Lake/Reservoir"},
	{"value":426,"label":"Medina Lake/Reservoir"},
	{"value":427,"label":"Meredith Lake/Reservoir"},
	{"value":428,"label":"Mexia Lake/Reservoir"},
	{"value":429,"label":"Mill Creek Lake/Reservoir"},
	{"value":430,"label":"Millers Creek Lake/Reservoir"},
	{"value":432,"label":"Mineral Wells Lake/Reservoir"},
	{"value":433,"label":"Monticello Lake/Reservoir"},
	{"value":967,"label":"Moran Lake/Reservoir"},
	{"value":434,"label":"Mountain Creek Lake/Reservoir | Colorado"},
	{"value":435,"label":"Mountain Creek Lake/Reservoir | Trinity"},
	{"value":436,"label":"Muenster Lake/Reservoir"},
	{"value":437,"label":"Murvaul Lake/Reservoir"},
	{"value":1138,"label":"NCTMWA Lake Creek Lake/Reservoir"},
	{"value":438,"label":"Nacatoch Aquifer | Bowie"},
	{"value":439,"label":"Nacatoch Aquifer | Delta"},
	{"value":968,"label":"Nacatoch Aquifer | Ellis"},
	{"value":440,"label":"Nacatoch Aquifer | Franklin"},
	{"value":442,"label":"Nacatoch Aquifer | Hopkins"},
	{"value":443,"label":"Nacatoch Aquifer | Hunt"},
	{"value":444,"label":"Nacatoch Aquifer | Kaufman"},
	{"value":445,"label":"Nacatoch Aquifer | Lamar"},
	{"value":446,"label":"Nacatoch Aquifer | Navarro"},
	{"value":447,"label":"Nacatoch Aquifer | Rains"},
	{"value":448,"label":"Nacatoch Aquifer | Red River"},
	{"value":449,"label":"Nacatoch Aquifer | Rockwall"},
	{"value":451,"label":"Nacogdoches Lake/Reservoir"},
	{"value":453,"label":"Navarro Mills Lake/Reservoir"},
	{"value":969,"label":"Navasota River Alluvium Aquifer | Grimes"},
	{"value":382,"label":"Neches Indirect Reuse"},
	{"value":663,"label":"Neches Run-of-River"},
	{"value":383,"label":"Neches-Trinity Indirect Reuse"},
	{"value":664,"label":"Neches-Trinity Run-of-River"},
	{"value":1139,"label":"New Marlin City Lake/Reservoir"},
	{"value":1137,"label":"New Throckmorton Lake/Reservoir"},
	{"value":454,"label":"North Fork Buffalo Creek Lake/Reservoir"},
	{"value":1068,"label":"North Texas MWD Lake/Reservoir System"},
	{"value":1129,"label":"Nueces Local Balancing Reservoir"},
	{"value":970,"label":"Nueces River Alluvium Aquifer | Edwards"},
	{"value":971,"label":"Nueces River Alluvium Aquifer | Real"},
	{"value":665,"label":"Nueces Run-of-River"},
	{"value":1064,"label":"Nueces-Rio Grande Indirect Reuse"},
	{"value":666,"label":"Nueces-Rio Grande Run-of-River"},
	{"value":1124,"label":"Nueces-Rio Grande Run-of-River Storage (Banco Morales)"},
	{"value":457,"label":"O' the Pines Lake/Reservoir"},
	{"value":507,"label":"OH Ivie Lake/Reservoir Non-System Portion"},
	{"value":458,"label":"Oak Creek Lake/Reservoir"},
	{"value":1112,"label":"Ogallala Aquifer ASR | Gray"},
	{"value":974,"label":"Ogallala Aquifer ASR | Hale"},
	{"value":977,"label":"Ogallala Aquifer ASR | Lubbock"},
	{"value":1113,"label":"Ogallala Aquifer ASR | Randall"},
	{"value":461,"label":"Ogallala Aquifer | Armstrong"},
	{"value":465,"label":"Ogallala Aquifer | Carson"},
	{"value":1086,"label":"Ogallala Aquifer | Collingsworth"},
	{"value":473,"label":"Ogallala Aquifer | Dickens"},
	{"value":474,"label":"Ogallala Aquifer | Donley"},
	{"value":475,"label":"Ogallala Aquifer | Ector"},
	{"value":479,"label":"Ogallala Aquifer | Glasscock"},
	{"value":480,"label":"Ogallala Aquifer | Gray"},
	{"value":482,"label":"Ogallala Aquifer | Hansford"},
	{"value":484,"label":"Ogallala Aquifer | Hemphill"},
	{"value":487,"label":"Ogallala Aquifer | Hutchinson"},
	{"value":489,"label":"Ogallala Aquifer | Lipscomb"},
	{"value":493,"label":"Ogallala Aquifer | Midland"},
	{"value":494,"label":"Ogallala Aquifer | Moore"},
	{"value":495,"label":"Ogallala Aquifer | Motley"},
	{"value":496,"label":"Ogallala Aquifer | Ochiltree"},
	{"value":497,"label":"Ogallala Aquifer | Oldham"},
	{"value":499,"label":"Ogallala Aquifer | Potter"},
	{"value":500,"label":"Ogallala Aquifer | Randall"},
	{"value":501,"label":"Ogallala Aquifer | Roberts"},
	{"value":502,"label":"Ogallala Aquifer | Sherman"},
	{"value":505,"label":"Ogallala Aquifer | Wheeler"},
	{"value":1111,"label":"Ogallala Aquifer | Winkler"},
	{"value":460,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Andrews"},
	{"value":462,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Bailey"},
	{"value":463,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Borden"},
	{"value":464,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Briscoe"},
	{"value":466,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Castro"},
	{"value":467,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Cochran"},
	{"value":469,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Crosby"},
	{"value":471,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Dawson"},
	{"value":472,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Deaf Smith"},
	{"value":476,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Floyd"},
	{"value":477,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Gaines"},
	{"value":478,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Garza"},
	{"value":931,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Garza"},
	{"value":481,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Hale"},
	{"value":485,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Hockley"},
	{"value":486,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Howard"},
	{"value":488,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Lamb"},
	{"value":490,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Lubbock"},
	{"value":491,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Lynn"},
	{"value":492,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Martin"},
	{"value":498,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Parmer"},
	{"value":503,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Swisher"},
	{"value":504,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Terry"},
	{"value":506,"label":"Ogallala and Edwards-Trinity-High Plains Aquifers | Yoakum"},
	{"value":980,"label":"Ogallala and Rita Blanca Aquifers | Dallam"},
	{"value":981,"label":"Ogallala and Rita Blanca Aquifers | Hartley"},
	{"value":982,"label":"Oklahoma Hugo Lake/Reservoir"},
	{"value":1016,"label":"Oklahoma Run-of-River"},
	{"value":509,"label":"Olney-Cooper Lake/Reservoir System"},
	{"value":510,"label":"Other Aquifer | Anderson"},
	{"value":511,"label":"Other Aquifer | Angelina"},
	{"value":513,"label":"Other Aquifer | Armstrong"},
	{"value":514,"label":"Other Aquifer | Bastrop"},
	{"value":515,"label":"Other Aquifer | Borden"},
	{"value":518,"label":"Other Aquifer | Brewster"},
	{"value":519,"label":"Other Aquifer | Briscoe"},
	{"value":521,"label":"Other Aquifer | Burnet"},
	{"value":984,"label":"Other Aquifer | Cherokee"},
	{"value":522,"label":"Other Aquifer | Childress"},
	{"value":524,"label":"Other Aquifer | Coke"},
	{"value":525,"label":"Other Aquifer | Coleman"},
	{"value":527,"label":"Other Aquifer | Collingsworth"},
	{"value":529,"label":"Other Aquifer | Concho"},
	{"value":531,"label":"Other Aquifer | Cottle"},
	{"value":985,"label":"Other Aquifer | Crosby"},
	{"value":535,"label":"Other Aquifer | Dickens"},
	{"value":536,"label":"Other Aquifer | Donley"},
	{"value":538,"label":"Other Aquifer | El Paso"},
	{"value":540,"label":"Other Aquifer | Fannin"},
	{"value":541,"label":"Other Aquifer | Fayette"},
	{"value":986,"label":"Other Aquifer | Floyd"},
	{"value":987,"label":"Other Aquifer | Foard"},
	{"value":988,"label":"Other Aquifer | Garza"},
	{"value":544,"label":"Other Aquifer | Hall"},
	{"value":990,"label":"Other Aquifer | Hardeman"},
	{"value":545,"label":"Other Aquifer | Henderson"},
	{"value":548,"label":"Other Aquifer | Houston"},
	{"value":549,"label":"Other Aquifer | Hudspeth"},
	{"value":1134,"label":"Other Aquifer | Kent"},
	{"value":555,"label":"Other Aquifer | King"},
	{"value":557,"label":"Other Aquifer | Llano"},
	{"value":1114,"label":"Other Aquifer | Mason"},
	{"value":560,"label":"Other Aquifer | McCulloch"},
	{"value":562,"label":"Other Aquifer | Mitchell"},
	{"value":564,"label":"Other Aquifer | Motley"},
	{"value":565,"label":"Other Aquifer | Nacogdoches"},
	{"value":1115,"label":"Other Aquifer | Navarro"},
	{"value":569,"label":"Other Aquifer | Pecos"},
	{"value":575,"label":"Other Aquifer | Runnels"},
	{"value":991,"label":"Other Aquifer | Rusk"},
	{"value":576,"label":"Other Aquifer | Sabine"},
	{"value":577,"label":"Other Aquifer | San Augustine"},
	{"value":578,"label":"Other Aquifer | Scurry"},
	{"value":579,"label":"Other Aquifer | Shackelford"},
	{"value":580,"label":"Other Aquifer | Smith"},
	{"value":582,"label":"Other Aquifer | Stephens"},
	{"value":1133,"label":"Other Aquifer | Stonewall"},
	{"value":587,"label":"Other Aquifer | Travis"},
	{"value":588,"label":"Other Aquifer | Trinity"},
	{"value":592,"label":"Other Aquifer | Wheeler"},
	{"value":594,"label":"Other Aquifer | Wilbarger"},
	{"value":595,"label":"Other Aquifer | Williamson"},
	{"value":600,"label":"Palestine Lake/Reservoir"},
	{"value":601,"label":"Palo Duro Lake/Reservoir"},
	{"value":602,"label":"Palo Pinto Lake/Reservoir"},
	{"value":603,"label":"Pat Cleburne Lake/Reservoir"},
	{"value":604,"label":"Pat Mayse Lake/Reservoir"},
	{"value":138,"label":"Pecos Valley Aquifer | Andrews"},
	{"value":607,"label":"Pinkston Lake/Reservoir"},
	{"value":608,"label":"Post Lake/Reservoir"},
	{"value":609,"label":"Queen City Aquifer | Anderson"},
	{"value":610,"label":"Queen City Aquifer | Angelina"},
	{"value":611,"label":"Queen City Aquifer | Atascosa"},
	{"value":612,"label":"Queen City Aquifer | Bastrop"},
	{"value":613,"label":"Queen City Aquifer | Brazos"},
	{"value":614,"label":"Queen City Aquifer | Burleson"},
	{"value":615,"label":"Queen City Aquifer | Caldwell"},
	{"value":616,"label":"Queen City Aquifer | Camp"},
	{"value":617,"label":"Queen City Aquifer | Cass"},
	{"value":618,"label":"Queen City Aquifer | Cherokee"},
	{"value":619,"label":"Queen City Aquifer | Fayette"},
	{"value":620,"label":"Queen City Aquifer | Freestone"},
	{"value":621,"label":"Queen City Aquifer | Frio"},
	{"value":622,"label":"Queen City Aquifer | Gonzales"},
	{"value":623,"label":"Queen City Aquifer | Gregg"},
	{"value":624,"label":"Queen City Aquifer | Grimes"},
	{"value":1004,"label":"Queen City Aquifer | Guadalupe"},
	{"value":625,"label":"Queen City Aquifer | Harrison"},
	{"value":626,"label":"Queen City Aquifer | Henderson"},
	{"value":627,"label":"Queen City Aquifer | Houston"},
	{"value":628,"label":"Queen City Aquifer | La Salle"},
	{"value":629,"label":"Queen City Aquifer | Lee"},
	{"value":630,"label":"Queen City Aquifer | Leon"},
	{"value":631,"label":"Queen City Aquifer | Madison"},
	{"value":632,"label":"Queen City Aquifer | Marion"},
	{"value":633,"label":"Queen City Aquifer | McMullen"},
	{"value":634,"label":"Queen City Aquifer | Milam"},
	{"value":635,"label":"Queen City Aquifer | Morris"},
	{"value":636,"label":"Queen City Aquifer | Nacogdoches"},
	{"value":637,"label":"Queen City Aquifer | Robertson"},
	{"value":638,"label":"Queen City Aquifer | Rusk"},
	{"value":639,"label":"Queen City Aquifer | Smith"},
	{"value":1010,"label":"Queen City Aquifer | Titus"},
	{"value":1011,"label":"Queen City Aquifer | Trinity"},
	{"value":640,"label":"Queen City Aquifer | Upshur"},
	{"value":641,"label":"Queen City Aquifer | Van Zandt"},
	{"value":642,"label":"Queen City Aquifer | Walker"},
	{"value":643,"label":"Queen City Aquifer | Wilson"},
	{"value":644,"label":"Queen City Aquifer | Wood"},
	{"value":1067,"label":"Rainwater Harvesting"},
	{"value":646,"label":"Ralph Hall Lake/Reservoir"},
	{"value":647,"label":"Randell Lake/Reservoir"},
	{"value":648,"label":"Ray Hubbard Lake/Reservoir"},
	{"value":649,"label":"Ray Roberts Lake/Reservoir Non-System Portion"},
	{"value":650,"label":"Ray Roberts-Lewisville-Grapevine Lake/Reservoir System"},
	{"value":651,"label":"Red Bluff Lake/Reservoir"},
	{"value":386,"label":"Red Indirect Reuse"},
	{"value":1131,"label":"Red River Off-Channel Reservoir"},
	{"value":667,"label":"Red Run-of-River"},
	{"value":1015,"label":"Regulating Lake/Reservoir"},
	{"value":1075,"label":"Rhines Lake/Reservoir"},
	{"value":652,"label":"Richland Chambers Lake/Reservoir Non-System Portion"},
	{"value":653,"label":"Ringgold Lake/Reservoir"},
	{"value":387,"label":"Rio Grande Indirect Reuse"},
	{"value":668,"label":"Rio Grande Run-of-River"},
	{"value":1081,"label":"Rio Grande Run-of-River Storage"},
	{"value":679,"label":"Rusk City Lake/Reservoir"},
	{"value":1017,"label":"Rustler Aquifer | Brewster"},
	{"value":1116,"label":"Rustler Aquifer | Crane"},
	{"value":680,"label":"Rustler Aquifer | Culberson"},
	{"value":1117,"label":"Rustler Aquifer | Jeff Davis"},
	{"value":1018,"label":"Rustler Aquifer | Loving"},
	{"value":681,"label":"Rustler Aquifer | Pecos"},
	{"value":682,"label":"Rustler Aquifer | Reeves"},
	{"value":1019,"label":"Rustler Aquifer | Ward"},
	{"value":1118,"label":"Rustler Aquifer | Winkler"},
	{"value":1077,"label":"STPNOC Lake/Reservoir"},
	{"value":953,"label":"Sabine Indirect Reuse"},
	{"value":669,"label":"Sabine Run-of-River"},
	{"value":683,"label":"Sam Rayburn-Steinhagen Lake/Reservoir System"},
	{"value":1020,"label":"San Angelo Lakes Lake/Reservoir System"},
	{"value":1125,"label":"San Antonio Indirect Reuse"},
	{"value":670,"label":"San Antonio Run-of-River"},
	{"value":671,"label":"San Antonio-Nueces Run-of-River"},
	{"value":684,"label":"San Augustine Lake/Reservoir"},
	{"value":1021,"label":"San Bernard River Alluvium Aquifer | Austin"},
	{"value":388,"label":"San Jacinto Indirect Reuse"},
	{"value":1022,"label":"San Jacinto River Alluvium Aquifer | Walker"},
	{"value":672,"label":"San Jacinto Run-of-River"},
	{"value":673,"label":"San Jacinto-Brazos Run-of-River"},
	{"value":1119,"label":"San Marcos River Alluvium Aquifer | Caldwell"},
	{"value":1141,"label":"Santa Cruz Lake/Reservoir"},
	{"value":685,"label":"Santa Rosa Lake/Reservoir"},
	{"value":1023,"label":"Seymour Aquifer | Archer"},
	{"value":686,"label":"Seymour Aquifer | Baylor"},
	{"value":687,"label":"Seymour Aquifer | Briscoe"},
	{"value":688,"label":"Seymour Aquifer | Childress"},
	{"value":689,"label":"Seymour Aquifer | Clay"},
	{"value":690,"label":"Seymour Aquifer | Collingsworth"},
	{"value":694,"label":"Seymour Aquifer | Fisher"},
	{"value":695,"label":"Seymour Aquifer | Foard"},
	{"value":696,"label":"Seymour Aquifer | Hall"},
	{"value":697,"label":"Seymour Aquifer | Hardeman"},
	{"value":698,"label":"Seymour Aquifer | Haskell"},
	{"value":699,"label":"Seymour Aquifer | Jones"},
	{"value":700,"label":"Seymour Aquifer | Kent"},
	{"value":701,"label":"Seymour Aquifer | Knox"},
	{"value":702,"label":"Seymour Aquifer | Motley"},
	{"value":1120,"label":"Seymour Aquifer | Scurry"},
	{"value":703,"label":"Seymour Aquifer | Stonewall"},
	{"value":1024,"label":"Seymour Aquifer | Throckmorton"},
	{"value":705,"label":"Seymour Aquifer | Wichita"},
	{"value":706,"label":"Seymour Aquifer | Wilbarger"},
	{"value":1025,"label":"Seymour Aquifer | Young"},
	{"value":1026,"label":"Simsboro Aquifer ASR | Brazos"},
	{"value":708,"label":"Sparta Aquifer | Anderson"},
	{"value":709,"label":"Sparta Aquifer | Angelina"},
	{"value":710,"label":"Sparta Aquifer | Atascosa"},
	{"value":711,"label":"Sparta Aquifer | Bastrop"},
	{"value":712,"label":"Sparta Aquifer | Brazos"},
	{"value":713,"label":"Sparta Aquifer | Burleson"},
	{"value":714,"label":"Sparta Aquifer | Cherokee"},
	{"value":715,"label":"Sparta Aquifer | Fayette"},
	{"value":716,"label":"Sparta Aquifer | Frio"},
	{"value":717,"label":"Sparta Aquifer | Gonzales"},
	{"value":718,"label":"Sparta Aquifer | Grimes"},
	{"value":719,"label":"Sparta Aquifer | Houston"},
	{"value":720,"label":"Sparta Aquifer | La Salle"},
	{"value":721,"label":"Sparta Aquifer | Lee"},
	{"value":722,"label":"Sparta Aquifer | Leon"},
	{"value":723,"label":"Sparta Aquifer | Madison"},
	{"value":724,"label":"Sparta Aquifer | McMullen"},
	{"value":725,"label":"Sparta Aquifer | Nacogdoches"},
	{"value":726,"label":"Sparta Aquifer | Robertson"},
	{"value":727,"label":"Sparta Aquifer | Sabine"},
	{"value":728,"label":"Sparta Aquifer | San Augustine"},
	{"value":729,"label":"Sparta Aquifer | Trinity"},
	{"value":730,"label":"Sparta Aquifer | Walker"},
	{"value":731,"label":"Sparta Aquifer | Wilson"},
	{"value":1036,"label":"Sparta and Queen City Aquifer ASR | Brazos"},
	{"value":732,"label":"Squaw Creek Lake/Reservoir"},
	{"value":733,"label":"Stamford Lake/Reservoir"},
	{"value":1037,"label":"Strawn Lake/Reservoir"},
	{"value":734,"label":"Striker Lake/Reservoir"},
	{"value":389,"label":"Sulphur Indirect Reuse"},
	{"value":674,"label":"Sulphur Run-of-River"},
	{"value":735,"label":"Sulphur Springs Lake/Reservoir"},
	{"value":736,"label":"Sweetwater Lake/Reservoir"},
	{"value":810,"label":"TRWD Lake/Reservoir System"},
	{"value":737,"label":"Tankersley Lake/Reservoir"},
	{"value":738,"label":"Tawakoni Lake/Reservoir"},
	{"value":739,"label":"Teague City Lake/Reservoir"},
	{"value":740,"label":"Tehuacana Lake/Reservoir"},
	{"value":741,"label":"Terrell Lake/Reservoir"},
	{"value":742,"label":"Texana Lake/Reservoir"},
	{"value":744,"label":"Texoma Lake/Reservoir Non-System Portion"},
	{"value":746,"label":"Throckmorton Lake/Reservoir"},
	{"value":747,"label":"Timpson Lake/Reservoir"},
	{"value":748,"label":"Toledo Bend Lake/Reservoir"},
	{"value":1049,"label":"Tradinghouse Creek Lake/Reservoir"},
	{"value":1038,"label":"Trammel Lake/Reservoir"},
	{"value":751,"label":"Trinidad City Lake/Reservoir"},
	{"value":752,"label":"Trinidad Lake/Reservoir"},
	{"value":1041,"label":"Trinity Aquifer ASR | Bandera"},
	{"value":1122,"label":"Trinity Aquifer ASR | Collin"},
	{"value":1042,"label":"Trinity Aquifer ASR | Hays"},
	{"value":1043,"label":"Trinity Aquifer ASR | Johnson"},
	{"value":1044,"label":"Trinity Aquifer ASR | Kerr"},
	{"value":1045,"label":"Trinity Aquifer ASR | McLennan"},
	{"value":1123,"label":"Trinity Aquifer ASR | Tarrant"},
	{"value":1047,"label":"Trinity Aquifer ASR | Williamson"},
	{"value":753,"label":"Trinity Aquifer | Bandera"},
	{"value":755,"label":"Trinity Aquifer | Bell"},
	{"value":756,"label":"Trinity Aquifer | Bexar"},
	{"value":757,"label":"Trinity Aquifer | Blanco"},
	{"value":758,"label":"Trinity Aquifer | Bosque"},
	{"value":759,"label":"Trinity Aquifer | Brown"},
	{"value":760,"label":"Trinity Aquifer | Burnet"},
	{"value":761,"label":"Trinity Aquifer | Caldwell"},
	{"value":762,"label":"Trinity Aquifer | Callahan"},
	{"value":763,"label":"Trinity Aquifer | Collin"},
	{"value":764,"label":"Trinity Aquifer | Comal"},
	{"value":765,"label":"Trinity Aquifer | Comanche"},
	{"value":766,"label":"Trinity Aquifer | Cooke"},
	{"value":767,"label":"Trinity Aquifer | Coryell"},
	{"value":768,"label":"Trinity Aquifer | Dallas"},
	{"value":769,"label":"Trinity Aquifer | Delta"},
	{"value":770,"label":"Trinity Aquifer | Denton"},
	{"value":771,"label":"Trinity Aquifer | Eastland"},
	{"value":772,"label":"Trinity Aquifer | Ellis"},
	{"value":773,"label":"Trinity Aquifer | Erath"},
	{"value":774,"label":"Trinity Aquifer | Falls"},
	{"value":775,"label":"Trinity Aquifer | Fannin"},
	{"value":777,"label":"Trinity Aquifer | Grayson"},
	{"value":1040,"label":"Trinity Aquifer | Guadalupe"},
	{"value":778,"label":"Trinity Aquifer | Hamilton"},
	{"value":779,"label":"Trinity Aquifer | Hays"},
	{"value":780,"label":"Trinity Aquifer | Hill"},
	{"value":781,"label":"Trinity Aquifer | Hood"},
	{"value":782,"label":"Trinity Aquifer | Hunt"},
	{"value":784,"label":"Trinity Aquifer | Johnson"},
	{"value":785,"label":"Trinity Aquifer | Kaufman"},
	{"value":786,"label":"Trinity Aquifer | Kendall"},
	{"value":787,"label":"Trinity Aquifer | Kerr"},
	{"value":788,"label":"Trinity Aquifer | Lamar"},
	{"value":789,"label":"Trinity Aquifer | Lampasas"},
	{"value":1121,"label":"Trinity Aquifer | Lee"},
	{"value":790,"label":"Trinity Aquifer | Limestone"},
	{"value":791,"label":"Trinity Aquifer | McLennan"},
	{"value":792,"label":"Trinity Aquifer | Medina"},
	{"value":793,"label":"Trinity Aquifer | Milam"},
	{"value":794,"label":"Trinity Aquifer | Mills"},
	{"value":795,"label":"Trinity Aquifer | Montague"},
	{"value":796,"label":"Trinity Aquifer | Navarro"},
	{"value":797,"label":"Trinity Aquifer | Palo Pinto"},
	{"value":798,"label":"Trinity Aquifer | Parker"},
	{"value":800,"label":"Trinity Aquifer | Red River"},
	{"value":801,"label":"Trinity Aquifer | Rockwall"},
	{"value":802,"label":"Trinity Aquifer | Somervell"},
	{"value":803,"label":"Trinity Aquifer | Tarrant"},
	{"value":804,"label":"Trinity Aquifer | Taylor"},
	{"value":805,"label":"Trinity Aquifer | Travis"},
	{"value":806,"label":"Trinity Aquifer | Uvalde"},
	{"value":807,"label":"Trinity Aquifer | Williamson"},
	{"value":808,"label":"Trinity Aquifer | Wise"},
	{"value":390,"label":"Trinity Indirect Reuse"},
	{"value":1048,"label":"Trinity River Alluvium Aquifer | Walker"},
	{"value":675,"label":"Trinity Run-of-River"},
	{"value":1039,"label":"Trinity and/or Brackish Edwards Aquifer ASR | Comal"},
	{"value":676,"label":"Trinity-San Jacinto Run-of-River"},
	{"value":811,"label":"Turkey Creek Lake/Reservoir"},
	{"value":812,"label":"Turkey Peak Lake/Reservoir"},
	{"value":814,"label":"Twin Oak Lake/Reservoir"},
	{"value":815,"label":"Tyler Lake/Reservoir"},
	{"value":817,"label":"Victor Braunig Lake/Reservoir"},
	{"value":818,"label":"Waco Lake/Reservoir"},
	{"value":819,"label":"Waxahachie Lake/Reservoir"},
	{"value":821,"label":"Weatherford Lake/Reservoir"},
	{"value":822,"label":"Welsh Lake/Reservoir"},
	{"value":823,"label":"West Texas Bolsons Aquifer | Culberson"},
	{"value":824,"label":"West Texas Bolsons Aquifer | Hudspeth"},
	{"value":825,"label":"West Texas Bolsons Aquifer | Jeff Davis"},
	{"value":826,"label":"West Texas Bolsons Aquifer | Presidio"},
	{"value":827,"label":"Wheeler Branch Off-Channel Lake/Reservoir"},
	{"value":828,"label":"White River Lake/Reservoir"},
	{"value":829,"label":"White Rock Lake/Reservoir"},
	{"value":832,"label":"Winters Lake/Reservoir"},
	{"value":833,"label":"Woodbine Aquifer | Collin"},
	{"value":834,"label":"Woodbine Aquifer | Cooke"},
	{"value":835,"label":"Woodbine Aquifer | Dallas"},
	{"value":837,"label":"Woodbine Aquifer | Denton"},
	{"value":838,"label":"Woodbine Aquifer | Ellis"},
	{"value":839,"label":"Woodbine Aquifer | Fannin"},
	{"value":840,"label":"Woodbine Aquifer | Grayson"},
	{"value":841,"label":"Woodbine Aquifer | Hill"},
	{"value":842,"label":"Woodbine Aquifer | Hunt"},
	{"value":843,"label":"Woodbine Aquifer | Johnson"},
	{"value":844,"label":"Woodbine Aquifer | Kaufman"},
	{"value":845,"label":"Woodbine Aquifer | Lamar"},
	{"value":847,"label":"Woodbine Aquifer | McLennan"},
	{"value":848,"label":"Woodbine Aquifer | Navarro"},
	{"value":850,"label":"Woodbine Aquifer | Red River"},
	{"value":851,"label":"Woodbine Aquifer | Rockwall"},
	{"value":852,"label":"Woodbine Aquifer | Tarrant"},
	{"value":1054,"label":"Woodson Lake/Reservoir"},
	{"value":854,"label":"Wright Patman Lake/Reservoir"},
	{"value":855,"label":"Yegua-Jackson Aquifer | Angelina"},
	{"value":1055,"label":"Yegua-Jackson Aquifer | Atascosa"},
	{"value":856,"label":"Yegua-Jackson Aquifer | Brazos"},
	{"value":857,"label":"Yegua-Jackson Aquifer | Burleson"},
	{"value":858,"label":"Yegua-Jackson Aquifer | Fayette"},
	{"value":1057,"label":"Yegua-Jackson Aquifer | Gonzales"},
	{"value":859,"label":"Yegua-Jackson Aquifer | Grimes"},
	{"value":860,"label":"Yegua-Jackson Aquifer | Houston"},
	{"value":1058,"label":"Yegua-Jackson Aquifer | Karnes"},
	{"value":1059,"label":"Yegua-Jackson Aquifer | La Salle"},
	{"value":862,"label":"Yegua-Jackson Aquifer | Lee"},
	{"value":1060,"label":"Yegua-Jackson Aquifer | Leon"},
	{"value":1061,"label":"Yegua-Jackson Aquifer | Madison"},
	{"value":863,"label":"Yegua-Jackson Aquifer | Nacogdoches"},
	{"value":864,"label":"Yegua-Jackson Aquifer | Polk"},
	{"value":865,"label":"Yegua-Jackson Aquifer | Sabine"},
	{"value":866,"label":"Yegua-Jackson Aquifer | San Augustine"},
	{"value":867,"label":"Yegua-Jackson Aquifer | Starr"},
	{"value":868,"label":"Yegua-Jackson Aquifer | Trinity"},
	{"value":870,"label":"Yegua-Jackson Aquifer | Walker"},
	{"value":871,"label":"Yegua-Jackson Aquifer | Washington"},
	{"value":872,"label":"Yegua-Jackson Aquifer | Webb"},
	{"value":1063,"label":"Yegua-Jackson Aquifer | Wilson"},
	{"value":873,"label":"Yegua-Jackson Aquifer | Zapata"}
];